### ISSUE TITLE
get re-arranged order of items using layoutEnd

### ISSUE THREAD

**Issue by woldsnewmedia** [haltu/muuri#104]
Hi,

I have the Muuri working perfectly now apart from one thing.

What I want to do is .on('layoutEnd') , get the changed values stored in data-id after some of the items have been moved around, but all I get no matter what I try is (for 8 items) 1,2,3,4,5,6,7,8 - when I would expect, after moving some items around, something like for example, 1,3,4,2,6,5,8,7 etc).

I tried the answer in the other question about save/load position but same problem - again I want to try save the re-ordered data-id values on('layoutEnd'), once I have these I should be able to do my own position re-loader.

Any suggestions?

Craig.

**Comment by woldsnewmedia** [comment]
Hi again,

Just to follow on, when I move items, I can see the data-id changing in the developer console, I just don't seem to know how to access them with on('layoutEnd')

Any help greatly appreciated!

Craig.

**Comment by woldsnewmedia** [comment]
Hi (again!),

Once I have setup my items as I have now from the database, once they are all setup, is it possible using some variant of 

// Sort items with a presorted array of items.
grid.sort(presortedItems);

To re-arrange the items to match some kind of array/list of saved items (by data-id for example) - that is assuming I have worked out a way to get the re-ordered item data-id's to save in the first place from the .on('layoutEnd') event?

Craig.

**Comment by Aldo-f** [comment]
Hey, had to do the same thing.

Made a Codepen.io solution. 
Just without keeping the data until next reload.
But that would be no problem if you save the last response as a cookie.

https://codepen.io/AldoF/pen/VwbGvPo

Most imported parts:
```js
// muuri.init.js

// Init Muuri
const options = {
  dragEnabled: true,
  sortData: {
    cookie: function (item, element) {
      // Sort by the cookie value
      console.log(element);
      return parseFloat(element.getAttribute("data-cookie"));
    },
    title: function (item, element) {
      // Sort by title
      return element.getAttribute("data-title").toUpperCase();
    }
  }
};
const grid = new Muuri(".grid", options);

// First sort by cookie value, if not exist => use title
grid.sort("cookie title");

grid.on("layoutEnd", function (items) {
  // Save current layout to cookie
  const cookieSort = $.map(items, (e) => e._id).join(",");

  console.log(cookieSort); // 2,4,3,5

  // TODO: Add these values to a cookie, and use the cookie on reload to add it tho the specific DOM-elements
});
```

```html
<!-- index.html -->

<div class="grid">

  <div class="item w3" data-title="Cookie 1" data-cookie="1"> <!-- this line -->
    <div class="item-content">
      <!-- Safe zone, enter your custom markup -->
      Lorem ipsum
      <!-- Safe zone ends -->
    </div>
  </div>
</div>
```
