### ISSUE TITLE
Center all items in their container

### ISSUE THREAD

**Issue by woldsnewmedia** [haltu/muuri#105]
Hi,

Is it possible to horizontally center all the grid items so that as screen width/resolution changes, they sit horizontally centered as opposed to to the left?

Craig.

**Comment by woldsnewmedia** [comment]
Hi,

I have just found on Google the following code - how do I, using this prototype, get the relevant value for width with which to try and dynamically set my container width?

var origRefreshDimensions = Muuri.prototype._refreshDimensions;
Muuri.prototype._refreshDimensions = function () {
  // Do custom manipulation here...
 // *** Need value here to set my container width? *****
  return origRefreshDimensions.call(this);
};



craig

**Comment by niklasramo** [comment]
You probably need to build a custom layout algorithm for that. Here's an example: https://codepen.io/niklasramo/pen/LLbLLd

**Comment by mspanish** [comment]
I am finding this would be a really helpful feature too - I'll try to post back if I figure out a solution, I don't think pure CSS will work in this case.

**Comment by mspanish** [comment]
This is a bit of a hacky workaround, but I center my grid items using jQuery - I use a new class .gridHide for this grid so it doesn't affect other ones that don't need centering - and add a small offset to account for my letters having a slightly right placement.

```
$('.gridLetters').css({'opacity':1, 'color':'white'});

var w = $('.grid').width();
var iw = 0;
$('.item').each(function(){
  iw = iw + $(this).width();
})
var offset = iw *.065;
//   toastr.info(iw)
var move = w/2 - (iw/2);

//toastr.info('move is '+move)
$('.grid').css({'background-color': 'transparent','margin-left':move-offset})
$('.gridHide').animate({
  opacity: 1
},1000)
```
![center](https://user-images.githubusercontent.com/206150/34471434-085d072e-eef6-11e7-8dce-e54e7e3bcae4.png)

**Comment by niklasramo** [comment]
I actually gave this some thought and wondered if this is something that could be added to the core as a layout option, but it turns out this feature would need it's own layout algorithm so this is best left outside the core. But yep, the way to go about doing this is definitely creating a custom layout algorithm and providing it to Muuri.
