### ISSUE TITLE
Grid displacement with React

### ISSUE THREAD

**Issue by awreccan** [haltu/muuri#106]
Rendering a new UI element while an item is being dragged is common UX. For example, one may want to render a banner as shown in [this Pen](https://codepen.io/awreccan/pen/ZaLLzQ). But that causes Muuri to calculate offsets wrongly, resulting in the mousedown cursor being displaced from the original point of mousedown on the item.

Any suggestions on a workaround?

**Comment by awreccan** [comment]
By the way, this happens with both the dragInit and dragStart events

**Comment by niklasramo** [comment]
Yep, I built the [dragContainer](https://github.com/haltu/muuri#dragcontainer-) option for this kind of use cases, and also for dragging item between two lists.

**Comment by awreccan** [comment]
Thanks. That answered my question. For future readers, apologies but I forgot to retain the pen linked above in its original state - I have since edited it and it no longer applies.
