### ISSUE TITLE
Suggestion: Be explicit on how to make different-sized items

### ISSUE THREAD

**Issue by pfalcon** [haltu/muuri#108]
It's my 2nd day of looking in Muuri, and I only now realized that README doesn't say anything on how to achieve e.g. 2x1, 1x2, 2x2 items in the grid, even though demo at https://haltu.github.io/muuri/ shows them.

As there's no in-tree demo (https://github.com/haltu/muuri/issues/107), I had to wade thru browser "Show sources" and include files, to figure out it's done in either too-plain or hackish way, depending on the outlook:

~~~
.item {
  position: absolute;
  width: 100px;
  height: 100px;
  margin: 10px;
}
.item.h2 {
  height: 220px;
  line-height: 220px;
}
.item.w2 {
  width: 220px;
}
~~~

I'd err on the side of calling it hackish, because a user needs to pre-create all the needed "Nx" classes, then if the base element sizes/margin is changed, all these adhoc styles need to be recalculated manually.

Consequently:

1. How about doing better, like allowing user to specify dimensions in terms of base item size? (That would be needed to support interactive resizing anyway.)
2. If that can't be done right away, how about adding a paragraph on how to deal with that in the meantime to the README?

And I can't emphasize enough how #107 would help.

**Comment by niklasramo** [comment]
Good suggestions.

> How about doing better, like allowing user to specify dimensions in terms of base item size? (That would be needed to support interactive resizing anyway.)

I can definitely see the need for having an API for defining items' base width/height and possibly also gutter size, but I don't think it belongs to Muuri's core. Maybe a plugin would suffice in this case? The API, as it stands, should be sufficient to build a plugin that does what you suggest.

> If that can't be done right away, how about adding a paragraph on how to deal with that in the meantime to the README?

There are quite a lot of "good to know" things which are not documented at all or not clearly enough and I've been planning to write down some Muuri tutorials to address this. This would be a good subject, for sure. However, time is limited, and I rather first concentrate on finishing the few missing features that are blocking the 1.0.0 release. So it might take while before I get to it ☹️ Some help in this area would be welcome 🙂

**Comment by pfalcon** [comment]
I can relate to the idea that a project may have its defined scope, and unlimited amount of features won't fit into it. After all, people who choose Muuri over alternatives probably look for something unbloated and without big dependencies.

At the same time, it depends on what to define as a baseline functionality. I'm not sure if Gridster http://dsmorse.github.io/gridster.js/ can be called a "gold standard", but at least its original repo has 6K+ stars: https://github.com/ducksboard/gridster.js . That's what I used to use too, and find being able to define item sizes in terms of multiple of a base size to be quite natural.

And I'm just trying to explore a new promise of "JavaScript with a human face", where you don't need to include close to a megabyte of mind-boggling code to get this done, like we used to with jQuery. But I'm not a JS programmer myself and not sure if I'm ready to dive into it trying to implement myself ;-).

Anyway, there's no hurry, and getting 1.0 release out if more important, and maybe other people can comment whether it's a useful feature to have.

Thanks!

**Comment by niklasramo** [comment]
Good ol' gridster =) I still remember when I first played around with it years ago, felt like magic 😄 Muuri's influences lie in the [Isotope](https://isotope.metafizzy.co/) and [Packery](https://packery.metafizzy.co/) direction, though. Personally, I consider those two the gold standard for the stuff that Muuri is also trying to do. Muuri just has bit different approach and some variation in the features. The key differentiator is that in it's core Muuri is just a layout engine, that just happens to provide some useful functionality for your custom layouts.
