### ISSUE TITLE
Blank space that can't be filled when element can't fit in the space

### ISSUE THREAD

**Issue by cgomezmendez** [haltu/muuri#110]
To reproduce it drag H pod (wider than the others) to the right corner and you will see that it goes to the left corner of the next row and leave an empty space that can't be filled.

https://jsfiddle.net/y29km3hj/1/

**Comment by niklasramo** [comment]
Yep, that's how the layout algorithm is supposed to work out of the box. If you want the gap to be filled you need to explicitly set `layout: {fillGaps: true}` in the options: https://jsfiddle.net/y29km3hj/2/
