### ISSUE TITLE
Content in empty grid

### ISSUE THREAD

**Issue by awreccan** [haltu/muuri#112]
What if we want to render content inside the grid when the grid becomes empty? Can the grid resize itself based on that content's dimensions?

In the following demo, I have added a div inside the grid container of one of the Kanban grids on https://haltu.github.io/muuri/. When I empty the grid out, I simulate a height increase in that div. To update the grid's height to contain that div, the straightforward way seems to be to read the div's dimensions and write to the grid container's min-height style property. But is there / should Muuri provide a more elegant solution?

Demo: https://youtu.be/WBCYVY7CN_w

**Comment by niklasramo** [comment]
This is one of those things I was having hard time to make more elegant and in the end (after a lot of testing with different techniques) came to the conclusion that min-width/min-height _is_ the most elegant way to handle it, at least in my opinion. No extra code needed, just basic css.

I'm open to suggestions though. If you have an idea how to handle this more gracefully please let me know 🙂

**Comment by awreccan** [comment]
I have been trying to do this by making the empty-state content a grid item that I `show()` or `hide()` depending on the state of the grid. Assuming that I can't implement it by changing the min-height because of other considerations in my application, there are two options:

### defaultStartPredicate function
I need an item to affect the layout but not be draggable (the grid's other items need to be draggable). Based on the current API, it seems the only way to do this is to provide a dragStartPredicate function that overrides the defaultStartPredicate and rejects drag requests on the empty-state content item. But that is a shame, since the defaultStartPredicate does a lot of work I don't want to replicate. Ideally I should be able to provide a dragStartPredicate function that gets the defaultStartPredicate as an argument, so that I can enhance, rather than replace, its functionality. Would you like a PR to that effect?

### specialised Item
Going past the current API, what if I wanted to create a watered-down version of grid Item? Going through the Item constructor, it looks like an item has 6 properties. What if I wanted just the 3 checked ones:

- [x] visibility control
- [x] animation control
- [x] affects grid layout
- [ ] migration
- [ ] release
- [ ] drag

To do that, would it be enough to comment out [these 3 lines](https://github.com/haltu/muuri/blob/master/muuri.js?utf8=%E2%9C%93#L1458-L1465)?

**Comment by awreccan** [comment]
^ comment updated with edits

**Comment by niklasramo** [comment]
Actually it is pretty straightforward to disable dragging for specific items while still enjoying the benefits of the default drag start predicate. Here's an example: https://codepen.io/niklasramo/pen/LOzZPo. You were on the right track in your example.

I think that example also serves as a "watered down" item example, so no need to add any extra code for that kind of functionality in my opinion. Thanks for suggesting though! Muuri has not had too many contributions so far 🙂

**Comment by awreccan** [comment]
Ah I should've realised one can directly access `Muuri.ItemDrag.defaultStartPredicate`! Thanks!
