### ISSUE TITLE
Prevent script break after destroy

### ISSUE THREAD

**Issue by ALTELMA** [haltu/muuri#113]
From the last issue I still use option to destroy and reinit muuri,
But I still facing problem when drag fastest.

I get error message like this
`Uncaught TypeError: Cannot read property '_settings' of null`

Can you help me to fix this?

**Comment by niklasramo** [comment]
Can you please provide a reduced test case? Preferably set up in codepen, jsfiddle or a similar service where I can easily fiddle around with it.

**Comment by ALTELMA** [comment]
You can close this issue. I already fixed it.
