### ISSUE TITLE
Prevent dragging for specific elements

### ISSUE THREAD

**Issue by maorpolak** [haltu/muuri#116]
I have a muuri list where the "item-content" area contains form inputs. These inputs should be editable. However, when I try to edit them, it drags the entire 'item'.

Is there a way to disable dragging for specific elements inside the 'item-content' area?

I tried the following, but it didn't work:
```
grid.on('dragInit', function (item, event) {
     if ($(event.target).is('input')) {
         event.preventDefault(); 
    }
});
```

**Comment by awreccan** [comment]
If you know the index of the item you want to disable dragging for:
```js
let indexToDisableDraggingFor;
grid.on('dragInit', function (item, event) {
  if (grid.getItems().indexOf(item) === indexToDisableDraggingFor) {
    return false;
  }
  return Muuri.ItemDrag.defaultStartPredicate(item, event);
})
```

**Comment by maorpolak** [comment]
Hi @awreccan 

I don't want to disable dragging for the entire item. I only want to disable dragging if the user is trying to drag the item by clicking on certain elements inside it (such as a form input).

If the user clicks on a form input that's inside the 'item-content' area, they should be able to fill out the form. If they click anywhere else inside the 'item-content' area, they should be able to drag the item.

**Comment by awreccan** [comment]
```js
grid.on('dragInit', function (item, event) {
  if ($(event.target).is('input')) {
    return false;
  }
  return Muuri.ItemDrag.defaultStartPredicate(item, event);
})
```
This should work in that case. However I have noticed that the dragging (this and other items) becomes significantly laggier if you perform such expensive DOM access operations on dragInit.

My workaround so far has been to specify drag handles by using `dragStartPredicate`'s `handle` property, but I'd love to hear better suggestions from @niklasramo, especially if `dragStartPredicate` could have a `notHandle` property that would allow developers to say `notHandle: 'input'`.

**Comment by maorpolak** [comment]
Oh, I actually overlooked the dragStarPredicate option. This solves the problem, as I can use this logic:

var grid = new Muuri(elem, {
  dragStartPredicate: function (item, event) {
     if ($(event.target).is('input')) {
         return false;
     }
     return true;
});

Thanks @awreccan

**Comment by niklasramo** [comment]
@maorpolak glad you got it sorted out, and thanks for @awreccan for helping out here! I recently made this little demo to show how to control drag start behaviour while still keeping the benefits of the default drag start logic: https://codepen.io/niklasramo/pen/LOzZPo.

This is how I would do it in this specific scenario:
```javascript
var grid = new Muuri(elem, {
  dragStartPredicate: function (item, event) {
    if ($(event.target).is('input')) {
      return false;
    }
    return Muuri.ItemDrag.defaultStartPredicate(item, event);
  }
});
```

Or, a bit more elegantly, using the handle option:

**Comment by niklasramo** [comment]
Actually that `handle: ':not(input)'`trick won't work, but would be cool if it worked. Maybe I'll upgrade it a bit ;)

**Comment by maorpolak** [comment]
@niklasramo thanks for the suggestion of returning the "defaultStartPredicate" for non-inputs. This is exactly the behavior I was looking for.
