### ISSUE TITLE
Dragged item disappears when dragged out of grid with overflow-y:scroll

### ISSUE THREAD

**Issue by maorpolak** [haltu/muuri#117]
When dragging an item between two connected muuri grids that have the "overflow-y: scroll" property, the item disappears when it leaves the source grid's area.

Each grid may contain many items and so overflow settings are necessary.

This is a known drag and drop issue, but I haven't found a workaround that works. Libraries like jQuery's Draggable give the option of cloning the element / temporarily placing it outside of the "overflow: hidden" parent.

Is there a solution that works for muuri or an option that clones the dragged element?

I've had limited success by setting the dragged item's position to "fixed" on "dragInit" and then back to "absolute" on "dragEnd". However, I ran into issues of the item "jumping" away from the cursor and/or changing its size.

**Comment by niklasramo** [comment]
Have you checked out [dragContainer](https://github.com/haltu/muuri/blob/master/README.md#dragcontainer-) option?

**Comment by maorpolak** [comment]
Brilliant! That solves my problem, thanks.
