### ISSUE TITLE
Fixed item ?

### ISSUE THREAD

**Issue by kohaistyle** [haltu/muuri#118]
Hi everyone !

First, congrats on the cool work on this Masonry alternative !

So i looked in the docs but didn't find my way, simple question: is there a way to fix a item in the grid, so that others items layout around it, as in the stamp option in masonry/isotope ?

Thank you for your help about it ;)

**Comment by niklasramo** [comment]
https://github.com/haltu/muuri/issues/84

**Comment by kohaistyle** [comment]
Thanx a lot ! Missed this one ! Sorry for disturbing ;)
