### ISSUE TITLE
Duplicate or Copy Item on release?

### ISSUE THREAD

**Issue by mspanish** [haltu/muuri#121]
I don't see the in the docs, but is this something anybody has tried implementing? I have a letter board and I'd like the kids to be able to drop letters to create a word, but it would be nice if once they do that the letter would replace itself so they can choose that same letter again.

I would only want this active when dropping from the letter board to the word board - for example, if they just move letters around on either board, no duplicate should be created.

Thanks in advance if anybody has any ideas!

**Comment by niklasramo** [comment]
Here's one way to do it: https://codepen.io/niklasramo/pen/zPVBLq

**Comment by mspanish** [comment]
awesome that looks better than my hacked up solution - thanks!
