### ISSUE TITLE
Simple example not working ?

### ISSUE THREAD

**Issue by ptorrent** [haltu/muuri#126]
Hello,

Here the code : 
```
var grid 	= document.createElement('div')
grid.className = 'grid'
var item 	=document.createElement('div')
item.className = 'item'
						
document.body.appendChild(grid)
					
var muuri = new Muuri(grid, {
})
muuri.add(item,{})
```
Result  : 

![capture](https://user-images.githubusercontent.com/6083644/33948460-37593a94-e027-11e7-9e20-d8d79414d29d.PNG)

Am I doing something wrong ?

THanks for your reply

**Comment by niklasramo** [comment]
Can't say I notice the issue by looking at the code, could you put this to codepen/jsfiddle so we can tinker around with it?

**Comment by ptorrent** [comment]
Hello !

Thanks for your reply.

https://codepen.io/ptorrent/pen/QawxpX

**Comment by niklasramo** [comment]
Hahaa, so simple it hurts! We both should have read the docs more carefully 😝  Although I've written the the docs and the code myself these simple things sometimes come haunting me 👻 

As said [here](https://github.com/haltu/muuri#4-add-the-markup)...
> Grid items must always consist of at least two elements. The outer element is used for positioning the item and the inner element (first direct child) is used for animating the item's visibility (show/hide methods). You can insert any markup you wish inside the inner item element.

Here's a working demo: https://codepen.io/niklasramo/pen/RxNJxB

**Comment by ptorrent** [comment]
thanks a lot :)
