### ISSUE TITLE
Has anyone integrated muuri with AngularJS?

### ISSUE THREAD

**Issue by narenkv** [haltu/muuri#127]
Has anyone integrated muuri with AngularJS? Please share your experiences

**Comment by Tyler-Losinski** [comment]
I have and was surprised just how easy it was to integrate.  The only drawback I found is that if you have data associated with the elements you're making draggable you have to utilize some unconventional methods to access and manipulate said data.

**Comment by niklasramo** [comment]
@Tyler-Losinski glad to hear. I haven't tried Muuri with Angular yet so would be really interested to see some real world examples.

**Comment by powerhcm8** [comment]
I using Angular 5 and I also found fairly easy to integrate it I used the Kanban example, I dare to say easier than some angular libraries.

**Comment by JoxBubo** [comment]
@powerhcm8 hello, can you help me? I´m not successful with muuri and angular5.
If you have some example it will very helpful.

**Comment by mriess260** [comment]
I threw together a quick Angular 6 Muuri project if anybody is having trouble and needs a stepping board. https://github.com/mriess260/angular-muuri-kanban-demo
The implementation is based off of Niklas Rämö's kanban demo.
Best of luck!

**Comment by JoxBubo** [comment]
Thanks, great example!

**Comment by c-dante** [comment]
If you're using AnguarJS, I put together an example here: https://github.com/c-dante/ng-muuri

I'm not sold on publishing this as a directive, so I should change the repo name, but the gist is straight forward. I don't wanna do the thing most angualr directives do and try to emulate the entire muuri API though bindings, so instead I'm taking the approach of add/remove/maintain is up to you, and I'm just tieing together the DOM lifecycle (driven by angular).

**Comment by niklasramo** [comment]
Seems like this can be closed as there are integration examples posted here and not much activity in the thread anymore.
