### ISSUE TITLE
small module drag

### ISSUE THREAD

**Issue by haojieguangxin** [haltu/muuri#128]
In the first example of the official network, when there is a relatively small space, the small module is not in the small space.

**Comment by niklasramo** [comment]
Hi! Can you elaborate a little bit? Maybe a gif/screenshot demonstrating the issue.

**Comment by haojieguangxin** [comment]
sorry，my English a little poor，i will try my best。the situation like this
![image](https://user-images.githubusercontent.com/1668064/34137087-f80a3718-e4a3-11e7-8ba5-f1958164fc8e.png)

i want to move 12 behind 10，but i can‘t do this

**Comment by niklasramo** [comment]
Yep, that's a known issue. Not an easy problem to solve by any means, but hopefully wiil be handled in the near future: https://github.com/haltu/muuri/issues/26

**Comment by davestewart** [comment]
Is this related to this?

Small squares don't seem to be able to be dragged into empty spaces:

![small space bug](http://g.recordit.co/biAcXqjXVD.gif)

**Comment by niklasramo** [comment]
@davestewart At the moment items can not be dropped on empty spaces.
