### ISSUE TITLE
Resizing support?

### ISSUE THREAD

**Issue by genachka** [haltu/muuri#132]
Is it currently possible or do you plan to add support for resizing, similar to how http://gridstackjs.com/ or https://strml.github.io/react-grid-layout/examples/0-showcase.html do it? i.e. gridstack shows on hover a handle in the bottom corners but always if so configured to resize from top or from sides too. 

I'm looking to use it for a dashboard where some containers may take the full width, but if user wants to see more info (i.e. change height of a list / grid) to allow to drag the container height.

**Comment by niklasramo** [comment]
Here's some discussion about this: https://github.com/haltu/muuri/issues/88

But yeah, there is no visual ui provided by Muuri to allow resizing items nor direct method calls for resizing items, and there most likely will never be. Muuri is intended to work on a bit lower level.

And how to do resizing with Muuri at the moment? Here's my best advice from [this thread](https://github.com/haltu/muuri/issues/49):
> Actually implementing item resizing should be pretty easy with Muuri also. You only need to implement the item resizing part (use an existing library or roll your own) yourself and the just call the grid.refreshItems().layout() when you are done.

And to make it even more clearer, let's imagine we have instantiated a Muuri grid which contains an item we want to later on resize. The item's size is 100x100 px and we want to resize it 200x200 px. We have reference to the item's element as `element`. So here we go:
```javascript
// Do the resizing of the item.
element.style.width = '200px';
element.style.height = '200px';
// Refresh the changed item's cached
// dimensions and do layout
grid.refreshItems(element).layout()
```

This is just a _very_ crude example, but that's basically the logic how you resize item's with Muuri:
1. Just resize the item elements you want by any means you see fit.
2. Refresh the cached dimensions of the affected items using `grid.refreshItems()`.
3. Do layout with `grid.layout()`.

You need to build all the fancy ui toggles yourself though.

**Comment by genachka** [comment]
Thanks for the prompt response. Was hoping for a more play and play approach but with your examples, doesn't look to bad. Might give that a try.

**Comment by moonbeetle** [comment]
+1 for easier documentation on how to make transition animation work without having to digest the entire Web Animations API. Apart from that Muuri looks very solid. Thanks for making this available.

**Comment by niklasramo** [comment]
@moonbeetle yep, I think a live example would serve well in this case. Maybe I'll roll one up when I have some extra time on my hands. And you can actually do the resizing animation with just CSS transitions too if you want to, no need to involve Web Animations here if you don't feel like it. You just need create a third container element (in addition to the two containers that Muuri requires) and give that the CSS transition styles.

**Comment by niklasramo** [comment]
This issue seems resolved -> closing.

**Comment by rquast** [comment]
For anyone who comes across this problem in the future, I use MutationObserver to update the layout from within the element that's being resized. Some Aurelia code that demos this:

```
  attached() {
    this.observe();
  }

  observe() {
    this.observer = new MutationObserver(this.resizeItem);
    this.observer.observe(this.element, {childList: true, subtree: true});
  }

  resizeItem = () => {
    this.$parent.resizeItem(this.element); // runs grid.refreshItems(element).layout()
  };

  detached() {
    if (this.observer) {
      this.observer.disconnect();
   }
 }
```
