### ISSUE TITLE
How to add custom drag handle?

### ISSUE THREAD

**Issue by abhipanda** [haltu/muuri#134]
Hi,

Thanks for the great library, wanted to know if we can implement a drag handle instead of having the whole "item" ?

Thanks,
Abhi

**Comment by niklasramo** [comment]
Yep, there is an option for handle. Check out (dragStartPredicate)[https://github.com/haltu/muuri/blob/master/README.md#dragstartpredicate-]

**Comment by abhipanda** [comment]
Thanks, it works.
