### ISSUE TITLE
Tooling improvements and better build process

### ISSUE THREAD

**Issue by niklasramo** [haltu/muuri#137]
I think it's time we revise Muuri's tooling and build process. Currently Muuri is just a [single JavaScript file](https://github.com/haltu/muuri/blob/master/muuri.js) and it's pretty big. We definitely need to split it into logical modules so that it's easier for potential contributors to help out and understand what's going on and where.

I'm also thinking about adopting [Prettier](https://github.com/prettier/prettier) for code style formatting and [Rollup](https://github.com/rollup/rollup) for bundling. Let's see what we come up with.

**Comment by awreccan** [comment]
I've worked on splitting muuri.js into multiple files as part of
react-muuri :) But it's a reactified version.

**Comment by niklasramo** [comment]
This is now done in develop branch, with Rollup and Prettier.
