### ISSUE TITLE
item-content content is not selectable

### ISSUE THREAD

**Issue by bsherwoodofdaptiv** [haltu/muuri#139]
In my web page, where I have used this functionality, all content inside of 'item-content' sections is no longer selectable. I can select text anywhere else on the page or other pages on the site without issue.

Here is the actual code used to build an item.
`
'<div class="item " data-id="1">' +
'<div class="item-content"><span class="dragHandle"><img src="/content/images/EveryWhichWay_small3.png"></span>' +
'my stuff is here '+
'</div></div>';
 `

We can also see I am leveraging the dragging ability.

I have not directly implemented any form of copy protection on the page, or overlay anything on top of this content. Prior to using this functionality, the same page if fully selectable.

**Comment by niklasramo** [comment]
That's Hammer.js doing it's thing there. Here's a bit more about the subject: http://hammerjs.github.io/tips/

**Comment by bsherwoodofdaptiv** [comment]
Agreed. If I hack out the pertinent part from Hammer, functionality returns and does not impact draggability.

Case Closed!

**Comment by bsherwoodofdaptiv** [comment]
returning the Hammer.JS file back to normal, and just using the following after grid contruction AND after every drag and drop event, keeps selectability in place. ** uses Jquery 

`$('.item').css('-ms-user-select', 'auto');`

**Comment by niklasramo** [comment]
You could also set the `user-select` attribute via CSS, no need to involve JS in this ;) Just remember to make the style `!important` so it overrides the inline style.
