### ISSUE TITLE
Question - how to serialize data-ID values with Internet Explorer 11

### ISSUE THREAD

**Issue by bsherwoodofdaptiv** [haltu/muuri#140]
I am trying to serialize the DATA-ID values of my grid items into an array for storage.
This code works fine:
```
var order = []; 
order = grid.getItems().map(item => item.getElement().getAttribute('data-id'));'
```

But IE 11 doesn't like it, and when that code loads, it breaks the entire page (prevents lots of other event driven things from working). This is very much an IE 11 issue.

This code works in IE11 (using jQuery's $.map function):

```
var order = [];
order = $('.grid > .item').map(function () { return $(this).data('id'); }).get();
```

But.. the items are in the DOM in physical order, but have  translation values the change their logical position on page. The first .map implementation reads out the DATA-ID values by physical position, where the jQuery $.map is reading the DOM items in physical order.

How do I read in the items in logical order (in IE 11) after a drag and drop event has changed their visual locations?

For reference here is what my grid item looks like:
```
 var panelDisplay = '<div class="grid">';
    panelDisplay += '<div class="item " data-id="8" id="8">' +
        '<div class="item-content">' +
        '<span class="dragHandle"><img src="/content/images/EveryWhichWay_small3.png"></span>' +
        'some other stuff is here'+
        '</div>' +
        '</div>' +
        '</div>';
```

**Comment by niklasramo** [comment]
Have you tried finding out _why_ the first example does not work in IE11? At least you're using the arrow function there which is _not_ supported in IE, and there is that `'` in the end of the second line (probably a typo).

Try this:
```
var order = grid.getItems().map(function (item) {
  return item.getElement().getAttribute('data-id');
});
```

**Comment by bsherwoodofdaptiv** [comment]
Yes, the extra single quote was a typo introduced while putting it into a code block here.

This version works like a champ.

With this line:
```
order = grid.getItems().map(item => item.getElement().getAttribute('data-id'));
```

IE trips on it and generates an error. Here is the current one:
```
JavaScript critical error at line 3418, column 39 in (unknown source location)\n\nSCRIPT1002: Syntax error
```

I came to believe (through some old internet posts) that IE doesn't implement, or correctly implement the .map function. For what you have shown, IE11 sort of does, but you have to pass in an anonymous  function instead.

I am happy. I love the code, as it has allowed me to implement a cool feature in what was otherwise a stock / old school locked layout single page application.

Thank you for your patience and time.

**Comment by bsherwoodofdaptiv** [comment]
Happy with alternate way of getting the DATA-ID value in the correct order.

**Comment by Gennady-G** [comment]
Here is the answer: https://stackoverflow.com/questions/35081810/error-with-array-map-in-ie11
Do not use lambda syntax in IE
