### ISSUE TITLE
After setting dragContainer,  the dragged item's position is not adjusted when it's container is scrolled

### ISSUE THREAD

**Issue by geeseteam** [haltu/muuri#157]
Dragged item disappears when dragged out of grid with overflow-y:scroll, So I Set the  **dragContainer**, It works well . But the dragged item's position is not adjusted when it's container is scrolled

**Comment by niklasramo** [comment]
Can you provide a reduced test case? If this is happening it's indeed a bug, the dragged item's position _should_ be updated on any parent element scrolling. You can see it working in Muuri's kanban demo here: https://haltu.github.io/muuri/.

**Comment by geeseteam** [comment]
A little change to kanban demo, [https://codepen.io/geeseteam/pen/EEbWyP](url) 
`.board-column-content {
  position: relative;
  **# max-height: 300px;
  overflow-y: auto**;
  border: 10px solid transparent;
  min-height: 95px;
}`

**Comment by niklasramo** [comment]
Hmmm, I'm noticing that when you scroll the item container and start a drag the initial position of the dragged item is wrong. But it gets corrected on first scroll event. Is this what you meant? Anyway, yep that is a bug, will fix asap.

**Comment by geeseteam** [comment]
Thank you very much!  It's what I meant.

There is another suggestion:  
When I drag the item to the top or bottom, the item container can scroll automatically if it has a scrollbar.
Too much to ask,  but very expect for it.

**Comment by niklasramo** [comment]
Yep, that's coming to muuri soon_ish_, see https://github.com/haltu/muuri/issues/9

**Comment by niklasramo** [comment]
Alrighty, this wasn't a bug after all 😛The base assumption for the calculation logic is that the grid container element does _not_ have `overflow: scroll;` or `overflow: auto;` values. You have to use a wrapper element where you set the overflow. Here's a modified example of the kanban demo that proves the point: https://codepen.io/niklasramo/pen/BrYaOp

I totally forgot this and apparently never documented this anywhere. This info is now updated to the readme: https://github.com/haltu/muuri#5-add-the-styles.

As I was reviewing the code I now remember that there are pretty valid arguments for this logic. The offset calculation logic becomes much more fragile if we try to account for the container `scrollTop`and `scrollLeft` values. It sounds simple, but it's really not.

**Comment by geeseteam** [comment]
Great, I'm clear. It's works perfectly after use a content wrapper! The updated content will help more people.

I realise your position about the calculation logic,  It's hard to even try to the hole project.
Cool!!  So thank you for your comments.
