### ISSUE TITLE
Connected grid and kanban

### ISSUE THREAD

**Issue by Altyos** [haltu/muuri#158]
Hello,

Is it possible to connect one grid to kanban for drag'n'drop ? I would like to do a delete area for items.

Thanks.

**Comment by niklasramo** [comment]
Yep, it's possbile. You can do pretty much any kind of configuration with [dragSort](https://github.com/haltu/muuri#dragsort-) option.

For example if you look at the basic [kanban example](https://codepen.io/niklasramo/pen/ppeMbK), you can just create another grid there (for deleting items) and configure the item grids to allow dragging inside that grid.

```javascript
// Create the thrash can grid.
var thrashGrid = new Muuri('.thrash-grid', {
  dragSort: true
}).on('dragEnd', function (data) {
  // You can do the item removal logic inside dragEnd event for example,
  // or inside dragReleaseEnd. Depends how you like to handle the interaction.
  thrashGrid.remove(data.item);
});

// ...and then on line 16
return columnGrids.concat(thrashGrid);
```

**Comment by Altyos** [comment]
Great, thank you !
