### ISSUE TITLE
First item fixed

### ISSUE THREAD

**Issue by andres314** [haltu/muuri#159]
I have a layout where the first item must be fixed, its a kind of placeholder. As it doesn't have the handle element, you can't drag it, but you still could position another element before it.

**Comment by niklasramo** [comment]
Do you mean you want to disable dragging for the item? Or is it fixed some other way too?

**Comment by andres314** [comment]
I need the first item blocked, it shouldn't be draggable and you shouldn't be able to drag an item before it.

**Comment by niklasramo** [comment]
Here you go: https://codepen.io/niklasramo/pen/EEdmJr

**Comment by kkak10** [comment]
@niklasramo 

https://codepen.io/niklasramo/pen/EEdmJr

this example not working on v0.6.2.

**Comment by niklasramo** [comment]
@kkak10 Bug fixed and released with v0.6.3 version.

**Comment by kkak10** [comment]
@niklasramo 

Oh!! Thank you!
so fast!!
