### ISSUE TITLE
Recover grid after destroy - Question

### ISSUE THREAD

**Issue by pedrovieira-zz** [haltu/muuri#161]
Hello, 

I'm using a validation when dragging to know if i can drop or not in that grid. 

The way i'm using this is with .destroy() method, because i don't know a better way to do this. The problem is that i need to recover the destroyed item to use after that action.

Is there a way to do it? or a simple way to do this? 

Best regards, 
Pedro Vieira

**Comment by niklasramo** [comment]
Hmm... sounds like you could also use [gridSort](https://github.com/haltu/muuri#dragsort-) option for that. You can define inside that function which grids a specific grid can be dropped in. Recovering a destroyed item/grid is not something I would attempt, at least Muuri has not been designed to support that kind of stuff.

**Comment by niklasramo** [comment]
Seems resolved -> closing
