### ISSUE TITLE
Double click event on item?

### ISSUE THREAD

**Issue by JustinYC** [haltu/muuri#162]
By any chance muuri comes with double click event on item?

Usage e.g.) User could double click on the item to bring up bootstrap modal / expand the item for more information

**Comment by niklasramo** [comment]
Have you tried just using `el.addEventListener('dblclick', fn)`? Here's working example: https://codepen.io/niklasramo/pen/rdXZaL

**Comment by justinwong85** [comment]
Great! that works out well 👍 

Was initially trying to lookout for something similar to .on('doubleclick') or something in api :)

**Comment by justinwong85** [comment]
Great! that works out well 👍 

Was initially trying to lookout for something similar to .on('doubleclick') or something in api :)

**Comment by JustinYC** [comment]
Great! that works out well 👍 

Was initially trying to lookout for something similar to .on('doubleclick') or something in api :)

**Comment by sittipat** [comment]
How to add onclick event in muuri?

`.on('click', function () {
            muuri.refreshItems();
        });`

Thank you
