### ISSUE TITLE
Typescript?

### ISSUE THREAD

**Issue by milewski** [haltu/muuri#164]
is there any plan to bundle a `.d.ts` along for this library? has anyone thought on this?

**Comment by niklasramo** [comment]
Nope, no plans for that. Open for discussion about it though 🙂

**Comment by milewski** [comment]
ok cool i will work on it on this weekend 👍

**Comment by milewski** [comment]
@niklasramo actually.. would accept a PR converting the whole source code to typescript instead of plain js?

**Comment by milewski** [comment]
well you plan to push a bunch of changes soon which would require also update the definition files again. 
writing the definition file is almost the same work as of rewriting the whole library in typescript it self (if not harder because it's kind of blind work).. so i think it is better wait for these changes land first and once the source is re-written in typescript the definitions (.d.ts) is generated automatically :)

just a note rewriting this library in TS is not much work really.. i would estimate ~3 hours to get it done.. it has almost 6k lines but most of it are comments and documentation...

**Comment by niklasramo** [comment]
Yep, there is indeed the extra work required to keep the type definitions up to date, which is something I'd like to skip at the moment. But yep, let's keep this issue open and come back to it when the time is ripe.

**Comment by Mischa1610** [comment]
I would also really appreciate typings a lot 👍

**Comment by SandHilt** [comment]
Hey @milewski, i'd like see progress and help if i can.

**Comment by sploders101** [comment]
If anyone has any updates on this, that would be awesome!

In the meantime though, I gave in and wrote my own typings. They may have some issues, and I'm not sure I'm up for *keeping* them updated (though its not out of the question), but they work with the current version (0.8.0). They also have JSDoc comments copied from the source code for intellisense descriptions, and were only made against the documentation in the readme, but they work in most cases.

https://gist.github.com/sploders101/84f88e0711ad573c3cc538ce112a98c8

**Comment by niklasramo** [comment]
Hi all, I've decided to rewrite Muuri with TypeScript, but not sure yet _when_ I have time to pull it off. I recently rewrote another pet project of mine (a fork of Cannon.js) with TypeScript and I really enjoyed it.

**Comment by aplisich** [comment]
Since a full rewrite will probably take a while, have you considered adding sploders101's declaration file to the repo? I would really appreciate it. It would benefit people using Muuri with plain JS too, since VSCode will still display the type hints even if you're not using TS.

**Comment by Paol-imi** [comment]
I rewrote the new version of [Muuri-react](https://github.com/Paol-imi/muuri-react/tree/dev) in typescript. Many of the declaration files that have been created can be largely reused for Muuri.

- Muuri options [here](https://github.com/Paol-imi/muuri-react/blob/dev/dist/types/components/muuriComponent.d.ts#L4)
- Partial events and Muuri instance [here](https://github.com/Paol-imi/muuri-react/blob/dev/dist/types/utils/decorators/decorateMuuri.d.ts#L4)

**Comment by niklasramo** [comment]
I took what @sploders101 had done and extended on it a bit to get all of the public API typed for the next version of Muuri -> https://github.com/haltu/muuri/blob/dev/src/index.d.ts. Thanks again for the ground work @sploders101 , let me know if you want me to add you to this list: https://github.com/haltu/muuri/blob/master/AUTHORS.txt

I do not yet have any timeline _when_ the 0.9.0 version is ready to be released, but it's slowly getting there. Some tweaking still left to be done and quite a lot of tests still to be added...
