### ISSUE TITLE
[BUG] the problem of placing blocks with a given % width

### ISSUE THREAD

**Issue by nikitamarcius** [haltu/muuri#165]
![22](https://user-images.githubusercontent.com/10992863/39442375-9d1e51d0-4cb9-11e8-9fbf-1c21c52180c7.PNG)
seems same problem: https://github.com/haltu/muuri/issues/67

Blocks with percentage width are not correctly placed at init or when changing the width of parent. Not always 2 blocks of 50% will fill the entire 100% width of grid

Version: 0.5.4
Example: https://codepen.io/nikitamarcius/pen/RypKNb

**Comment by nikitamarcius** [comment]
@niklasramo great, thanks for the quick response.

**Comment by niklasramo** [comment]
This seems resolved -> closing.
