### ISSUE TITLE
Relayout

### ISSUE THREAD

**Issue by sunxt1989** [haltu/muuri#167]
I have some difficulties in using Muuri.
How to change the size of a project? All projects need to be rearranged.
Like the layout property in Masonry

**Comment by niklasramo** [comment]
Hmmm... by project do you mean grid? If so you can just directly set the grid element's width/height and call grid.layout() after it.

**Comment by sunxt1989** [comment]
Thank you for your prompt reply！
Now I've solved this problem.
The code I wrote is this：

$itemReduce.on('click',function(){
        $(this).parents('.item').css({
            'width': '50px',
            'height': '50px'
        })
        grid.refreshItems();
        grid.layout();
    })
But in Masonry, you only need to call grid.layout ().

**Comment by niklasramo** [comment]
seems resolved -> closing

**Comment by Techn1x** [comment]
Might be useful if this is include in the Readme, that you need to call both `grid.refreshItems()` and `grid.layout()`
