### ISSUE TITLE
Dynamically add an element to the grid from array

### ISSUE THREAD

**Issue by Sashkan** [haltu/muuri#169]
I have an array of data, and a form

Every time I fill the fom, a new element is added to the array

This array is used to display a muuri grid (Each element of the array is a muuri item)

Unfortunately, when I use the form, the new item does not behave as the rest of the items (it is just added in the container div, without any style or transformation)

is there a way to refresh the grid every time a new item is added ? So far, it is added in the DOM, but it is not affected by the Muuri gridding. Here are a few images to explain : 

Before adding item : 

![image](https://user-images.githubusercontent.com/6276267/40490088-00e3ecac-5f6b-11e8-81a3-70121e98499c.png)

After adding item (the item is the lamb, previous first item is hidden behind)

![image](https://user-images.githubusercontent.com/6276267/40490112-134f60d8-5f6b-11e8-9250-9d356182e397.png)

I tried using grid.layout() and grid.refreshItems() after adding the item, it doesn't change anything

**Comment by Sashkan** [comment]
Yes ! Thanks a lot !

**Comment by niklasramo** [comment]
Seems resolved -> closing.

**Comment by angeldua** [comment]
@Sashkan @niklasramo  Could you please share your sample code to add items to muuri grid dynamically. have been trying to use the one available on codepen, but the new items are not appearing for me in the grid.
