### ISSUE TITLE
Prevent styling on hidden elements

### ISSUE THREAD

**Issue by Sashkan** [haltu/muuri#170]
Gridding works perfectly, although I'd like to enhance performances by adding a lazyload on my grid, so that items are only displayed when in viewport. Unfortunately, it seems like Muuri apply styles to every single elements, therefore raising an error when an element does not exist (or, in our case, is not loaded yet). 

![image](https://user-images.githubusercontent.com/6276267/40617231-07581f74-628e-11e8-9d05-7c4451fa3360.png)

Is it possible to prevent this behaviour ?

**Comment by niklasramo** [comment]
Hmmm.. I guess it's possible, but going to be a bit complex. You really have to dive deep into Muuri's core functionality to make that happen. I've also been thinking about this quite a bit and hoping that I'd have time to build a plugin for Muuri that could do exactly what you're suggesting: hiding all items with display:none that are not in viewport.

If you come up with a nice solution I bet many others here would be interested in it as well ;)

**Comment by TJKoury** [comment]
I'm new to the library, what would be the drawback of simply:

`
    for (i = 0; i < props.length; i++) {
      if (element && !!element.style) {
        element.style[props[i] === 'transform' && transform ? transform.propName : props[i]] = styles[props[i]];
      }
    }`

**Comment by TJKoury** [comment]
I'm new to the library, and interested in contributing.

For this issue, what would be the drawback in simply:

```
    for (i = 0; i < props.length; i++) {
      if (element && !!element.style) {
        element.style[props[i] === 'transform' && transform ? transform.propName : props[i]] = styles[props[i]];
      }
    }
```

**Comment by niklasramo** [comment]
@TJKoury there would be an error after even if you fixed that line. Muuri assumes throughout the code that the elements added to the grid exist in DOM.
