### ISSUE TITLE
How to set specified item undraggable?

### ISSUE THREAD

**Issue by misybing** [haltu/muuri#172]
How to set specified item undraggable?

Example:
<img src="http://wx2.sinaimg.cn/large/65db906egy1fs30a7ahwuj20cp0gumx6.jpg">
Is it possible to set item 【2017】【2018】undraggable?
While 'Item #3' still could drag to position after 【2018】and also 'Item #4' could drag to postion before 【2017】or【2018】.

This issue(https://github.com/haltu/muuri/issues/159) is similar to my question but not the same.

**Comment by misybing** [comment]
Here are an example to set item dragable or not by using boolean parameter ‘draggable’:
http://jsrun.net/XpiKp/edit
Could Muuri set up this way too?

**Comment by niklasramo** [comment]
Well, yes :) The answer is in the example mentioned in #159 : https://codepen.io/niklasramo/pen/EEdmJr. Check the `dragStartPredicate` option.

**Comment by misybing** [comment]
Thank you. I have solved this problem by code below:
``    dragStartPredicate: function (item, event) {
      // Prevent first item from being dragged. 
      if (item.getElement().id === 'no-drag') {
        return false;
      }
      // For other items use the default drag start predicate.
      return Muuri.ItemDrag.defaultStartPredicate(item, event);
    },

**Comment by niklasramo** [comment]
Seems resolved -> closing
