### ISSUE TITLE
How do I prevent a click event on drop?

### ISSUE THREAD

**Issue by AndrewMorsillo** [haltu/muuri#173]
When I am dropping my elements they always get a click event which in my app opens a dialog to edit the item. When an item is dropped I want to prevent this click event, but doing preventDefault or stopPropagation in 'dragEnd' does not seem to do it.

**Comment by niklasramo** [comment]
Yep, that's probably not the simplest thing to set up. I can't help you without a small example on this one, like a reduced test case I can tinker with.

**Comment by AndrewMorsillo** [comment]
My solution was to add a check to my dialog open click handler. Turned out to be pretty simple =)

```
 if (!this.clickElem.closest(".muuri-item-releasing")) {
     this.props.DialogState.setShowEditTaskDialog(task._id)
 } else {
    console.log("Suppressing open on drag")
 }
```

**Comment by StellaTerra** [comment]
I was able to use this solution, but on a fast enough computer/browser `muuri-item-releasing` is appended so fast that it can't tell the difference between a click and a drag. The fix is simply adding a small delay (50ms worked for me) to the `dragStartPredicate` and then it works great!
