### ISSUE TITLE
How to undo a drag-drop

### ISSUE THREAD

**Issue by lukecurtis93** [haltu/muuri#174]
Hey there,

Is there currently the ability to 'undo' a drag? Right now I have:
```
.on('dragReleaseEnd', function(){
    //confirm they want to drag the item here
});
```

But if a user presses cancel on the drag confirm, is there the ability to put the item back in the list they originally dragged it from? I'm using the Kanban example as a starting point here.

**Comment by niklasramo** [comment]
Canceling drag is not supported via the public API, but it's totally doable if you poke around the source a bit and see what happens there. You could also try to use the `.send()` method there and see what happens 🙂

**Comment by lukecurtis93** [comment]
Thanks I'll give this a go.
