### ISSUE TITLE
An event is missing after append a new element on .grid class

### ISSUE THREAD

**Issue by avdnowhere** [haltu/muuri#175]
Dear All,

I am trying to add a new element on .grid class (the .grid class is on a div).
So basically I already have some elements (div) inside the .grid class.
Then I want to add a new one by clicking on a button.
However there is an event missing from the new added element.

This is my HTML code:

```
<div class="row mh grid">

<div class="col-sm-6 itemgrid" id="div-1">
	<div class="card">
		<div class="white">
			<h3 class="title">Title 1</h3>
		</div>
		<div class="card-content">
			<canvas></canvas>
		</div>
	</div>
</div>

<div class="col-sm-6 itemgrid" id="div-2">
	<div class="card">
		<div class="white">
			<h3 class="title">Title 2</h3>
		</div>
		<div class="card-content">
			<canvas></canvas>
		</div>
	</div>
</div>

</div>
```

This is my JS code:

```
var grid;

$(document).ready(function() {

grid = new Muuri('.grid', {
dragEnabled: true
});

$('#submitBtn').click(function(e) {

e.preventDefault();
var items = grid.getItems();
var itemsLength = items.length + 1;

var newDiv = '<div class="col-sm-6 itemgrid" id="div-' + itemsLength + '">'
+ '<div class="card">'
+ '<div class="white">'
+ '<h3 class="title">New Title</h3>'
+ '</div>'
+ '<div id="testing-' + itemsLength + '" class="card-content">'
+ '</div>'
+ '</div>'
+ '</div>'

$('.grid').append(newDiv);

grid = new Muuri('.grid', {
dragEnabled: true
});

});
		
});
```

So after I clicked the #submitBtn button, it will add a div element on the .grid class, then I call again the Muuri, so the new element will be able to drag as well.

However, the new one is missing an event, you can refer to the images below:

This is from existing two div: https://imgur.com/rdf0fk4
This is from the new element div: https://imgur.com/Wl5cWuK

Based on the images above, you clearly see the new one missing one pointerdown event.

So, the new one will not trigger any events from Muuri JS, eg: dragReleaseEnd.

Any ideas why the new element missing another pointerdown event?

Thank You.

**Comment by niklasramo** [comment]
Hmmm, it is not adviseable to add items like this. You are basically creating multiple muuri instances here without cleaning up the old one. Use grid.add() method for adding items to the grid.

**Comment by avdnowhere** [comment]
Hi @niklasramo 

Ohh, I see. Could you show me how to add a new element by using grid.add() ?

Thanks.

**Comment by niklasramo** [comment]
Please read the docs about that, it should be well explained there: https://github.com/haltu/muuri#gridadd-elements-options-

**Comment by avdnowhere** [comment]
hi @niklasramo 

I have tried to use the grid.add() method, however the new element is not appended to the .grid section and I got this error: TypeError: Argument 1 of Node.appendChild is not an object.

This is my updated JS code:

```
var grid;

$(document).ready(function() {

grid = new Muuri('.grid', {
dragEnabled: true
});

$('#submitBtn').click(function(e) {

e.preventDefault();
var items = grid.getItems();
var itemsLength = items.length + 1;

var newDiv = '<div class="col-sm-6 itemgrid" id="div-' + itemsLength + '">'
+ '<div class="card">'
+ '<div class="white">'
+ '<h3 class="title">New Title</h3>'
+ '</div>'
+ '<div id="testing-' + itemsLength + '" class="card-content">'
+ '</div>'
+ '</div>'
+ '</div>'

grid.add(newDiv);

});
		
});
```
Any ideas how to solve it?

Thanks.

**Comment by niklasramo** [comment]
The `newDiv` in your example is not an element, but a string. That's why it fails. You should first convert the string to DOM node: https://davidwalsh.name/convert-html-stings-dom-nodes

**Comment by avdnowhere** [comment]
Hi @niklasramo 

Yes, you are right.
I just need to convert it into DOM and now it works.

Thanks a lot.

**Comment by niklasramo** [comment]
seems resolved -> closing

**Comment by hitodev** [comment]
Hi, I try to add item via AJAX using a callback function. Items are added but not positioned :
`function callbackSearch(data){
	console.log("callbackSearch");
	 //var data = data;
	 console.log(data);
	 
	 // ERROR : tems added but not positioned
	 
	 let doc = new DOMParser().parseFromString(data, 'text/html');
	 
	 // WORKS : added & positioned
	 
	 //let doc = new DOMParser().parseFromString('<div class="item"><div class="item-content"><div class="my-custom-content">ADDEED 1 ! </div></div> </div><div class="item"><div class="item-content"><div class="my-custom-content">ADDEED 2 ! </div></div> </div>', 'text/html');
	 //let doc = new DOMParser().parseFromString('<div data-idx="" data-chunk="tpl.rsextra.single_1" class="card col-sm-3 col-md-3 col-lg-2 m-2 border-0 item" ><img src=" https://kaihatsu.jpdn.net/assets/img/pthumb-cache/pthumb-image-cache/filestore/1/9/5_6226292656ce744/195_5d1994a08257e29.7234d54d.jpg" class="card-img-top" alt="Image ID: 195"> <div class="card-body"><p class="card-text small text-center">Le pont de Bercy</p></div></div><div data-idx="" data-chunk="tpl.rsextra.single_1" class="card col-sm-3 col-md-3 col-lg-2 m-2 border-0 item" ><img src=" https://kaihatsu.jpdn.net/assets/img/pthumb-cache/pthumb-image-cache/filestore/1/9/4_a7f33a6bf37c75d/194_4a03eb68aaf9cba.7234d54d.jpg" class="card-img-top" alt="Image ID: 194"><div class="card-body"><p class="card-text small text-center">Inondations Quai d\'Austerlitz</p> </div></div>', 'text/html');
	 let getNodes  = doc.body.childNodes;
	 grid.add(getNodes);

}`
Any idea ?
