### ISSUE TITLE
Remove Item by data-id

### ISSUE THREAD

**Issue by lithiumhax** [haltu/muuri#177]
Can someone give me an example on how to remove an Item from a Grid using the Item's data-id?
Is this possible?  Thanks!!

**Comment by niklasramo** [comment]
You can use grid.remove() and provide a muuri item instance or a dom element as the first argument. Getting the item or dom element that has the data-id is trivial, e.g. use document.querySelecror().

**Comment by lithiumhax** [comment]
Thanks @niklasramo, it was an error on my end.  Everything is working great.
