### ISSUE TITLE
 Can Murri be used in the VUE project?

### ISSUE THREAD

**Issue by sunxt1989** [haltu/muuri#179]
If you can, if you install it and reference it?

**Comment by niklasramo** [comment]
Haven't tried Vue yet, so maybe some others can answer this one. There's a couple of Vue wrappers for muuri already available, but haven't tried them either yet so don't know how ready they are. 

https://github.com/jocodev1/vue-muuri

**Comment by sunxt1989** [comment]
Thank you. I tried it. I can still use it now. I'm still developing it.

**Comment by niklasramo** [comment]
Seems resolved -> closing
