### ISSUE TITLE
Kanban with scrolling containers  / One row Horizontal scrolling

### ISSUE THREAD

**Issue by pars11** [haltu/muuri#180]
Hi I want these cards in a row as a horizontal scroll.

https://codepen.io/anon/pen/RJvPvM

but unfortunately I failed.

https://codepen.io/anon/pen/PaxLov

there

  layout: {
    horizontal: true
  }

the operation is not fully functional at the top.

**Comment by niklasramo** [comment]
Yep, it's a bit tricky but in the end just a matter of setting up the CSS correctly. Here's a working example: https://codepen.io/niklasramo/pen/RJmBVV.

The takeaway here is to understand that in horizontal layout mode Muuri adjusts the container's _width_ automatically based on the layout, not the height. So you have to manually set the height of the container as it is used in the drag sorting algorithm.

**Comment by pars11** [comment]
I think I understand. Thank you so much.
