### ISSUE TITLE
Add grid back to added grid / Question

### ISSUE THREAD

**Issue by pars11** [haltu/muuri#186]
I would like to add new columns and new items into this [example](https://codepen.io/niklasramo/pen/RJmBVV).

I add grid with

`var log = boardGrid.add([div]);`

but then I can't add new grid with

`log.add([div2]); `

or 

`log[0].add([div2]); `

I get 

> Uncaught TypeError: log.add is not a function

error.
Thank you very much for your help already.

**Comment by niklasramo** [comment]
The .add() method returns an array of the new items added to the grid. So you can't do log.add() or log[0].add(). You probably should be doing boardGrid.add().

**Comment by pars11** [comment]
I can add new column with boardGrid.add () but how can I add the items in that column.

**Comment by niklasramo** [comment]
Call the `.add()` method on the columns Muuri instance.

**Comment by pars11** [comment]
I found a solution, thanks.
