### ISSUE TITLE
Disabling/enabling drag & drop on the fly

### ISSUE THREAD

**Issue by cristiancporto** [haltu/muuri#189]
I was planning to make a dashboard layout with Muuri and, after user edits, I would want to disable drag & drop. I tried doing so by creating a `new Muuri({ enableDrag: false })` and it didn't work, even after calling `destroy()` or `remove()` on the object created. Any way of doing it? A method or a property for doing this would be great.

**Comment by niklasramo** [comment]
You can do that with [dragStartPredicate](https://github.com/haltu/muuri#dragstartpredicate-). Check out the examples.
