### ISSUE TITLE
Muuri in AngularJS, how to add/remove item?

### ISSUE THREAD

**Issue by klusinyan** [haltu/muuri#193]
Hi, first of all thank you very much for this nice library.

I'm trying to implement Muuri boards with AngularJS and I could populate the items in boards via ng-repeat. So, all works fine until I try to add new item in angular's array. My code looks like this:

```
<div class="board-column 1day">
  <div class="board-column-header font-bold-20-dark">1{{day}}</div>
  <div class="board-column-content" id="1">
    <div ng-repeat="event in events | filter: { day: '1' } | orderBy : 'order'" class="board-item" id="{{event.id}}">
      <div class="board-item-content">
          my content
      </div>
    </div>
  </div>
</div>

```

When I'm trying to modify my **events** array by adding or remove elements I can not refresh the boards, I tried almost all methods that Muuri's grid provide. 
My question, is there any method that I can call to reload completely layout with current **events** elements? 
Thank you very much!

**Comment by niklasramo** [comment]
Haven't tried Muuri with angular personally, _but_ you always have to explicitly use the [`grid.add()`](https://github.com/haltu/muuri#gridadd-elements-options-) method when adding items in the grid. No way around that. It's also good to bear in mind that Muuri will append the added element in the grid container element _unless_ the added element is already a child of the container.

Also good to note that the same applies for removing items, you have to do it explicitly with [`grid.remove()`](https://github.com/haltu/muuri#gridremove-items-options-) method.

**Comment by klusinyan** [comment]
Hi Niklas, thank you indeed for you quick reply!

After a lot of coding : ) yes, the only solution was to use **`grid.add()`**  and **`grid.remove()`**. So, by generating dynamic DOM **`board-item`** I placed it inside of **`board-column-content`**. 

Just another question, if you have any suggestion : )
I'm trying to add also **`board-column`** dynamically. So in particular, what I need to do is to add **n** boards by code, similar to **`board-item`**. Do you think it's possibile, and at what point I need to generate DOM board elements?

**Thanks again!**

**Comment by niklasramo** [comment]
Yoi can add the columns to the board the same way you add items to a column. Just use the gris.add() method.

**Comment by klusinyan** [comment]
**Adding boards dynamically:**
I tried to add columns after init() with **`boardGrid.add()`**, as you suggested me, then proceed by adding items into boards: no success. I tried also to generate first statically 3 columns, populate items and then add a single column later. The 4th column is visibile (always using **`boardGrid.add()`** method), but can not drag items into it. 

**Setting vertical distance between boards:**
How can I set the vertical distance between columns? I could not find any reference in doc.

Thank you.

**Comment by klusinyan** [comment]
It's not enough to call **`grid.add()`** to add a new **`board-column`**. The new board is not active, however the log shows that it's active. It seems that the **`board-column`** and **`board-item`** have different behaviour on **`add()`**.

**Comment by rquast** [comment]
I'm trying to figure this out with Aurelia at the moment too. Need to dynamically add and remove items. I tried grid.add(element) but it gives me an error:

```
aurelia-logging-console.js:47 ERROR [window_onerror] browser:::window_onerror TypeError: Cannot read property 'style' of undefined
    at setStyles (muuri.js:4474)
    at Object.start (muuri.js:5149)
    at new Item (muuri.js:1457)
    at Grid.add (muuri.js:796)
```

**Comment by rquast** [comment]
My bad.. I got it working with add().

```
    <div class="grid" id="muuri-grid">
      <div class="item" repeat.for="item of relatedTopics">
        <div class="item-content">
          <topic-tile index.bind="$index" class="item-content"></topic-tile>
        </div>
      </div>
    </div>
```
The custom element topic-tile calls grid.add() when it attaches to the DOM. I was sending it the wrong element. Sending it topic-tile's parentNode's parentNode and it works fine.

**Comment by klusinyan** [comment]
Hi, I tried to follow your example by adding **`id="muuri board"`** nothing happened. The new board remains inactive and it's possibile to drag the elements into it again.

**Comment by klusinyan** [comment]
Have anyone tried to add board dynamically?

I have a following board system:

```
boardGrid = new Muuri('.board', {
  items: generateBoards(3),
  layoutDuration: 400,
  layoutEasing: 'ease',
  dragEnabled: true,
  dragSortInterval: 0,
  dragStartPredicate: {
    handle: '.board-column-header'
  },
  dragReleaseDuration: 400,
  dragReleaseEasing: 'ease'
});

function generateBoards(count) {
  var boards = [];
  for (var i = 0; i < count; i++) {
    var board = generateBoard(i+1);
    boards.push(board);
  }
  return boards;
}

function generateBoard(index) {
  var itemElem = document.createElement('div');
  var itemTemplate = '' +
    '<div class="board-column">' +
      '<div class="board-column-header">' + index + '{{day}}</div>' +
      '<div class="board-column-content" id="' + index + '"></div>' +
    '</div>';
  itemElem.innerHTML = itemTemplate;
  return itemElem.firstChild;
}
```
then I want to add the 4th board to main board:

```
function addBoard() {
  var board = generateBoard(4);
  boardGrid.add([board]);
}
```

It adds an **inactive** board disabled for dragging. What is wrong?
I tried to understand the issue and looked up to **ids** for each board, so: 
the main board (root board that contains all columns) has `id:1`, every nested board has `id=2, 3, 4. `The last board comes with `id=9`, maybe this is problem? if yes, is it possibile to assign the specific id to specific board?

Thank you in advance for reply.

**Comment by niklasramo** [comment]
@klusinyan could you maybe put up an interactive demo (reduced test case) on codepen for example?

**Comment by klusinyan** [comment]
Ok. Thanks.

**Comment by klusinyan** [comment]
Just one thing, I saw that the current versione I'm currently using is:

`<script src="https://cdnjs.cloudflare.com/ajax/libs/muuri/0.5.4/muuri.min.js"></script>`

maybe the problem is there, what do you think? 
I'll update to last versione 0.6.2 first and then put the reduced code on codepen.

**Comment by klusinyan** [comment]
Hi, I created the example in codepen and this is link: https://codepen.io/klusinyan/pen/rrzQma
1. First "Add item" into board (adds item into 1st board)
2. Then "Add column"
3. Try to drag into the item into new board

Thanks.

**Comment by niklasramo** [comment]
Ah yes, you are not instantiating muuri on column when you add it to the board. That's why it won't work as you would want to. You need do the instantiate muuri to the item container in the added column same way you do on line 26 there.

**Comment by klusinyan** [comment]
Hi, thank you for your reply. I tried to do it following your suggestion to instantiate again muuri:

```
function reload() {

var docElem = document.documentElement;
    var kanban = document.querySelector('.kanban-board');
    var board = kanban.querySelector('.board');
    var itemContainers = Array.prototype.slice.call(kanban.querySelectorAll('.board-column-content'));
    var dragCounter = 0;

    itemContainers.forEach(function (container) {

      var muuri = new Muuri(container, {
        items: '.board-item',
        layoutDuration: 400,
        layoutEasing: 'ease',
        dragEnabled: true,
        dragSort: function () {
          return columnGrids;
        },
        dragStartPredicate: {
          distance: 10,
          delay: 1,
        },
        dragSortInterval: 0,
        dragContainer: document.body,
        dragReleaseDuration: 400,
        dragReleaseEasing: 'ease',
        dragSortPredicate: {
          action: 'move'
        },
      })
      .on('dragStart', function (item) {
        ++dragCounter;
        docElem.classList.add('dragging');
        item.getElement().style.width = item.getWidth() + 'px';
        item.getElement().style.height = item.getHeight() + 'px';
      })
      .on('dragEnd', function (item) {
        if (--dragCounter < 1) {
          docElem.classList.remove('dragging');
        }
      })
      .on('dragReleaseEnd', function (item) {
        item.getElement().style.width = '';
        item.getElement().style.height = '';
        columnGrids.forEach(function (muuri) {
          muuri.refreshItems();
        });
      })
      .on('layoutStart', function () {
        boardGrid.refreshItems().layout();
      })
      .on('layoutEnd', function (items) {
        refreshAllEvents(container, items);
      });
      columnGrids.push(muuri);
    });
}

function addColumn() {
  var board = generateBoard(4);
  boardGrid.add([board]);
}
```

Great, it works. I wake s almost "sure" that add() method, in case of board, was doing already the instantiation, but I was wrong. 

In case I want to remove the last board and add it again. All works until dragging the element inside it, I saw that it remains the empty space on that board, some strange layout behaviour. I tried to apply the same solution above, instantiate  Muuri again but it doesn't work. To see this behaviour there is a new method called removeBoard() on codepen.

Thanks.

**Comment by klusinyan** [comment]
It happens also when your first add the item then the board. Otherwise, when board already added it's ok. So please try the following sequence:
1. add item first
2. add new board
3. drag item into new board

**Comment by niklasramo** [comment]
@klusinyan the reload function instantiates Muuri again to all item containers. That causes some serious problems (unwanted behaviour, massive memory leak, etc.). If you wanter to build that kind of reload function you need to destroy the old Muuri instance before you apply the new.

But... the way to go here is not doing that kind of massive operation every time you add/remove a new column. You only need to instantiate Muuri to the new column's item container (`'.board-column-content'`). And when you remove a column you need to destroy the Muuri instance.

**Comment by klusinyan** [comment]
If remove causes such a memory leaks and the problem to add board after adding an item causes layout problems, maybe I should destroy and create the main board instance each time? 
So if I do in this way is there a callback function when Muuri instance is created?

**Comment by niklasramo** [comment]
No, you should not do that. 

> You only need to instantiate Muuri to the new column's item container ('.board-column-content'). And when you remove a column you need to destroy the Muuri instance.

**Comment by niklasramo** [comment]
Everytime you remove an element from the DOM that has a Muuri instance linked to it, you need to call destroy method on that Muuri instance before removing the element from DOM.

**Comment by klusinyan** [comment]
Sorry, maybe I'm wrong but if I destroy the linked element before remove it, how I can remove it later if it has not a reference anymore.
example:
```
    $scope.removeBoard = function() {
      if (boardGrid) {
        var board = boardGrid.getItems()[boardGrid.getItems().length-1]; // last element
        board.destroy(); // 
        boardGrid.remove([board]); // can not remove destroyed element
        console.log("remove column done");
      }
    }  
```

**Comment by niklasramo** [comment]
I'll try to add a demo of dynamically adding columns to e.g. kanban board when I have some extra time.

**Comment by klusinyan** [comment]
Ok, thank you again to share this great library with us.

**Comment by Fornasier7** [comment]
Has anyone developed a solution for this? Thanks in advance

**Comment by klusinyan** [comment]
Hi, yes I developed for AngularJs. What do you need in particular?

**Comment by klusinyan** [comment]
If you need to add/remove boards, you can not do it. The thing that you can do to destroy and create boards again. If you need to add/remove items, that you can do it.

**Comment by klusinyan** [comment]
This is a my code, in my example I have 3 boards.

1. initBoard element once:

```
    function initBoard() {
      boardGrid = new Muuri('.board', {
        items: generateBoards(3),
        layoutDuration: 400,
        layoutEasing: 'ease',
        dragEnabled: true,
        dragSortInterval: 0,
        dragStartPredicate: {
          handle: '.board-column-header'
        },
        dragReleaseDuration: 400,
        dragReleaseEasing: 'ease'
      });
      var docElem = document.documentElement;
      var kanban = document.querySelector('.kanban-board');
      var board = kanban.querySelector('.board');
      var itemContainers = Array.prototype.slice.call(kanban.querySelectorAll('.board-column-content'));
      var dragCounter = 0;
      itemContainers.forEach(function (container) {
        var muuri = new Muuri(container, {
          items: '.board-item',
          layoutDuration: 400,
          layoutEasing: 'ease',
          dragEnabled: true,
          dragSort: function () {
            return columnGrids;
          },
          dragStartPredicate: {
              distance: 10,
              delay: 1,
          },
          dragSortInterval: 0,
          dragContainer: document.querySelector('.timeline-board'),
          dragReleaseDuration: 400,
          dragReleaseEasing: 'ease',
          dragSortPredicate: {
            action: 'move'
          },
        })
        .on('dragStart', function (item) {
          ++dragCounter;
          docElem.classList.add('dragging');
          item.getElement().style.width = item.getWidth() + 'px';
          item.getElement().style.height = item.getHeight() + 'px';
        })
        .on('dragEnd', function (item) {
          if (--dragCounter < 1) {
            docElem.classList.remove('dragging');
          }
        })
        .on('dragReleaseEnd', function (item) {
          item.getElement().style.width = '';
          item.getElement().style.height = '';
          columnGrids.forEach(function (muuri) {
            muuri.refreshItems();
          });
        })
        .on('layoutStart', function () {
          boardGrid.refreshItems().layout();
        })
        .on('layoutEnd', function (items) {
          // console.log(items);
          refreshAllEvents(container, items);
        });
        columnGrids.push(muuri);
      });
    }
```

2. Each time you need to create an item first create a DOM element, something like this:

```
    function generateBoardItem(item) {
      var itemElem = document.createElement('div');
      var itemTemplate = '' +
        '<div class="board-item" id="' + item.id + '">' +
          '<div class="board-item-content" ng-style="{opacity : (' + item.deleted + ' ? 1 : 1)}">' +
            '<button type="button" id="' + item.id + '" class="close font-bold-20-dark" style="padding-top:10px" aria-label="Close" ng-disabled="isTimelineUpdating" ng-click="removeBoardItem($event)">' +
              '<span aria-hidden="true">&times; </span>' +
            '</button>' +
            '<div class="media">' +
              '<div class="media-left media-middle">' +
                '<img src="' + item.image + '" id="' + item.id + '" class="media-object board-image">' +
              '</div>' +
              '<div class="media-body">' +
                '<div class="row" style="height:10px;"></div>' +
                '<div class="media-heading">' +
                  '<span ng-if="' + !item.deleted + '" class="' + item.badgeIconClass + ' board-badge" style="color:' + item.badgeIconColor + ';"></span><span ng-if="' + item.deleted + '" class="fa fa-exclamation-triangle board-badge" style="color:red;"></span>  <span ng-if="' + item.deleted + '" class="board-removed" ng-bind="place_removed"></span>' +
                '</div>' +
                '<div class="media-heading" style="margin-top:-5px">' +
                  '<p class="board-title">' + item.name + '</p>' +
                  '<p class="board-subtitle" id="event-cat-' + item.id + '" style="margin-top:-10px">' + localizedKey(item.category) + '</p>' +
                '</div>' +
              '</div>' +
            '</div>' +
          '</div>' +
        '</div>';

      // add template to parent 'div'
      itemElem.innerHTML = itemTemplate;

      // compile html DOM element
      $compile(itemElem)($scope);
      // console.log("compiled[0]");
      return itemElem.firstChild;
    }
```

3. Then add generated item to board:

```
        // NOTE:: columnGrids
        columnGrids[indexOfBoard].add([item], {index: event.order});
```

**Comment by Fornasier7** [comment]
Hi, thanks for the answer!
I am trying to add new items to a new column without having to reload the component or delete columns, but I haven't succeeded yet. I tried to instantiate a new column's container item as @niklasramo suggested, but didnt quite figured it out how to do it properly

**Comment by klusinyan** [comment]
For column do you mean a board?
Do you create a DOM object properly?

**Comment by Fornasier7** [comment]
I mean a `board-column` element. I'm trying to add multiple board columns dinamically and then add some board itens for each column. My code is based on your example https://codepen.io/klusinyan/pen/rrzQma

**Comment by klusinyan** [comment]
I had same problem to add or remove boards dynamically. At the end I did by destroying and creating each time. Note that this was also suggested from @niklasramo.

**Comment by niklasramo** [comment]
@klusinyan @Fornasier7 This is what I suggested: https://codepen.io/niklasramo/pen/KKKYKWG, hope it helps 😉 No need to destroy and create each time.

**Comment by Fornasier7** [comment]
Thanks so much @niklasramo @klusinyan , problem solved!

**Comment by klusinyan** [comment]
You’re welcome!
Thanks to @niklasramo for this great library.
