### ISSUE TITLE
How to break attachment with drag

### ISSUE THREAD

**Issue by dreed4** [haltu/muuri#195]
Hopefully I can make sense of what I'm trying to do. I have several items that belong to a Muuri grid and in the same page I have another non-Muuri custom element (essentially a grid, but not one that I can use Muuri for). I need to drag an item out of the Muuri grid, perform some operations on it, and then allow it to drop into my own custom element. Is there some way to determine when I have dragged an element a certain distance away from the Muuri grid, and then remove the item from the grid while still having some custom element remain under my cursor?

**Comment by niklasramo** [comment]
Hmmm.. yes, there are probably plenty of ways to do that, but you have Muuri itself doesn't have any helpful methods for your case. You can probably tap into the Hammer drag events and determine the distance from there and then just cache the position of the element when dropping it, remove it from the muuri instance and re-apply the cached position. Something like that should get you started.
