### ISSUE TITLE
Adding elements to grid with Vue.js

### ISSUE THREAD

**Issue by RBrNx** [haltu/muuri#197]
I am currently using Murri in a Vue project, along with [vue-murri](https://github.com/jocodev1/vue-muuri).

I have my Grid set up, along with a number of Grid-Items that get created based on an Array in my Vue component. 

```
        <muuri-grid v-if="gridLayout.length > 0" id="grid" :options="muuriOptions" @dragReleaseEnd="storeGridPositions" @gridCreated="storeGridPositions">
			<muuri-grid-item v-for="gridItem in gridLayout" 
				:itemsize="gridItem.size"
				:itemid="gridItem.id" 
				:key="gridItem.id"
				:ref="gridItem.id">
				<WidgetPlaceholder 
					:widgetinfo="gridItem" 
					:dashboarddata="DashboardData"
					:grideditable="isGridEditable"
				></WidgetPlaceholder>
			</muuri-grid-item>
        </muuri-grid>
```

This all works great so far! My issue is when I try to add an item to my grid. Adding an extra element to my `gridLayout` will create a new GridItem as desired, however this simply floats on top of the Muuri Grid as it has not been added via the `.add()` function. 

I can fake adding a new element to the gridLayout array by using [vue-custom-element](https://github.com/karol-f/vue-custom-element) to turn my Vue Component into a HTML Custom Element, and then adding it to the Grid

```
function addCustomElement(){
	var el = document.createElement("custom-grid-item");
	el.itemsize = "Single";
	el.setAttribute("data-id", 99);

	var widget = document.createElement('w-placeholder');
	
	widget.widgetinfo = {             
		id: 99,
		size: "Single",
		title: "Blank",
		widgetType: "Blank" 
	}

	el.appendChild(widget);

	var muuriGrid = this.$children.find(child => {  return child.id == "grid"});
	muuriGrid.grid.add(el);
}
```

This technically works (as in Muuri now has the element in its `Items` array) however the GridItem does not seem to obey my Muuri rules (fillGaps: true), nor can it be dragged around.

![image](https://user-images.githubusercontent.com/1332314/43329768-428e3f56-91b9-11e8-82ca-efffd18a9e6f.png)

(The new element is the Blank one in the bottom left)

Is there any solution for this?

**Comment by niklasramo** [comment]
@RBrNx I'd suggest creating reduced test case of this and setting it up live on codepen (or similar service) so that we can tinker easily with the code and see what's really going on.
