### ISSUE TITLE
Best options for making grid items selectable?

### ISSUE THREAD

**Issue by Bandes** [haltu/muuri#200]
I am planning to use Muuri for a photo grid, and I need a way to let the users select items (for bulk edit, etc) - right now I am using jquery-ui-selectable which seems to work ok, though it is a little flakey. Is there a preferred approach? I saw in another ticket that this is considered out-of-scope for Muuri core, but I suspect I am not the only person who has this use-case.

**Comment by niklasramo** [comment]
I'd say roll your own. Selectable item implementation is pretty trivial and can vary so much that I don't see much point adding it to the core.

**Comment by smfukaya** [comment]
First of all I would like to congratulate for your work! It is very impressive and extremely useful! I intend to use Muuri to help producing court hearings minutes. I wrote this post [Attempt to add Muuri multidraggable items support (Web only)](https://codepen.io/smfukaya/post/muuri-multiselectable-items-web-only) describing my approach to add multidragging support to Web applications using Muuri. I wonder if you could give me some advice on how to improve it.

**Comment by niklasramo** [comment]
Closing this one since there has not been much acitivity in a long time.
