### ISSUE TITLE
Item with select element is making item draggable in Firefox

### ISSUE THREAD

**Issue by bhaskarunichiranjeevi** [haltu/muuri#201]
https://codepen.io/bhaskarunichiranjeevi/pen/BPbqGe?editors=0010

Item 2 in the above given codepen example has select dropdown element. On trying to select an element the item is being dragged only in firefox. Chrome and other browsers it is working fine as Item is not dragged on clicking select element. Tried many options with dragStartPredicate but no luck. Please help.

**Comment by niklasramo** [comment]
@bhaskarunichiranjeevi you indeed _can_ control the drag start logic fully with `dragStartPredicate` function. One of the many ways to accomplish what you are trying to do is the following:

```
var grid = new Muuri('.grid', {
  dragEnabled: true,
  dragStartPredicate: function (item, event) {
    if (!event.isFinal && event.target.nodeName === 'SELECT') return false;
    return Muuri.ItemDrag.defaultStartPredicate(item, event);
  }
});
```

**Comment by bhaskarunichiranjeevi** [comment]
Thanks @yoursweater, I already tried with these before and after your reply too but it didn't worked for me.

**Comment by bhaskarunichiranjeevi** [comment]
@niklasramo your solution worked like a charm. I tried almost same but checking when there is a click on select element and the rest as your solution. Thanks for your solution.
