### ISSUE TITLE
Get the order of the tiles!!

### ISSUE THREAD

**Issue by gurpreetkaurahuja** [haltu/muuri#202]
Hello , 
There was a query regarding the order of the muuri tiles.
After the drag and drop , i want to trace the order of the tiles.
It cant be achieved through "DOM" as tiles are positioned virtually with giving them left  and top.
Is there any function which can give me the order of the tiles after Drag and drop. (except grid.getPosition() as it return left and top only) :)

**Comment by yoursweater** [comment]
Is there some reason why grid.getItems() won't work for you?

**Comment by niklasramo** [comment]
As @yoursweater said `grid.getItems()` is the way to go. If you want to save one `slice` operation in perf critical scenarios you can also directly read from `grid._items` array.

**Comment by gurpreetkaurahuja** [comment]
get.getITems() is returning me the array but not clearly the order in which the tiles are placed after dragging..
Actually i want to store the tiles order after dragging

**Comment by niklasramo** [comment]
Don't store the order based on item._id. It is meant for library's internal purposes only. Instead give the elements id yourself. Thete's a live example of this in the collection of demos I linked earlier.

**Comment by gurpreetkaurahuja** [comment]
Thankyou so much!! It worked  :) :) 👍
