### ISSUE TITLE
Hide grid items by default

### ISSUE THREAD

**Issue by yaroslav-perec** [haltu/muuri#203]
Can I hide the grid items by default?

I need something like this:

`let grid = new Muuri(
      '.widget-container',
      {
        hideByDefault: true
      }
  );`

**Comment by yoursweater** [comment]
Why not just use `grid.hide([elemA, elemB], {instant: true});` in your init function?

**Comment by yaroslav-perec** [comment]
@yoursweater I tried to use `grid.hide ()` without `{instant: true}`, it didn't work exactly as I wanted (elements were first drawn and then quickly hidden), with the option `{instant: true} works fine, thanks

**Comment by yaroslav-perec** [comment]
`grid.hide([elemA, elemB], {instant: true})` works fine
