### ISSUE TITLE
space between items when there are items of diff sizes

### ISSUE THREAD

**Issue by bhaskarunichiranjeevi** [haltu/muuri#209]
Hi @niklasramo ,

I have almost 20+ items and can select/deselect, save/load layout as this example https://codepen.io/niklasramo/pen/YveqNN. 
We also have squared items as in the above example and also some items has the size of two vertically (width) and some are horizantally (height). The issue is when we are moving the items around we are ending up having one/two items space between last row items. I tried playing with layout config also and we already have fillgap as true. But none seems to be working. So kindly help me with the solution.

Thanks,
Chiranjeevi.

**Comment by niklasramo** [comment]
@bhaskarunichiranjeevi please provide a reduced test case in e.g. codepen

**Comment by bhaskarunichiranjeevi** [comment]
<img width="653" alt="space issue between pods 1" src="https://user-images.githubusercontent.com/40071043/45161606-45548300-b1ba-11e8-8e53-f908a1f34583.png">
<img width="639" alt="space issue between pods 2" src="https://user-images.githubusercontent.com/40071043/45161626-4b4a6400-b1ba-11e8-9fc0-14906cb86a14.png">

**Comment by niklasramo** [comment]
I'm sorry, but I'm not understanding the issue here, and still not seeing the live reduced test case ;)

**Comment by bhaskarunichiranjeevi** [comment]
Hi @niklasramo ,

Sorry I don't have any test case since I am not able to replicate the exact issue. In the above second image, 6th row has 2 items which should come next to each other but if you see there is an empty space between items which is not filling up after moving/dragdrop items. So I don't want to have that empty space and need to display 6th row items next to each other. When I was debugging regarding this issue I found this is happening only when the 1st row last item is placed at that position. And if we move that to 1st row first or second position I didn't see any space between items in the 6th row. If you still didn't this let me know how can I able to chat/talk to you directly.

Thanks,
Chiranjeevi.

**Comment by niklasramo** [comment]
I'm sorry, but I can't help out with this one without a reduced test case I can test myself :/

**Comment by bhaskarunichiranjeevi** [comment]
Please find this example and see the empty space between items https://codepen.io/bhaskarunichiranjeevi/pen/NLwYOW

**Comment by niklasramo** [comment]
I see Muuri behaving as supposed to in that example. Yes, unwanted gaps can appear in that example, but that's because of this:

```
.item1{
  width:400px;
}
.item3{
  height:400px;
}
```

You should probably set them to:

```
.item1{
  width:410px;
}
.item3{
  height:410px;
}
```

You have to account for the margin when creating the item styles if you want your layout to behave as a grid. You have defined in CSS an item to be 200px wide and 200px tall with 5px margin on every side. Which essentially means that one _cell_ in the grid is 210px wide and 210px tall. So when you create styles for items that occupy two or more cells vertically/horizontally use this formula: cell size * amount of cells - margins.

**Comment by niklasramo** [comment]
Seems resolve -> closing

**Comment by bhaskarunichiranjeevi** [comment]
Hi @niklasramo 

In the codepen example, it might be because of item width and height but in this screenshot if you see all items are of same height and width but somehow ending up with empty space between items in the 6th row. I want to get rid of that empty space and align Item-11 next to Item-10. And also let me know if we can fix an item at one place I.e, for ex: Item-1 always at first place and no drag and drop or no item can replace this position.

<img width="653" alt="1" src="https://user-images.githubusercontent.com/40071043/46426185-ca747e80-c70b-11e8-8613-e5f2aa6de0fc.png">
<img width="653" alt="2" src="https://user-images.githubusercontent.com/40071043/46426189-ce080580-c70b-11e8-83f4-5e16ab719fda.png">

**Comment by saifullahsaquib** [comment]
@chiranjeevi-bhaskaruni 
https://docs.muuri.dev/grid-methods.html#refreshitems
