### ISSUE TITLE
Restrict the drag and drop of a particular element

### ISSUE THREAD

**Issue by gurpreetkaurahuja** [haltu/muuri#210]
Hello ,
There was a query regarding restricting the drag and drop of specific element.
I went through  [https://codepen.io/niklasramo/pen/LOzZPo](url).
Here we can't drag the first element but its position changes when the other element is dropped on it but what actually i am trying to do is that I want to fix a position of a element.

**Comment by niklasramo** [comment]
I think this is a duplicate of https://github.com/haltu/muuri/issues/205

See my answer there: https://github.com/haltu/muuri/issues/205#issuecomment-417049799

**Comment by gurpreetkaurahuja** [comment]
Yes !!
Thank you so much :)
