### ISSUE TITLE
Phonegap support

### ISSUE THREAD

**Issue by abtx** [haltu/muuri#211]
First of all, thanks for creating this neat library! I love it and would love to use with Phonegap, but as far as I've tested the drag and drop doesn't work well when packaged transpiled. Are there any plans to help with Phonegap support? Thanks!

**Comment by niklasramo** [comment]
Nope, no plans for that. Personally I haven't even tested Muuri with PhoneGap, but I'd be interested to know more specifically what kind of issues there are. If there's something we can optimize here I'm all up for it ;)

**Comment by niklasramo** [comment]
Yeah, would be great if you could pinpoint the issue. Thanks in advance!
