### ISSUE TITLE
Search by selector example?

### ISSUE THREAD

**Issue by rawdot** [haltu/muuri#215]
Is it possible for you to make an item example that is searchable and that doesn't need to be like in the demo, i mean with the selector option because i can't seem to get it done... I am new to programming so it isn't quite clear for me what to do reading the doc.... 

Thank you in forward.

**Comment by rawdot** [comment]
Thanks for the fast reply :)
Yes i have, but couldn't find one except the muuri example that has a search box integrated, but that doesn't work through selectors, i learned alot of these examples though. :)

**Comment by niklasramo** [comment]
Hmmm.. do you mean like using the .filter() method with selectors while using text based search? If so, then you can stop banging your head to the wall because that is a job for a callback function as the predicate.

**Comment by rawdot** [comment]
Yes sounds like the right answer, i guess, but i think i lack the knowledge or the mindframe to understand or implement this. Thanks anyway.
