### ISSUE TITLE
Blurry items on Google Chrome 69

### ISSUE THREAD

**Issue by Pingd0m** [haltu/muuri#218]
Hi,

We are implementing this library on a project where we have a dashboard and widgets.

On Firefox the items seems to have clear fonts and borders, but on Google Chrome everything seems a bit unfocused. I searched this issue and saw some posts on the internet related to this behavior of Google Chrome withCSS transform.

Is someone experiencing the same issue? What could minimize this?

Best regards,
Miguel

**Comment by niklasramo** [comment]
Interesting, is this effect happening on the muuri website and all the muuri demos here: https://codepen.io/collection/AWopag/? Or is it happening in some specific case only?
