### ISSUE TITLE
Can't drag a grid item that contains an <input>

### ISSUE THREAD

**Issue by findingorder** [haltu/muuri#219]
Hello,
I have a grid item that contains an <input>.  When I try to drag it, it won't drag.  If I simply comment out the input, it drags just fine.  How can I make a grid item that contains an input draggable?

Here is a codepen that shows the issue: https://codepen.io/DeliciousPickle/pen/zmaqYJ

**Comment by niklasramo** [comment]
Ummm.. you're explicitly blocking the dragging and sorting of the first item in your JS code. It doesn't matter if there's input or not.

**Comment by c-dante** [comment]
```
    // Prevent first item from being dragged. 
    if (grid.getItems().indexOf(item) === 0) {
      return false;
    }
```

You're literally disabling the drag on the first item...?
