### ISSUE TITLE
drag issue on nested grid

### ISSUE THREAD

**Issue by kumangxxx** [haltu/muuri#220]
Hi, i have a page structured like this

```
body
    - bigGrid
        - bigGridItem
              - smallGrid
                     - smallGridItem
                     - smallGridItem
                     - smallGridItem
        - bigGridItem
              - smallGrid
                     - smallGridItem
                     - smallGridItem
                     - smallGridItem
        - bigGridItem
              - smallGrid
                     - smallGridItem
                     - smallGridItem
                     - smallGridItem
```

i set the touchaction on bot bigGrid and smallGrid to pan-y
problem is i cannot drag any item if i drag it vertically,
drag works fine if i drag it horizontally

any idea what happened ?

here's a video demonstrating the issue
https://streamable.com/erkzc

**Comment by niklasramo** [comment]
Well it looks like the browser scrolling is taking over there. How to fix it? Not sure. Can you provide live code example?

**Comment by kumangxxx** [comment]
Hi,

this is an example on the issue
https://codepen.io/anon/pen/PyXYLr

**Comment by kumangxxx** [comment]
here's my snippet for the issue:
https://codepen.io/anon/pen/PyXYLr

**Comment by niklasramo** [comment]
Ummm yeah, I forgot to ask that what's the intention here? What are you trying to do exactly?

If you let touch-action be `none` dragging will work as usual, but it blocks the browser's default behaviour (e.g. scrolling) for the grid items. If you want set touch-action to `pan-y` you enable browser's vertical scrolling for the items so it will mess up dragging (as we have witnessed). I see nothing really bugging out here and everything seems to work as expected (https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action).

**Comment by kumangxxx** [comment]
I see

at first this is some error on my side
i saw this [thread](https://github.com/haltu/muuri/issues/45)
it was also about touch scrolling vs drag right ?
i thought dragStartPredicate supposed to fix the issue ?

**Comment by niklasramo** [comment]
Yep, that thread is somewhat related and `dragStartPredicate` allows you fine-grained control over the drag start behaviour (which you have to code yourself). But you still did not tell me that what do you want to do? What is the issue?

**Comment by kumangxxx** [comment]
My intention is to have a working vertical touch scroll with drag and drop.

The logic to activate drag and drop is if the drag event started on .handle-bar div inside grid-item, otherwise ignore the drag and let touch scroll handle it.

so my initial thought is that if i use ```pan-y``` in the option, and return ```false``` in ```dragStartPredicate```, this will enable scroll on the grid item, then if i return ```true``` touch scroll will be disabled, no ?

sorry if i somehow drag this conversation

**Comment by niklasramo** [comment]
Maybe just use `auto` for item's touch-action and `none` for `.handle-bar`'s touch-action? And provide `.handle-bar` selector to the dragStartPredicate as handle?

**Comment by h1tan** [comment]
> Maybe just use `auto` for item's touch-action and `none` for `.handle-bar`'s touch-action, and provide `.handle-bar` selector to the dragStartPredicate as handle?

I have the same problem. You need to be able to scroll with the usual touch and move the tile for a long time.
If you set the parameter touch-action: 'pony' then not when you try to drag the tile vertically ( even with a delay) - is reset and the page will scroll

**Comment by niklasramo** [comment]
@h1tan I'm not following entirely. Maybe a _live_ reduced test case would help here?

**Comment by h1tan** [comment]
http://tests.alldan.ru
Thanks for the quick response! 
Look, if you click on the tile and hold, and then move left and right, then OK. But if you click on the tile and hold, and then move up or down, the drag does not work

> @h1tan I'm not following entirely. Maybe a _live_ reduced test case would help here?

**Comment by abishekreddy** [comment]
@h1tan - I'm facing the same issue. Did you find a solution?
