### ISSUE TITLE
Can Muuri work with Bootstrap popover? 

### ISSUE THREAD

**Issue by maya70** [haltu/muuri#226]
Hi, I'm trying to add a [Bootstrap popover](https://www.w3schools.com/bootstrap/bootstrap_popover.asp) in the item-content of Muuri but the popover doesn't appear at all (or sometime it flickers then disappears as if it's competing on z-index with other elements).
I'm specifically trying to get a popover working with the kanban example. I tried different values for z-index and I tried with other Muuris examples too but nothing worked.

**Comment by niklasramo** [comment]
Haven't tried, but I don't see why not :) Can you post a reduced test case in codepen for example so we can see the issue better?

**Comment by maya70** [comment]
Thanks for your reply. I've added the simple popover example (linked in my question) to [this codepen](https://codepen.io/maya70/pen/zMKBvX). The first item in the 'To do' column is supposed to toggle the popover but so far nothing is shown.

**Comment by niklasramo** [comment]
You just need to add and configure the `dragStartPredicate` option:
```
    dragStartPredicate: function (item, event) {
      if (event.target.matches('[data-toggle="popover"]') {
        return false;
      }
      return Muuri.ItemDrag.defaultStartPredicate(item, event);
    }
```

https://codepen.io/niklasramo/pen/mQOQOe


However, you're now left with a CSS z-index issue (which you will easily discover when playing around with the demo) 🙂 One way to solve that is increasing the z-index of the item when it's popover is open.

**Comment by maya70** [comment]
Brilliant! Thank you very much :)
