### ISSUE TITLE
dragging problem after grid shifts positions more than once during drag

### ISSUE THREAD

**Issue by grintz** [haltu/muuri#227]
i am using layout to save and load the order of tiles from local storage.  

when i drag a tile and release it after the grid shifts once, reloading the page works fine with the updated layout order.

however, when i drag an item and the grid shifts underneath once and I then drag it to to different place so the grid shifts a second time during a single drag-event -- the grid breaks and throws an error when reloaded.  (Uncaught Error: [Muuri] sort reference items do not match with grid items.)

what is happening is the itemIndex is starting at 0 in the first example in the loadLayout() function.  And the itemIndex after the grid shifts twice starts with a 1.  so, then indexes are one off and the last one ends up being a -1.  So, then Muuri thinks that there are only 23 items instead of 24 and throws the error.  

how do i fix this? or what is going wrong?

drag item where grid shifted once
![image](https://user-images.githubusercontent.com/4039479/48639959-8dbbc880-e9d5-11e8-84b5-a8a9e2f8de1a.png)

drag item where grid shifted twice
![image](https://user-images.githubusercontent.com/4039479/48639971-96140380-e9d5-11e8-9b16-cb63d545f8ae.png)

**Comment by niklasramo** [comment]
Can you create a reduced test case of this in e.g. codepen?

**Comment by grintz** [comment]
nevermind, i figured it out.  i was calling the update indices when it wasn't necessary.  thanks!
