### ISSUE TITLE
Prevent that a item is added to a grid

### ISSUE THREAD

**Issue by JohMun** [haltu/muuri#228]
First of all, this is a really cool library you have created!

I like to know, if there is a possibility to prevent, that an item is added to a grid, based on a condition. For example, I have two grids (length 2 and 4) and the second one is allowed to hold 4 items as maximum. Now if I drag an item from the first grid to the other, the second grid shouln't reorder itself and should reject the dragged item.

Are there any options to achieve this?

**Comment by niklasramo** [comment]
Yes, [dragSort](https://github.com/haltu/muuri/blob/master/README.md#dragsort-). Just give it a function and return the an array of the grids that a specific is allowed to be dragged into. The item in question will be the first argument.

**Comment by JohMun** [comment]
Yes, works perfect. Thanks for your fast reply.
