### ISSUE TITLE
background where the item can be put

### ISSUE THREAD

**Issue by f3ltron** [haltu/muuri#233]
Hello i would like to background color where item can be put into the the grid.

I tried to background the muuri container but you see all free space not only where the item can be drop.

None of the class expose can be use.

```
.muuri-item {
  background: red;
}
.muuri-item-shown {
  background: red;
}
.muuri-item-hidden {
  background: red;
}
.muuri-item-positioning {
  background: red;
}
.muuri-item-dragging {
  background: red;
}

.muuri-item-releasing {
  background: red;
}
```

Any idea of how i can do that ?

Thanks for your work and for help

**Comment by niklasramo** [comment]
Sorry to say, but with default configuration you can only drop items on top of other items. So there is no empty space where you can drop the item.

**Comment by niklasramo** [comment]
Oh, you mean like a drag placeholder? There's an open issue about that here: https://github.com/haltu/muuri/issues/8

**Comment by f3ltron** [comment]
i am not sure but i think this is it yeah ! 👍
