### ISSUE TITLE
Question: Containers as items

### ISSUE THREAD

**Issue by mariocalin** [haltu/muuri#234]
Hello!

I need to create a graphical editor where you can get items from a palette and place them inside a container. Those items can be simple items and container items (like creating some layout) where you can insert another items and so on.

I have a question. Is it possible to create containers as items?
#
Thank you very much

**Comment by niklasramo** [comment]
Yes, it's possible. However, it might get a little tricky depending on how it's all configured. You might need to create a custom [`dragSortPredicate`](https://github.com/haltu/muuri#dragsortpredicate-) which gives you full control over the drag sorting behaviour.
