### ISSUE TITLE
Center items in muury

### ISSUE THREAD

**Issue by AskDesignTeam** [haltu/muuri#238]
hello

its possible to center items in muury

I want to do like e.g:

![cosl](https://user-images.githubusercontent.com/46100180/50474475-591e3200-09c1-11e9-83d6-0e7561c29f58.jpg)

**Comment by niklasramo** [comment]
Yep, it's possible, but there's no built-in layout algorithm for that. You have to roll one yourself. Check out the docs here: https://github.com/haltu/muuri#layout-

There's also a live demo here: https://codepen.io/niklasramo/pen/LLbLLd

**Comment by AskDesignTeam** [comment]
thx bro :)

**Comment by Harrisandwich** [comment]
@AskDesignTeam Were you able to do this? Can I peek at your layout algorithm?
