### ISSUE TITLE
how to update Muuri option after initialise

### ISSUE THREAD

**Issue by AskDesignTeam** [haltu/muuri#240]
hello Niklas
just a quesstion about muuri 
i create a custum option interface edition for muuri, 
![s5d2](https://user-images.githubusercontent.com/46100180/50535054-b2af6980-0b45-11e9-8170-38aaa073b64b.jpg)

how to update grid option after initialise Muuri?
my code 

```
MuuriElement=new Muuri("#grid);



var obj = {};
obj['showDuration'] = inputShowDuration; 
MuuriElement=new Muuri("#grid",obj);
```

Thx

**Comment by Techn1x** [comment]
I'll use _settings for now as suggested but this would be great in the future. My use case is to set `dragEnabled` true/false using a button (allowing the user to lock their grid in place)

It would be great to do something like.. grid.setOption('dragEnabled', false);

**Comment by elmasry** [comment]
@niklasramo @Techn1x grid._settings won't update dragEnabled, it changes it but the grid items are still draggable, any work around for this?

**Comment by niklasramo** [comment]
Well, the dragStartPredicate option was designed to solve this issue. Can you elaborate a bit more how that is not solving the issue?

**Comment by niklasramo** [comment]
Also, a bit related, the dev branch has Hammer.js removed and I'm considering adding a better way to disable/enable dragging as a part of this refactoring. Breaking changes coming in any case in near future..

**Comment by elmasry** [comment]
Thanks for replying. The only way the child elements dragging works is when I initially set the muuri grid dragEnabled false. I tried to return false on dragStartPredicate, the grid items were no longer draggable but still the child elements dragging was not working, the only way I can get it to work is by setting the grid option dragEnabled false when I initialize the grid.
I think if I knew the difference between initially setting dragEnabled false and returning false on dragStartPredicate, I can figure out the problem.

**Comment by niklasramo** [comment]
> the child elements dragging was not working

What does this mean exactly? Can you share the code that is not working?

**Comment by elmasry** [comment]
Basically any html element that has draggable=true, in my case it's a basic image inside every grid item
```
<div class="grid">
  <div class="item">
    <div class="item-content">
      <img src="@/assets/imgs/example.svg"  draggable="true">
    </div>
  </div>
</div>
```

When I set muuri dragEnabled to false, the dragging html functionality for the example image will work fine but once I set dragEnabled to true, the image dragging doesn't work even if I let dragStartPredicate return false
```
dragStartPredicate: function (item, e) {
  return false
})
```

**Comment by niklasramo** [comment]
Ah, yes, that's a good point and I'm glad you brought it up! There's no elegant solution to this as muuri prevents default for dragstart event, and you can't disable that specifically via API.

You can always just call item._drag.destroy() for any items you want to disable drag for, fully. And then recreate the ItemDrag instance for the item when you want it to make draggable again.

**Comment by elmasry** [comment]
Thank you. How to recreate the itemDrag instance for an item?

**Comment by niklasramo** [comment]
https://github.com/haltu/muuri/blob/master/src/Item/Item.js#L92

**Comment by elmasry** [comment]
Unfortunately it's throwing an error:
Failed to execute 'contains' on 'Node': parameter 1 is not of type 'Node'.
at new Grid (muuri.js?03d1:4363)
```
if (!document.body.contains(element)) {
  throw new Error('Container element must be an existing DOM element');
}
```
Here's how I call itemDrag
```
import ItemDrag from 'muuri'
this.item._drag = new ItemDrag(this.item)
```

"this.item" is a muuri grid item type and I also made sure that "this.item._element" returns a Node

**Comment by elmasry** [comment]
Oh I only had to call ItemDrag this way:
item._drag = new Muuri.ItemDrag(item)
and no need to import ItemDrag from 'muuri'
It works fine now, thanks!
