### ISSUE TITLE
Muuri + angular 6 IE Drag not Working

### ISSUE THREAD

**Issue by arunkmr25** [haltu/muuri#241]
I have integrated Angular7 and muuri for grid drag and drop. everything works fine with Google chrome, firefox and even Edge. But in IE 11 iam not able to drag at all. The same i have implemented using Jquery which works perfectly fine for all browsers. Can anyone help me asap.

**Comment by arunkmr25** [comment]
Any suggestions?

**Comment by SanjayJadon** [comment]
It also not working in Mac - Safari...

**Comment by SanjayJadon** [comment]
Its not working in Macbook Safari with angular... and with all browser and machine its working perfect. So can you tell what is the problem?

**Comment by arunkmr25** [comment]
@niklasramo apologies for the late reply, find the html and type script code that i have written. Drag works fine with google chorme, Edge, firefox  but Drag doesnt Work on IE11

HTML

 <div class="board" id="widgetContainer">
              <div class="board-column todo" id="{{widget?.UserDashboardWidgetId}}uId" *ngFor="let widget of selectedWidgets">
                <div class="board-column-header"><span id="wgtname">{{ widget?.Name }}</span><span (click)="deleteWidget($event)" id="{{widget?.UserDashboardWidgetId}}" style="float: right; margin-right:12px;"></span>
                </div>
                <div class="board-column-content">
                  <div id="{{ widget?.WidgetId }}" [ngSwitch]="widget.WidgetId">
                    <div *ngSwitchCase="'1211'">
                        <app-topsellers [topSellersChild]="selectedWidgets"></app-topsellers>
                    </div>
                  </div>
                </div>
              </div>
            </div>


Type Script

import * as Muuri from 'muuri';

 refreshLayout(widgetService) {
    this.boardGrid = new Muuri('.board', {
      layoutDuration: 400,
      layoutEasing: 'ease',
      dragEnabled: true,
      dragSortInterval: 0,
      dragStartPredicate: {
        handle: '.board-column-header'
      },
      dragReleaseDuration: 400,
      dragReleaseEasing: 'ease'
    }).on('move', function (item: any) {
      widgetService
        .UpdateOrder(
          item.toIndex,
          item.item
            .getElement()
            .getAttribute('id')
            .slice(0, 6)
        )
        .subscribe((resp: any) => { });
    });
  }
![capture](https://user-images.githubusercontent.com/11206794/51114101-43669480-182a-11e9-9f12-cb7b4da593ad.PNG) Iam suppose to drag drop widgets inside a grid .

**Comment by niklasramo** [comment]
Is there any chance you can post this live somewhere, e.g. codepen?
