### ISSUE TITLE
Can you disable transform / translate X/Y?

### ISSUE THREAD

**Issue by joseffb-mla** [haltu/muuri#242]
Is there a way to tell Murri to not do the transform? 

I have inherited a project where the init is shared between all grids and I get a conflict in the secondary grids if I use a custom layout algo. 

I'd like to disable translate X/Y and use the grid in a more manual way to setup columns etc. Possible?

**Comment by niklasramo** [comment]
No, there isn't an easy way to do that. I'm curious though, what do you mean by using "the grid in a more manual way"?

**Comment by joseffb-mla** [comment]
no problem. 

Well because I'm having a conflict with the multiple grids (which I will eventually figure out ;) I would have liked to simply set up my own columns via Tachyons library classes. Can't do that currently because of the absolute / transforms. 

It seems that your library is too smart at times telling me "there is space for 4 columns so we are using 4 columns", but the design calls for only 3... :)

Otherwise the grid engine is perfect :) good job.

**Comment by niklasramo** [comment]
Well you can always override the transforms with !important ;)
