### ISSUE TITLE
Conditional Drag&Drop 

### ISSUE THREAD

**Issue by itrivacchiani** [haltu/muuri#244]
First of all, well done with this great library.

Based on your CodePen where you clone back the element, I was wondering how to prevent an item that has already been dragged and droped to be droped a second time in the second grid.

Thanks !

**Comment by niklasramo** [comment]
If you want to disable dragging completely for those items that have already been added to the second grid you just need to check in `dragSortPredicate` of the first grid if the item in question is already in the other list.

**Comment by ruiger** [comment]
you can add something when you write then function  getAllGrids(dragSort) ，check the item Whether it already exists in second grid，if it already exists do not add into the dragSort grid。iam so sorry ，my english is so bad . i give you some code.

    window.grid1 = new Muuri('.grid-1', {
        items: ".item",
        dragEnabled: true,
        dragContainer: document.body,
        dragSort: getAllGrids
    });

    function getAllGrids(item) {
        console.log('when it fire');
        var allGrids = [];allGrids.push(window['grid1']);
        var id = item.getElement().getAttribute("data-id");
      
        for (var i = 2; i < getLastIndex(); i++) {
            var grid  = window["grid" + i];
            var toGridItems = grid.getItems();
            var hasItem = false;
            //check it already in the gird;
            for (var j = 0, jj = toGridItems.length; j < jj; j++) {
                var toItemId = toGridItems[j].getElement().getAttribute("data-id");
                if (id == toItemId) {
                    hasItem = true;
                }
            }
            if(!hasItem){
                allGrids.push(window["grid" + i]);
            }
        }
        console.log(allGrids);
        return allGrids;
    }

**Comment by itrivacchiani** [comment]
Works fine ! Thanks for your help !
