### ISSUE TITLE
Input element + grid id

### ISSUE THREAD

**Issue by Terveysmyrsky** [haltu/muuri#245]
Hi, 

I just found your outstanding library. Thank you very much, it'll help me a lot. Couple of questions tho, and sorry if these are stupid, but I've developed 20+ hours / day (deadline coming) and my brains are hurting :D 

1. Is there any possibilities to add an input element to content item? I tried, but I cannot type anything to it, because it keeps refreshing as dragged.  

2. I have multiple grid instances. All is working, big badabum and so on, but how on earth can I get a base grid id when dropping an item to it? getGrid keeps giving me 'undefined'. 

Thanks!

**Comment by Terveysmyrsky** [comment]
Yup. Those were kinda stupid questions and I got it all working after couple days of rest. One does not simply understand basic code after 100+ hours of insane development. Sorry for the hassle, shame on me :D 

Nevertheless, your library saved tons of work for me, so thanks again!

**Comment by niklasramo** [comment]
Those were not stupid questions at all :slightly_smiling_face: Glad you got them sorted out and happy to hear you are finding Muuri useful :wink:
