### ISSUE TITLE
Allow overlap?

### ISSUE THREAD

**Issue by Charuru** [haltu/muuri#247]
Optionally can we allow overlap of elements? This should be a simple option to turn overlap reactions off.

**Comment by Charuru** [comment]
@niklasramo I should clarify that I don't want any autosort at all, or items to have any collision. I just want to arbitrarily place layers on a grid. Would that be easier?

**Comment by niklasramo** [comment]
I'm not sure I understand what you are trying to do... but, if you just want to drag items around with no restrictions you don't need Muuri for that at all. Muuri will just be hinderance in that scenario.

Muuri uses hammer.js under the hood to listen to touch/pointer events and then moves the elements based on those events. It's also pretty trivial to do.

**Comment by Charuru** [comment]
I want to drag layers around on a grid (snapping) to simulate plotting areas on a map. Do you have a recommendation for a different lib? If I google hammerjs grid the it only returns muuri.

**Comment by niklasramo** [comment]
Maybe http://interactjs.io would be more useful in your scenario?

**Comment by jmthomas** [comment]
@niklasramo I have a similar question and I'd like to support both the awesome layout engine of muuri and sometimes allow users to individually place windows (either / or but not both). I like your suggestion of interactjs.io but I would have to switch between the two. Is there an easy way to disable muuri layout or disconnect it such that I could let interactjs.io take over?
