### ISSUE TITLE
Swapping items between two grids

### ISSUE THREAD

**Issue by stat92** [haltu/muuri#248]
Can I swap two items in two grids? Using `dragSortPredicate` I can swap two items only within one grid.
Thanks in advance.

**Comment by stat92** [comment]
Solved:
```
.on('receive', (data) => {
        const { toGrid, fromGrid } = data;
        const item = toGrid.getItems()[1];
        toGrid.send(item, fromGrid, 0, undefined, { layoutSender: false, layoutReceiver: false });
})
```

**Comment by niklasramo** [comment]
Yeah intuitively speaking setting dragSortPredicate.action to "swap" should also work when dragging items between grids, but I remember there were some problems with that so I didn't do it like that. Just can't remember what the issues were anymore... might be a good time to revisit that piece of code :)

**Comment by niklasramo** [comment]
I've decided to fix this one for the next release so that you can define explicitly the action for the grid-to-grid drag scenario and support "swap" if that's defined.

**Comment by niklasramo** [comment]
Done in `dev` branch, will be landed to master with the next release.

**Comment by niklasramo** [comment]
Let's keep this open until it's actually landed to master branch.
