### ISSUE TITLE
dragSortPredicate improvement

### ISSUE THREAD

**Issue by stat92** [haltu/muuri#249]
Is it possible to call `dragSortPredicate` on `mouseup` event. Now it's called only on `mousemove`.
With this additional check users will be able to receive and drop an `Item` only on the release.

P.S. May be checking for `beforeReceive` listeners result and preventing receiving will be better solution?

**Comment by niklasramo** [comment]
Actually dragSortPredicate is called on mouseup/touchend event if the dragSortInterval timeout is still pending, so you could try setting reeeeally big number to dragSortInterval option to make sorting happen only on release.

But, you're right that there are use cases for always calling dragSortPredicate on the end event too so I'll try to make that adjustment there when I get a chance to poke around the codebase again ;)

**Comment by niklasramo** [comment]
I'll add a mention about the long timeout "hack" in the docs, might be useful in some scenarios. I don't think this requires necessarilly any modifications in the code since the hack should work reliably and it's a bit of an edge case.

**Comment by stat92** [comment]
Got it

**Comment by niklasramo** [comment]
Let's keep this open until it's actually landed to master branch.
