### ISSUE TITLE
Changing dragEnabled option on fly

### ISSUE THREAD

**Issue by o2sevruk** [haltu/muuri#250]
Hi!
Thanks for the great job!
I have an issue with update dragEnabled option on fly. I need to change this option to true value when I check some checkbox. I read about issue like I have in this issue #189 (It works well on desktop). But it not working when dragEnabled: false or hasn't value. 
If I set dragEnabled: true, I have a problem on mobile devices (Android) with scrolling (content not scrolling).
Thanks)

**Comment by niklasramo** [comment]
You need to enforce the items' [touch-action](https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action) CSS property to 'auto' when you when drag is disabled. 'dragStartPredicate' is the "correct" solution for now to disabling/enabling drag on the fly.
