### ISSUE TITLE
Need help about Sorting by multiple ids in data-attribute?

### ISSUE THREAD

**Issue by beratgashi** [haltu/muuri#251]
Hi there,

First of all I want to congratulate **Niklas** for his amazing work.

My issue is this, I'm trying to sort elements by a multiple ids of an data-attribute for example the element has this:
`data-categories="[3,1,7,9,5]"]`

Is it possible to sort from this way or an array because I've tried but the sort allows only object or null!

Any answer is appreciated.
Thank you,
Best Regards.

**Comment by niklasramo** [comment]
I suppose you're talking about sorting with the help of sortData option? It should work for most cases and if you need more expression power you can always feed the [grid.sort()](https://github.com/haltu/muuri/blob/master/README.md#gridsort-comparer-options-) method a custom comparer function that let's you to sort the items as you wish.

Out of curiosity, what would the sort logic be (pseudo-code) in this case where you have multiple values in one key?
