### ISSUE TITLE
[support question] Disabling/Reenabling resize event listener for muuri

### ISSUE THREAD

**Issue by FotisK** [haltu/muuri#252]
I'm trying to temporarily prevent resizing the window from causing the layout to shift.
I'm sure this must be something trivial, but I'm not very experience in JS so I can't wrap my head around it. There is something in the documentation about the .on/.off methods but I'm not sure how to use these in this case. I tried studying the code in the .js file 

> if (mygrid._resizeHandler) {window.removeEventListener('resize', mygrid._resizeHandler);}

while I managed to remove the listener with the above code, I couldn't properly readd it since
the **debounce()** function and **layoutOnResize** value are limited in scope inside the js file.

> window.addEventListener('resize',(mygrid._resizeHandler = debounce(function() {grid.refreshItems().layout();}, layoutOnResize)));

What is the proper way of doing this? 
Thanks!

**Comment by niklasramo** [comment]
Set [layoutOnResize](https://github.com/haltu/muuri/blob/master/README.md#layoutonresize-) to false and do the resize logic yourself ;) You just need to call grid.refreshItems().layout() on resize.

**Comment by FotisK** [comment]
thank you Niklas!!!
