### ISSUE TITLE
Suggestion: Pause sort

### ISSUE THREAD

**Issue by Harrisandwich** [haltu/muuri#253]
Hello! 

I was wondering if it's possible to include a way to pause sorting, then unpause it. 

In my case, I want to allow the user to resize grid items. At the moment, when the grid item is a size that would trigger a sort, all of the elements move around. I would like to be able to prevent sorting until the user has finished sizing the element, then unpause when complete. I think it would be quite handy!

**Comment by niklasramo** [comment]
What triggers the sort in your case? There is no constantly active sorting going on in Muuri so there's really nothing to pause.

Also, do you mean with sorting the actual sorting or the layout procedure? You can sort grid items without triggering layout. grid.layout() is the method that makes the items move visually.

**Comment by Harrisandwich** [comment]
Ooooohhh. Then it must be layout I'm referring to, not sort. My bad
