### ISSUE TITLE
What's the difference between Active and Visible Items?

### ISSUE THREAD

**Issue by FotisK** [haltu/muuri#254]
While I was looking if there was some existing method to return only the items that are currently scrolled into view I stumbled on the isActive and isVisible methods; what's the difference between Active/Visible Items?

**Comment by niklasramo** [comment]
isVisible -> is the item visible?
isActive -> is the item part of the layout?

The distinction is made so that you could have visible items that are not part of the layout and hidden items that are part of the layout. A very rarely needed feature, but it's there.

**Comment by FotisK** [comment]
I see Niklas, thank you!
