### ISSUE TITLE
CSS transform decimal precision issue

### ISSUE THREAD

**Issue by armujahid** [haltu/muuri#256]
Can we somehow improve transform precision without writing my own layout algorithm?
**Demo:** https://codepen.io/armujahid/pen/MLPvbW
Its simple bootstrap row with three `col-md-4` columns
![image](https://user-images.githubusercontent.com/3725386/52857676-9e511b80-3149-11e9-88d4-d8baa6d7359c.png)

X transform should be 526.66px instead of 527px. Because of this decimal precision issue 3rd column is displaying in 2nd row although it should be displayed in 1st row.

**Comment by niklasramo** [comment]
Sure, just set `layout.rounding` to `false`=> https://codepen.io/niklasramo/pen/OdBrJZ

**Comment by armujahid** [comment]
Thanks. Sorry I missed layout options while scanning docs. I should have read docs carefully.
