### ISSUE TITLE
Muuri combined with Lazyload

### ISSUE THREAD

**Issue by superfein** [haltu/muuri#257]
Hi I'm trying to get Muuri to work with lazysizes, an image lazy loading plugin. The images just stack on top of each other because the height cannot be set on each image, as the images have varying heights (depending on the way my client cropped the images).

Here's a Codepen of where I am so far: https://codepen.io/anon/pen/daQmrM?editors=0110

Would love some assistance on this, mainly if it's even possible to get this to work without hard-coded height attributes on the img elements.

Thanks.

**Comment by niklasramo** [comment]
Hi! There's a lot going on in that demo (item structure is pretty deeply nested which makes it a tad difficult to follow), so I suggest starting with something small (e.g. this https://codepen.io/niklasramo/pen/xWYdmp) and building the lazyload on top of that. 

As long as you've got your CSS in order Muuri works as advertised. No need to set fixed dimensions to items. All you need to do is call grid.refreshItems().layout() after any item's dimensions have changed (e.g. after item's image is loaded). Muuri reads the item dimensions from the item element, so just make sure that reflects the item's layout size.

**Comment by msdobrescu** [comment]
In case of a slow responding server, or slow bandwidth or too many items, I have the same behaviour.
I had to set the items height in a loop before instantiating Muuri.
