### ISSUE TITLE
drag and drop safari not working

### ISSUE THREAD

**Issue by f3ltron** [haltu/muuri#258]
Hello it is related to #241 but i create another for a more consistent title

For any drag and drop on safarie the drag and drop start and block after a no more working after.

**Comment by niklasramo** [comment]
https://haltu.github.io/muuri/ works fine on my safari, can you provide some more details?

**Comment by f3ltron** [comment]
Can you give me a simple project that work for you i will try on mine ?

**Comment by niklasramo** [comment]
All Muuri projects I've tested work on my Safari (version 12.0.3) on Mojave, including all examples here: https://codepen.io/collection/AWopag/

**Comment by niklasramo** [comment]
@f3ltron Can you provide a reduced test case where Muuri is not working with Safari? I will be closing this issue if I can't confirm the issue.

**Comment by f3ltron** [comment]
I will just let me a bit time next week

**Comment by niklasramo** [comment]
Closing for now, let's revisit this when/if we have reproducable example of this.
