### ISSUE TITLE
Any way to support `nowrap`?

### ISSUE THREAD

**Issue by peoro** [haltu/muuri#259]
I have an horizontal flexbox that is meant to extend past the page width. `flex-wrap: nowrap;` does the trick when not using Muuri.

With Muuri, though, the flexbox always wraps around. Is it possible to avoid this?

**Comment by niklasramo** [comment]
Hi! Maybe a little live demo could showcase the issue a bit better? I'm not fully grasping the issue here.

**Comment by peoro** [comment]
I created [this JSFiddle](https://jsfiddle.net/peoro/17qe0xny/24/).

The first flexbox extends beyond the width of the page (since it's got `wrap:nowrap`). The second one, that uses Muuri, doesn't

**Comment by niklasramo** [comment]
@peoro thanks for the demo and sorry for the laaaaate answer. In any case, understood the question from the demo 👍 As Muuri's items are absolutely positioned they are really not affected by flexbox, so you have to work around it.

The simplest way to accomplish this is just setting Muuri into horizontal layout mode and defining the grid's height to the item's height: https://jsfiddle.net/on4x0fu7/2/. However, this only works nicely if all your items are the same size.

The more robust way is just to provide your own layout algorithm:  https://jsfiddle.net/x0nowm7s/

I hope this helps 😉
