### ISSUE TITLE
Prevent item being dropped on certain other items

### ISSUE THREAD

**Issue by yomomano** [haltu/muuri#260]
First of all, thanks for this amazing piece of work. Love working with it.
I am looking for a way to prevent an item to be dropped on certain items. I saw some posts in which you suggest to use 'dropMove', but:
* how do I detect on which item the dragged item is located? The hover-item is being moved to make space for the dragged item so it must be detectable I suppose.
* if somehow this item can be found, and is not suitable for drop, how do I cancel (1) the layouting while dragging, and (2) restore dragged item to last location/grid when releasing?

**Comment by niklasramo** [comment]
To prevent item being dropped on specific item you can use the technique demonstrated here: https://codepen.io/niklasramo/pen/EEdmJr (just use `dragSortPredicate`).

When you drag an item around the sorting that occurs is not cancelable, but there are plenty of ways to do the cancellation manually (revert the layout). You could keep track of the dragged item's _origin_ index and just `grid.move(droppedItem, originIndex)` on the `dragEnd` event. Or you could just store the whole state on `dragStart` (`const origState = grid.getItems()`) and just do `grid.sort(origState)` on `dragEnd`.

**Comment by LordRampantHump** [comment]
I too am interested in this to a degree, however i want to get the element below the dragged item so that i may make a "drag to me to delete" button

Any advice?
Thanks

**Comment by bernhardberger** [comment]
> I too am interested in this to a degree, however i want to get the element below the dragged item so that i may make a "drag to me to delete" button
> 
> Any advice?
> Thanks

Did you ever find a solution for this?
