### ISSUE TITLE
Can we move items using keyboard Arrow keys?

### ISSUE THREAD

**Issue by robinprashanth** [haltu/muuri#263]
In my project, I am trying to implement move items in a grid to some position using the arrow keys. Can anyone help on how to implement keyboard arrow event?

**Comment by niklasramo** [comment]
You can just call grid.move() when arrow key is pressed. If you need help with listening arrow key press I recommend checking this out: https://css-tricks.com/snippets/javascript/javascript-keycodes/.

**Comment by robinprashanth** [comment]
Thanks for the help. Sorry for the late reply.
