### ISSUE TITLE
How can we drag only from selected region of item?

### ISSUE THREAD

**Issue by armujahid** [haltu/muuri#265]
Currently items are draggable from anywhere inside item's body. How can we drag only from selected region of item? e.g. only via placeholder div.
![image](https://user-images.githubusercontent.com/3725386/54664830-28a0ec80-4b07-11e9-8871-5091613d78b6.png)
**Example:** https://jsfiddle.net/armujahid/m7cfs1uo/

This may be related to https://github.com/haltu/muuri/pull/262

**Comment by niklasramo** [comment]
You can define your own [`dragStartPredicate`](https://github.com/haltu/muuri#dragstartpredicate-) or use the _handle_ option of the default predicate.

**Comment by armujahid** [comment]
Thanks. I totally forgot about dragStartPredicate. 
Solution: https://jsfiddle.net/armujahid/m7cfs1uo/18/
