### ISSUE TITLE
Option to set width of the grid

### ISSUE THREAD

**Issue by upendra-web** [haltu/muuri#270]
First of all, thanks for making such an awesome library.

I have a question. Can we center the elements to the grid?

Muuri positions elements to the left (as in 1 in the diagram below), I want to align the elements to the center of the layout (as in 2 in the diagram below). Is this possible?

![muuri](https://user-images.githubusercontent.com/43108965/55673841-12e34380-58cb-11e9-9687-2956cfc7b43a.png)

**Comment by niklasramo** [comment]
Well, yes and no. Muuri's default layout algorithm does not set the width of the grid element, it reads it before doing layout and arranges the items based on it. So you can set the width of the grid element and Muuri respects that. Then you only need to center the grid element relative to it's container.

However, in practise, there will probably be some leftover space on the right side unless your items align nicely always. Getting rid of that is a bit more complicated. You can always build a custom layout algorithm, or you can try to detect the excess space on the right and apply offset to the grid container accordingly.

**Comment by upendra-web** [comment]
Thanks for the reply. Anyway, I used CSS to solve the problem.

**Comment by KevinUre** [comment]
I'm looking to do something similar, what CSS did you use to solve this?
