### ISSUE TITLE
Drag-and-drop doesn't work on Safari on Mac

### ISSUE THREAD

**Issue by workboxsoftware** [haltu/muuri#274]
Here's a pen that shows the problem.  It works fine on Chrome and Firefox.  It also works fine when run on version 0.4.0.  Seems to have been broken on the 0.5.0 release.
https://codepen.io/bobglass53/pen/XQQdQL

**Comment by niklasramo** [comment]
https://github.com/haltu/muuri#web-animations-polyfill

There's no Web Animations polyfill on that demo (Safari does not support Web Animations).

**Comment by workboxsoftware** [comment]
Thank you - that fixed it.

Sorry, the website caniuse.com listed web animations as available in Safari 12.1 - but then I just looked closer and it said “partial”.

It’s a beautiful product - thank you for open sourcing it.

Bob

On Apr 30, 2019, at 1:43 AM, Niklas Rämö <notifications@github.com> wrote:

https://github.com/haltu/muuri#web-animations-polyfill <https://github.com/haltu/muuri#web-animations-polyfill>
There's no Web Animations polyfill on that demo (Safari does not support Web Animations).
