### ISSUE TITLE
Remove Hammer.js dependency

### ISSUE THREAD

**Issue by niklasramo** [haltu/muuri#275]
Hammer.js is an awesome lib, but it has its share of performance issues. With hundreds of draggable items there is a lot of performance overhead with Hammer. And additionally Muuri only uses a _tiny_ bit of Hammer's feature set.

So with all this in mind I've decided that it's time to let go of Hammer and just building that piece of functionality into Muuri's core. It's not _that_ much of code and it _will_ allow smoother dragging with hundreds of items.

**Comment by marataziat** [comment]
What if you just disable dragging? Will it help?

**Comment by LordRampantHump** [comment]
sounds sexy!

**Comment by niklasramo** [comment]
Almost done now, but dang, this was definitely not a walk in the park. So many quirks dealing with touch/pointer events 😓

**Comment by niklasramo** [comment]
I think it's done now, at least the tests pass and everything seems to work 🙂 I guess the question is that is it good enough already 🤔
