### ISSUE TITLE
grid.remove() not enough?

### ISSUE THREAD

**Issue by LordRampantHump** [haltu/muuri#278]
When removing an grid item via 
```
dragStartPredicate: function (item, event) {
}
```
I have noticed that while it seems to be removed from the grid it remains in the dom.
I have overcome this using jquery
```
 grid.remove(item);
 $(item._child).remove();
```

but i wanted to know is this normal? It doesn't feel so unless I am missing something
![scrum](https://user-images.githubusercontent.com/37228494/57260660-ee62be80-7064-11e9-839e-5c70b9b5311c.JPG)

**Comment by niklasramo** [comment]
@LordRampantHump By default the item's associated DOM node is not removed from DOM, but you _can_ optionally tell the command to _also_ remove the element from DOM: https://github.com/haltu/muuri#gridremove-items-options-

**Comment by LordRampantHump** [comment]
Oh ok, interesting. Thanks for getting back to me
