### ISSUE TITLE
Space between items

### ISSUE THREAD

**Issue by Enngage** [haltu/muuri#280]
Hello,

thanks a lot for this awesome lib. Have been using this for some time with great success. I was wondering if it there is any way to set space between items. By space between I mean that the margin would not be applied to first & last items in each row - which is why setting `margin` on item container does not work the way I need. 

I'm able to do this quite easily with flex, but that unfortunately breaks muuri functionality and calculations.

**Comment by niklasramo** [comment]
Well you can always provide a custom layout algorithm and add the spacing there, but other than that there's really no other way.

**Comment by Enngage** [comment]
That is probably too hardcore for my purpose :) Thank you anyway, it's great lib!
