### ISSUE TITLE
muuri kanban

### ISSUE THREAD

**Issue by laetisam** [haltu/muuri#281]
Hi,
I'm working with muuri kanban
...
.on('dragReleaseEnd',function (item){
...
I can access to item.getElement().innerHTML
But how can I access to the target title?
Thanks in advance

**Comment by niklasramo** [comment]
What is the target title in specifically in this case? `item.getElement()` gives you the DOM node and the rest of the solution should be just reading the title from DOM (wherever that may be in your case).

**Comment by laetisam** [comment]
Hi, 

Thank you so much, I found the solution. 

I have another question: 

I work with "simple kanban with scrolling containers" and ".on
('receive', function(data){....} 

with data.toGrid.getElement().parentNode.. I know where the item is, but
how to know where the item come from? 

With a condition, how to refuse the deplacement and move the item to its
start position? 

Yours sincerely. 

Le 18/05/2019 19:53, Niklas Rämö a écrit :

> What is the target title in specifically in this case? item.getElement() gives you the DOM node and the rest of the solution should be just reading the title from DOM (wherever that may be in your case). 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].

 

Links:
------
[1]
https://github.com/haltu/muuri/issues/281?email_source=notifications&amp;email_token=ADRSP4QXDY63ZR4JJRFMX3TPWA67XA5CNFSM4HNAXTJ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODVWTA2A#issuecomment-493695080
[2]

**Comment by GianlucaFrongia** [comment]
> with data.toGrid.getElement().parentNode.. I know where the item is, but
> how to know where the item come from?

You can get it like this:
```js
}).on('receive', function (data) {
   let fromGrid = data.fromGrid;
}
```

**Comment by laetisam** [comment]
Thank you, 

But I want to read the element dropped (in data.fromGrid, the element is
not present of course), 

And how to refuse the drop (with a condition) and let the element in its
start position? 

Yours sincerely 

Le 22/05/2019 14:09, Gianluca Frongia a écrit :

>> with data.toGrid.getElement().parentNode.. I know where the item is, but
>> how to know where the item come from?
> 
> You can get it like this:
> 
> }).on('receive', function (data) {
> let fromGrid = data.fromGrid;
> }
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].

 

Links:
------
[1]
https://github.com/haltu/muuri/issues/281?email_source=notifications&amp;email_token=ADRSP4QJCNCBXP323CTPX6TPWUZV7A5CNFSM4HNAXTJ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODV62XGQ#issuecomment-494775194
[2]

**Comment by niklasramo** [comment]
> But I want to read the element dropped (in data.fromGrid, the element is
not present of course),

https://github.com/haltu/muuri#receive -> `data.item`

> And how to refuse the drop (with a condition) and let the element in its
start position?

By default you can't _refuse_ the drop. You need to build create a custom dragSortPredicate to make that happen: https://github.com/haltu/muuri#dragsortpredicate-
