### ISSUE TITLE
Gridstack-like Layout Algorithm?

### ISSUE THREAD

**Issue by ico85** [haltu/muuri#284]
Is it possible to achieve same layout-behaviour as here with custom layout-algorithm? http://gridstackjs.com/ I cannot use jQuery in the project environment.

I played around a bit with the layout function but I do not understand exactly when the layout-function is called. Only on Collision on drag?

**Comment by niklasramo** [comment]
Yes, it can be done, but you do have to create custom layout algorithm for it and also a custom data structure for the layout as it can't be deducted just from the order of items.

layout function is called every time the items are positioned -> it calculates the positions for the items

**Comment by zrubinrattet** [comment]
@ico85 did you find a way to achieve the layout behavior from gridstackjs?

**Comment by ico85** [comment]
@zrubinrattet sorry, but no. I think it's not that simple because the type of layout algorithm is completely different from what muurijs supports. So maybe it's possible but with a lot of afford. I took a look at react-grid-layout. I think the kind of sorting is very intuitiv. Also inspired by gridstackjs.
