### ISSUE TITLE
Getting error when I am trying to hide the card and save it or restore it

### ISSUE THREAD

**Issue by rasikaksh** [haltu/muuri#286]
Hi,
I am implementing a feature where I need to use muuri for sorting and hiding cards in reactJs.
I have 'Hide' button for each chart . If we click on hide, it is supposed to change the position of that card and send that card to another grid. When I save this change, I am getting below error 

"DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node." 

Can anyone help me ?

**Comment by rasikaksh** [comment]
P.S I have not used  removeChild property anywhere in the code.

**Comment by niklasramo** [comment]
Muuri assumes that every item element is a direct child of grid element and additionally the item elements must not be removed without Muuri's knowledge. So probably one of these scenarios (or both) is happening in your case. You should `key` the item components in React and also make sure that the DOM node order is correct (grid > item).

**Comment by rasikaksh** [comment]
Thanks @niklasramo  for quick response.
Can you please elaborate this line : 
'You should key the item components in React and also make sure that the DOM node order is correct (grid > item).' 

Basically flow of my code is like this:
1. charts are getting loaded with Hide button on each chart
2. I can drag/drop the charts.
3. There are 2 grids I have used in muuri..  1: 'grid' : to show visible cards 2: 'hidden grid':to show hidden cards. I have 'hiddenCards' section which will display all hidden cards when I click on Hide button of cards.
4. When I am clicking on Hide button of any chart, I am able to see that particular card in Hidden section. 
5. In save my code logic is as below:
state variable which is holding visible and hidden cards data will be saved in localStorage and it will build all the cards again with the help of Muuri.

Now when I hide the card and save it , I am getting this error.

@niklasramo  So you mean to say we cannot change the existing order of items that we send to muuri right ?

**Comment by niklasramo** [comment]
As for the React and keys: https://reactjs.org/docs/lists-and-keys.html

> So you mean to say we cannot change the existing order of items that we send to muuri right ?

I don't fully understand this means 😕 

Generally speaking using Muuri with React is not easy and might lead to weird scenarios/bugs, because Muuri modifies the DOM and React modifies the DOM. So you have to be really careful when coordinating that DOM manipulation.
