### ISSUE TITLE
Is it possible to drag a copy of item leaving original intact?

### ISSUE THREAD

**Issue by JetsonDavis** [haltu/muuri#287]
Fantastically beautiful piece of code!

I'd like to use Muuri to drag objects from one list to another while keeping the original list item intact. Is there any way to do this?

Thanks!

**Comment by GianlucaFrongia** [comment]
like this [demo](https://codepen.io/niklasramo/pen/zPVBLq) ?

**Comment by JetsonDavis** [comment]
Pretty close - thanks Gianluca.  Did that come from the Muuri website?  
I'd like it more if it never removed the red box but instead lifted a clone.  Anyone seen a demo that does that?
Thanks!

**Comment by GianlucaFrongia** [comment]
you can find more demo on codepen!

i did a small [demo](https://codepen.io/Chillskyy/pen/WBmdBa)

**Comment by JetsonDavis** [comment]
That is incredible - thank you so much!!!!

**Comment by GianlucaFrongia** [comment]
you need to implement a logic that prevents adding the item on the same grid.

**Comment by JetsonDavis** [comment]
Oh, that's funny.  If you click on the source (red) tile, it duplicates itself!

**Comment by GianlucaFrongia** [comment]
ive changed it a bit: [demo](https://codepen.io/Chillskyy/pen/WBmdBa)

**Comment by JetsonDavis** [comment]
Cool - still a small bug.  If you drag #1 into the grid, then move #1 to a different location, it regenerates on the left!

**Comment by GianlucaFrongia** [comment]
ok check it out again

**Comment by JetsonDavis** [comment]
Still does the same?  Refresh the page and try to drag 7 to the left of 6!

**Comment by GianlucaFrongia** [comment]
ups wrong pen -> [demo](https://codepen.io/Chillskyy/pen/NZxrgG)

**Comment by GianlucaFrongia** [comment]
there is an edge case to consider: 
![Kapture 2019-06-14 at 19 54 50](https://user-images.githubusercontent.com/20201125/59528348-51563980-8ede-11e9-9026-de1a8e6539fc.gif)

@niklasramo why is the receive event called so early ?
the same thing happens in your example:
![Uploading Kapture 2019-06-14 at 20.17.02.gif…]()

**Comment by niklasramo** [comment]
@GianlucaFrongia You've done a very nice demo here so far, great job 👍 I'm not sure what you with receive event being called _early_?

However, you actually found a bug. `grid.once()` listener can not be unbound at the moment with `grid.off()` which is what causes the duplicate items. If you change `once` -> `on` it should work as supposed to. I'm actually thinking of removing the `grid.once()` method altogether as it is just a convenience method, and making it work with `grid.off()` would require more code and more maintaining.

However, I revised the old demo a bit to be a bit more elegant as it was originally just a quick hack: https://codepen.io/niklasramo/pen/zPVBLq

**Comment by GianlucaFrongia** [comment]
thanks for the feedback! 
> I'm not sure what you mean with receive event being called early, can you elaborate a bit?

In the [docs](https://github.com/haltu/muuri#receive) :
> The item is dragged into another grid.

Means that the event is triggered when the dragged object is over a grid ? I understood it in such a way that the event only happens when the grid 'receive' the object.

**Comment by GianlucaFrongia** [comment]
@JetsonDavis bug free [demo](https://codepen.io/Chillskyy/pen/NZxrgG)

**Comment by JetsonDavis** [comment]
Cool!  While I have the attention of both of you, can you tell me how to put a dashed line around the target area with text in the middle “Drop here” or such?

I put a div inside 'board-column-content’ but I get this:

**Comment by niklasramo** [comment]
@GianlucaFrongia Yes, the `receive` event should be emitted immediately _after_ the item has been moved between grids (for the _receiving_ grid). And by _moving_ I mean that when the item has become part of the other grid's layout, so it is _not_ emitted by merely hovering the item over another grid.

**Comment by niklasramo** [comment]
> how to put a dashed line around the target area with text in the middle “Drop here” or such?

@JetsonDavis that's separate issue, so maybe better to create a new issue for that.

**Comment by JetsonDavis** [comment]
One last question about this demo.  Say I have added the '1' box in a few places and even moved around the order of the right boxes.  What is the easiest way to determine the order of the boxes, going left to right, then down?  All I can come up with is looking at the translateX & Y values and using them to compute the order, but there must be a more simple way?

Thank you!

**Comment by niklasramo** [comment]
[`grid.getItems()`](https://github.com/haltu/muuri#gridgetitems-targets-) returns the grid item instances in order. The order is _not_ the visual order though (necessarilly) but the internal order which is fed to the layout algorithm.

**Comment by JetsonDavis** [comment]
But if I do a grid.synchronize() I will get the visual order, yes?

**Comment by niklasramo** [comment]
`grid.synchronize()` will only reorder the _DOM nodes_ based on the internal item order. In most cases you should not need to call `grid.synchronize()`. You should _only_ use it if you have some code that requires the DOM nodes to be in sync with the internal order.

**Comment by JetsonDavis** [comment]
So what is the best way to determine the visual order of the items?  Thanks!

**Comment by GianlucaFrongia** [comment]
@niklasramo this [demo](https://codepen.io/Chillskyy/pen/XLdqJZ) shows my question with receive:

![Kapture 2019-06-17 at 9 16 47](https://user-images.githubusercontent.com/20201125/59585546-08ba9e00-90e1-11e9-86ab-d2582e4e1346.gif)

so when the 'receive' pop ups, the item is part of the other grid ?
>  mean that when the item has become part of the other grid's layout

**Comment by niklasramo** [comment]
@JetsonDavis well, the question that needs answering first is "_what is the visual order_"? Muuri works by having the items ordered internally in some order and then it feeds the items to the layout algorithm which generates positions for the items. How the items are positioned is _fully_ dependent on the layout algorithm and how it uses the items as input. As you can also provide your own layout algorithm it's pretty much impossible to have an API in Muuri that would give you the _visual order_.

**Comment by niklasramo** [comment]
@GianlucaFrongia Yes, when the receive pops up the item is indeed part of the other grid, it's positioned as the last item. When moving item between grids the default drag sort predicate will first try to find a grid it overlaps with enough and then it tries to find out if it overlaps enough with any item within that grid. If no suitable item is found it will be added as the last item in that grid.

You _can_ override all of that logic by providing your own `dragSortPredicate`, but it's quite a lot of logic and code there to make it work nicely. I've actually been thinking myself too how to make that logic easier to customize, because it indeed does not look so nice when the item is first added as the last item and then soon after it probably overlaps with some item and is moved again. This looks especially weird with the placeholder, which is coming up.

**Comment by JetsonDavis** [comment]
@niklasramo I discovered that I can use grid.getItems() to get an array in visual order!

**Comment by niklasramo** [comment]
@JetsonDavis It's not guaranteed to be the visual order. It depends on the layout algorithm.

> [`grid.getItems()`](https://github.com/haltu/muuri#gridgetitems-targets-) returns the grid item instances in order. The order is _not_ the visual order though (necessarilly) but the internal order which is fed to the layout algorithm.

**Comment by GianlucaFrongia** [comment]
@niklasramo thanks for the explanation 👍 
in our projects we had the same problem that the item cloned back before the user let go of the item. But seems that your hack works. We ende up using the`grid.send` method and disabled drag&drop.

**Comment by niklasramo** [comment]
I think the original issue here was solved so closing this one, thanks @GianlucaFrongia for the help here!

**Comment by JetsonDavis** [comment]
Hey Niklas,

Do you have a code pen for this demo appearing on Muuri homepage? (See red arrow)

Thanks!
