### ISSUE TITLE
Layout spacing issues when calling refresh.Items().layout()

### ISSUE THREAD

**Issue by Radlad-io** [haltu/muuri#288]
I'm having an issue when I refresh my layout. I can't seem to traverse this. I thought it was a CSS issue at first, but after a lot of digging I'm starting to think it's Muuri (or rather my understanding of Muuri). 

Here's the issue in action:

![Untitled](https://user-images.githubusercontent.com/24879510/58820225-03992180-8600-11e9-9450-3acfcefb45b1.gif)

Here's a code pen (with wonky icons):

https://codepen.io/Proinsky/pen/JqxgMY

**Comment by elmasry** [comment]
If you manually removed the hidden items you will get a perfectly aligned grid like the screenshot I attached so basically when you switch from one filter (python, trap, nodejs.. ) to another, use grid.remove() to hide the non-relative items.

![Screen Shot 2019-06-06 at 8 47 55 PM](https://user-images.githubusercontent.com/970314/59058202-673f7b00-889c-11e9-9341-c1cd164853c7.png)

**Comment by niklasramo** [comment]
@Proinsky Why do you manually toggle `display:none` instead of calling `grid.hide()`/ `grid.show()`? That's the issue there. The hidden items are still considered part of the layout because they are not hidden with `grid.hide()`.

**Comment by Radlad-io** [comment]
Honestly. It was an extremely stupid oversight. Whomp. It was coded prior to implementing muuri and just sort of adjusted on the fly. Sorry for gumming up the thread.
