### ISSUE TITLE
How to customize "dragPlaceholder" CSS

### ISSUE THREAD

**Issue by papakai** [haltu/muuri#300]
I've configured it that way for now
```javascript
dragPlaceholder: {
      enabled: true,
      duration: 300,
      easing: 'ease',
      createElement: null,
      onCreate: null,
      onRemove: null
    }
```

I was just asking myself: you use a "div" element by default as placeholder item, how can I change its default css so that it fits that gray bordered one in the packagery example?
![image](https://user-images.githubusercontent.com/229425/61226081-1a17ba00-a722-11e9-8a2c-7cf6a5d5aa56.png)
I wasn't able to detect that (temporarily inserted?) div item in development tools console, so no idea how that exactly works and how I can customize / override a standard css class if available.
(yes I can ensure I am using v0.8.0)

Or am I misunderstanding the use of "dragPlaceholder" option?

**Comment by papakai** [comment]
Ah, I think I found it "div.muuri-item-placeholder". So maybe worth for others or as idea to improve documentation.

**Comment by niklasramo** [comment]
Yep, the placeholder feature would benefit from a full chapter of it's own in the docs, as well as the whole drag system. Also I'm guessing there's a bunch of things that are not fully thought through with the drag placeholder as it's a new feature and not so battle-tested.
