### ISSUE TITLE
Issue with dragPlaceholder in huge nested grid

### ISSUE THREAD

**Issue by papakai** [haltu/muuri#301]
positioning of the element was really wrong, it worked nicely for the TLD items in the categories, but not for the categories itself - for any reason. If you have ideas, let me know.

![image](https://user-images.githubusercontent.com/229425/61227777-3ec16100-a725-11e9-96d4-cf4818b46c39.png)

In that cases it showed in another category block. sometimes it even doesn't show up (or maybe somewhere down in the page out of viewport maybe where I don't recognize it).

**Comment by papakai** [comment]
both grids are defined with `position: relative` their items differ. the category grid items have no height configured as of flexibility, the nested tldgrid items have it.

**Comment by niklasramo** [comment]
I need a live demo (reduced test case) to debug this one, but I suspect you are facing this issue: https://github.com/haltu/muuri/issues/298

**Comment by papakai** [comment]
I'll try to provide you a test case. Sorry for the late reply, I had been out of office.

**Comment by papakai** [comment]
@niklasramo see my email that I directly addressed to you for that demo case. HTH

**Comment by niklasramo** [comment]
As Muuri v0.9.0 is now released I recommend trying it out as it should fix some issues related to this. Let's close this one for now and reopen if need be.
