### ISSUE TITLE
Is not an Issue: How to position 5th item below the 1st item?

### ISSUE THREAD

**Issue by MasterJuan** [haltu/muuri#302]
Hey,
I am using Muuri and fits my needs till now!
First 4 items, are the ones on the 1st row and all the others fill the columns underneath.
I would like the 5th item to be stacked under the 1st item, so in the first column exist the 1st and 5th item. All the other items should be stacked underneath of 2nd / 3rd and 4th item "randomly".

Is any way to do that?

Thanks

**Comment by niklasramo** [comment]
You can use a custom layout algorithm: https://github.com/haltu/muuri#layout-

**Comment by MasterJuan** [comment]
Hey Niklas.
To be honest, I gave a try but without any good results!
From the section of how to build a custom layout algorithm I cannot understand how the values of transform: translateX( ) translateY( ) are calculated!
Can you guide me a bit?
Thanks!

**Comment by niklasramo** [comment]
Well I've explained the custom layout algorithm with the best of my abilities in the docs and here's even a live demo: https://codepen.io/niklasramo/pen/LLbLLd

The `slots` data in the layout algorithm is basically the translate values.

**Comment by MasterJuan** [comment]
Your demo is actually what I am seeing, as well!
Can you send me the code of fillGaps: false, because this is what I want to change a bit!
Thank you Niklas

**Comment by niklasramo** [comment]
Well I don't have any secret code lying around here ;) You can just poke at the repo to find what you need. All the code is there. The default layout algorithm is in the Packer folder: https://github.com/haltu/muuri/blob/master/src/Packer/Packer.js
