### ISSUE TITLE
Cannot read property 'getRootNode' of null

### ISSUE THREAD

**Issue by MasterJuan** [haltu/muuri#305]
Hello,

My website has a few pages in which the selector using for Muuri doesn't exist.
Firstly, I tried to Initialize Muuri only if the selector exists. However I noticed that if you just include the library into a page, even if without write any line of code regarding with Muuri, I am seeing this error message in my Console:

> Uncaught TypeError: Cannot read property 'getRootNode' of null

Any advise for this?

**Comment by niklasramo** [comment]
That error should not happen unless you try to initialize Muuri instance with a non-existent element. Can you provide a reduced test case (e.g. in codepen) that demonstrates this issue?

**Comment by MasterJuan** [comment]
Hey Niklas,
You are right! One of my colleagues call it in one of the JS files.
So, my question is a false alarm!

Thanks
