### ISSUE TITLE
How to loop through muuri item, item-content while integrating in Angular 6 App

### ISSUE THREAD

**Issue by khushbuS** [haltu/muuri#306]
I am trying use *ngFor to put multiple items in the grid. But for some reason, this is not working and dynamic classes like "item muuri-item muuri-item-shown" are not getting added on runtime. 
`<div class="grid">
    <div class="item" *ngFor="let widget of orderWidgets;">
      <div class="item-content" *ngIf="widget.type === 'graph'">
        <app-graph-chart title="title" [widgetModel]="widget"
                         (widgetRemoved)="removeWidget($event)"></app-graph-chart>
      </div>
      <div class="item-content" *ngIf="widget.type === 'bar'">
        <app-bar-chart title="title" [widgetModel]="widget"
                       (widgetRemoved)="removeWidget($event)"></app-bar-chart>
      </div>
      <div class="item-content" *ngIf="widget.type === 'donut'">
        <app-donut-chart title="title" [widgetModel]="widget"
                         (widgetRemoved)="removeWidget($event)"></app-donut-chart>
      </div>
    </div>
  </div>`

Any help in here?

**Comment by chiranjeevi-bhaskaruni** [comment]
how you're using muuri library in comp.ts file?

**Comment by khushbuS** [comment]
Hi, I pretty simplified the above code by this
` <div class="grid">
    <div class="item"
         *ngFor="let widget of defaultWidgets,let i=index;">
      <div class="item-content">
        <app-graph-chart  [widgetModel]="widget" *ngIf="widget.type === 'graph'"></app-graph-chart>
        <app-bar-chart [widgetModel]="widget" *ngIf="widget.type === 'bar'"></app-bar-chart>
      </div>
    </div>
  </div>`

but for some reason I had to initialize the grid in a setTimeout

setTimeout(() => {
      this.dashboardGrid = new Muuri('.grid', {
        items: '.item',
        showDuration: 600,
        showEasing: 'cubic-bezier(0.215, 0.61, 0.355, 1)',
        hideDuration: 600,
        hideEasing: 'cubic-bezier(0.215, 0.61, 0.355, 1)',
        visibleStyles: {
          opacity: '1',
          transform: 'scale(1)'
        },
        layout: {
          fillGaps: true
        },
        layoutOnResize: 200,
        layoutDuration: 600,
        layoutEasing: 'cubic-bezier(0.215, 0.61, 0.355, 1)',
        dragEnabled: true,
        dragStartPredicate: {
          handle: '.handle'
        },
        dragSortPredicate: {
          threshold: 20,
          action: 'swap'
        },
        dragReleaseDuration: 600,
        dragReleaseEasing: 'cubic-bezier(0.215, 0.61, 0.355, 1)',
      });

      this.setListeners();
    }, 1);



Otherwise it won't run. 
It's working now, but still figuring out, why do I have to initialize the grid in a setTimeout. Let me know if anyone has a clue.

Thanks

**Comment by niklasramo** [comment]
Most likely the item elements you are targeting are not in DOM when you try to init without setTimeout. I'm sure angular provides you a way to get a hold of the item element references which you can directly feed to Muuri. Using setTimeout is a bit hacky for this imho.

**Comment by chiranjeevi-bhaskaruni** [comment]
Initialize it in ngAfterViewInit lifecycle method without a timeout. It works.

**Comment by khushbuS** [comment]
Thanks @chiranjeevi-bhaskaruni , this is the better way. I have removed setTimeout and using ngAfterViewInit lifecycle method. It's working all fine.
