### ISSUE TITLE
Can't get dragPlaceholder to work.

### ISSUE THREAD

**Issue by aorozsa** [haltu/muuri#309]
My issue is simple: dragPlaceholder isn't working for me. I've searched many places online, but there isn't a definitive answer to my problem. I've checked the documentation and other people's examples, but I decided to take a page out of the Muuri live demo since that's the only working example I've come across.

Examining the source code, I added the dragPlaceholder property to my grid declaration. This is what it looks like as a whole:

`var grid = new Muuri('.grid', { // Initialise the grid`
`  layoutOnInit: false,`
`  dragEnabled: true,`
`  dragContainer: document.body,`
`  dragStartPredicate: function (item, e) {`
`    if (item === ghost) return false;`
`    return Muuri.ItemDrag.defaultStartPredicate(item, e);`
`  },`
`  dragPlaceholder: {`
`    enabled: true,`
`    duration: 400,`
`    createElement: function (item) {`
`      return item.getElement().cloneNode(true);`
`    }`
`  }`
`});`

That didn't work, so I continued digging until I discovered that there was an additional style for making the placeholder a thing, so I added the following to my styles. In case you're wondering, I just left the item class name as item.

`.item.muuri-item-placeholder {`
`  z-index: 2;`
`  margin: 0;`
`  opacity: 0.5;`
`  border-style: dashed;`
`}`

I then decided to do a little debugging. I tried adding a simple console log at the start of the createElement function to see if it was being called at all, and lo and behold, nothing was being logged to the console. For comparison, I also added one to dragStartPredicate which I know is working, and that one logged info to the console. I'm lost. Please help me out.

**Comment by niklasramo** [comment]
And you are using v0.8.0, right? I mean I can't tell from the code you posted why it isn't working. I'll try to update the demos in codepen to use the latest Muuri version and add a simple demo for placeholder.

**Comment by aorozsa** [comment]
I'm not... I'll try upgrading, then I'll post back with results.

**Comment by niklasramo** [comment]
Yep, the placeholder feature was added in 0.8.0 so that's one cause at least.

**Comment by aorozsa** [comment]
It works! Thanks a million! I need to iron out the placeholder a bit, but all I care about is that I have a placeholder. Anyway, that's really strange, because I started my project when 0.7.(something) was out, and I remember checking the live demo for inspiration shortly after getting the main part set up (which had the placeholder), so 0.8.0 must've come out right after I installed 0.7.
