### ISSUE TITLE
Drag'n'drop of multiple items

### ISSUE THREAD

**Issue by papakai** [haltu/muuri#313]
Hey @niklasramo,

would it also be possible to drag'n'drop multiple items? idea is to first select all the items by single-click (toggles class "active") and then to move all of them by one drag'n'drop action to the target grid in the order they had in the previous grid? So inserting all items at the position of the drop target.

TIA
Kai

**Comment by niklasramo** [comment]
Not out of the box, unfortunately, but that is a very useful UX pattern which I've been thinking about myself too. I'll keep it in mind and see if I can add better support for such a scenario.

**Comment by papakai** [comment]
@niklasramo thanks :-) I think we will keep using muuri and may introduce it in futher projects. Eventually I can also offer my help on features we need. I just have to bring this up to the management, but I don't expect someone not agreeing. The only problem is that I am not familiar with drag'n'drop in general and also not with your library internal. Are you open for a contributor/collaborator?

I am lead developer of https://www.npmjs.com/package/@hexonet/ispapi-apiconnector and took over maintaining idna-uts46 in a fork https://www.npmjs.com/package/idna-uts46-hx.
I was also a certain time collaborator at https://www.npmjs.com/package/pem.
At least I could also support with things like CI/CD (Travis CI), auto changelog, semantic-releasing, beautifying/minifying, ...

**Comment by niklasramo** [comment]
@papakai I do welcome all the help I can get, so yep I'm open for contributors and collaborators. The best way to contribute is via PRs squashing one feature/bug at a time and following this guide: https://github.com/haltu/muuri/blob/master/CONTRIBUTING.md 

I'm not actually even sure if I can add any collaborators to this repo as I'm not the owner of it. I haven't worked at Haltu (the owner if the repo) for quite some time, but they kindly let me maintain this project :)

**Comment by johnnyneverwalked** [comment]
This would be a great feature! Looking forward to it :)

**Comment by niklasramo** [comment]
Let's continue this conversation here: #418
