### ISSUE TITLE
[Question] "Fluid" height

### ISSUE THREAD

**Issue by agenceKanvas** [haltu/muuri#316]
Hey ! Muuri seems perfect for my project but I have a question before.
I need the heights of the blocs to fit the content inside. Is it possible ? 
For the widths, I have many blocs based on columns (12, 8, 6, 4, 3). 
Thanks !!!

**Comment by agenceKanvas** [comment]
Problem is, when I try a simple setup without any height, I have this result : http://wordpress-284843-881255.cloudwaysapps.com/demo/muuri.html
Can't drag and drop

**Comment by niklasramo** [comment]
@agenceKanvas I'm sorry, but I don't fully understand your question. Could you please elaborate a bit more and maybe provide a _reduced_ test case? I didn't fully grasp what was going on in the demo you provided.
