### ISSUE TITLE
muuri不兼容Microsoft Edge浏览器

### ISSUE THREAD

**Issue by AshangGitHub** [haltu/muuri#317]
第一次移动可以 放开就会报错，之后一直报错
![muuri报错](https://user-images.githubusercontent.com/49851744/63482925-23d4d000-c4cd-11e9-8771-1d7057e9fba9.png)
`SCRIPT438: Object doesn't support property or method 'animate'`     muuri.js (395,3)

**Comment by niklasramo** [comment]
Duplicate of #318
