### ISSUE TITLE
Muuri is not compatible with Microsoft Edge browser

### ISSUE THREAD

**Issue by AshangGitHub** [haltu/muuri#318]
When the first move is open, it will report an error, and then it will report an error all the time.

**Comment by niklasramo** [comment]
https://github.com/haltu/muuri/issues/317

**Comment by niklasramo** [comment]
I just tested and http://haltu.github.io/muuri/ works fine on Edge. Are you sure you have included the web animations polyfill: https://github.com/haltu/muuri#2-get-web-animations-polyfill-if-needed?

**Comment by niklasramo** [comment]
@AshangGitHub Are you still experiencing this with web animation polyfill? I'll close this issue if I can't reproduce the issue.
