### ISSUE TITLE
Elements in 'item' container unclickable in Mobile Safari.

### ISSUE THREAD

**Issue by emilime93** [haltu/muuri#319]
Anchors, images or anything within the 'item' container cannot be clicked. If i tap away and really try to trigger it it sometimes succeeds after a while, but even spamming doesn't always reliably trigger it.
I have tried to create my own dragPredicate which returns false immediately if any of my target elements are the event.target. I also changed the z-index and tried reposition the elements in different ways, but nothing works.

**Comment by niklasramo** [comment]
@emilime93 could you create a reduced test case and explain what you expect to happen and what really happens? Is this happening only on Mobile Safari?

**Comment by rainerborene** [comment]
Try disabling `dragEnabled` option. Mobile Safari has some incompatibilities with `touch-action` css property. See the [`dragCssProps`](https://github.com/haltu/muuri#dragcssprops-) section on the README file as well.

**Comment by D2Phoenix** [comment]
@emilime93 To fix that issue on ios I use next approach:
1) perfect scrollbar to be able to scroll 
2) and dragCssProps option as follows:
```
dragCssProps: {
        touchAction: this.platform.IOS ? 'auto' : 'none'
}
```

**Comment by niklasramo** [comment]
@D2Phoenix Hah 😄clever! Another approach would be using a drag handle (`dragStartPredicate.handle`), but of course that would set restrictions to the UI/UX.

**Comment by niklasramo** [comment]
Okay, now that v0.9.0 is released I'd in general recommend using a dedicated [dragHandle](https://github.com/haltu/muuri#grid-option-draghandle) within the item element.
