### ISSUE TITLE
Better drag handle

### ISSUE THREAD

**Issue by niklasramo** [haltu/muuri#323]
Currently Muuri supports providing drag handle via (`dragStartPredicate.handle`), but it has one major flaw... the `Dragger` instance is always instantiated for the item element and all the `dragCssProps` are applied to the item element. When you use a drag handle, most of the time you do it because you want the item element to be (for the most part) interactable (links, forms, etc) without any drag interactions getting in the way of the normal browser behaviour. So what we really need is a way to optionally instantiate the `Dragger` instance for some other element within the item element.

To make things simple we could just introduce a new option, e.g. `dragHandle`, which would be a selector for the drag handle. And then we would try to get the handle element on item instantiation with `element.querySelector()` and fall back to the item element if no element is found. I think this approach would serve most of the use cases better than the current approach.

**Comment by niklasramo** [comment]
Done in `dev` branch: https://github.com/haltu/muuri/commit/be66ba4df8337aa12408183e960c7f5c7ee783b5

**Comment by niklasramo** [comment]
Let's keep this open until it's actually landed to master branch.

**Comment by juhasev** [comment]
Niklas,

I just run into this issue! Sure enough I have components in the grid that get confused when the drag handle initialized. Any changes getting this merged up?

BTW! Thanks for the fantastic package. This is by far the best out there!

**Comment by niklasramo** [comment]
@juhasev Thanks! Always nice to hear good feedback from Muuri :)

This one gets landed with 0.9.0, but there's still quite a bit of tuning and testing to be done for the 0.9.0 release. The drag autoscrolling is the last big feature to be finished (it's around 85% done) and after that it's pretty much ready to land.
