### ISSUE TITLE
iOS: click events are not firing on grid items

### ISSUE THREAD

**Issue by robert-j** [haltu/muuri#324]
Starting with 0.8.0, click events of elements inside grid items are not firing any longer:

See [https://jsfiddle.net/325dxsbf/2/](https://jsfiddle.net/325dxsbf/2/).

Browser: Safari iOS Safari
Version: iOS 12.4

**Comment by niklasramo** [comment]
@robert-j Thanks! I will investigate.

**Comment by gaurav-verma-maropost** [comment]
I ran into the similar issue. Is there any update on this ?

**Comment by robert-j** [comment]
It seems to be an iOS 12 issue. It works with iOS >= 13.

**Comment by niklasramo** [comment]
@robert-j I think this is causing it: https://github.com/haltu/muuri/blob/master/src/Dragger/Dragger.js#L506. However, I don't know any way around it. We need to prevent the default action on "touchstart" event for browsers that don't support requested touch-action property. Let me know if you have some ideas for this.

**Comment by niklasramo** [comment]
Closing this as the issue is something that can't be fixed at the moment, at least to my knowledge.
