### ISSUE TITLE
Auto-Sorting after drag'n'drop

### ISSUE THREAD

**Issue by papakai** [haltu/muuri#326]
Hi @niklasramo 

I've tried a lot of things, but couldn't get this figured out.
I want to apply a specific custom order AFTER an item has been moved by drag'n'drop. Independent of the grid has changed or not (if not, of course resorting doesnt change things, and thus should be avoided).

I tried subscribing layoutstart event and manipulating the _items directly. This leads to having the items correctly ordered, but the view stays unchanged.
dragSortPredicate ... I don't understand how this could be done using that approach.

I know about how to sort a grid by providing new item list, but I am looking for a central place where I can apply the sort logic. Any idea / suggestion?
At least I applied a sortData function correctly, which is great ;-)

```javascript
sortData: {
      prio: function (item, element) {
        const tld = element.getAttribute('data-tld')
        return data.alltlds.indexOf(tld) - data.alltlds.length + 1
        //the highest priority corresponds to the lowest index
        //data is a global var
      }
    },
```

TIA
Kai

**Comment by niklasramo** [comment]
Hmm... 🤔 interesting scenario. Why do you allow drag and dropping in the first place if you revert the drag sort right after the drop? If you for some reason want the items to be draggable, but not cause sorting you can just return `false` within `dragSortPredicate` function.

**Comment by papakai** [comment]
thanks! not cause sorting means that dragged items will just get added to the end of the list?
Basically I just want to provide the possibility to drag'n'drop an item from one list to another one and then this needs to be ordered by the above `prio` function.

**Comment by niklasramo** [comment]
Ah, yes, that scenario makes a lot of sense actually for this behavior. I have to admit this has never crossed my mind, but yes, there is a way to do this pretty neatly with `dragSortPredicate` and piggybacking with the default predicate. Here's how:

```javascript
dragSortPredicate: function (item) {
  // Use the default predicate to determine where the item would be placed
  // if we didn't intervene.
  var result = Muuri.ItemDrag.defaultSortPredicate(item, {
    action: 'move',
    threshold: 50
  });

  // If result is `false` it means no sorting or layout will happen here.
  if (!result) return result;
  
  // Alrighty, so now we got a result. If we return it Muuri will
  // move the dragged item to correct position/grid based on the
  // result data. But we can also manipulate the data before returning
  // it. Here would be a good chance to do your own calculations to
  // check where the dragged item should be positioned and the force it.

  // E.g. this will always make the dragged item be moved as the first item.
  result.index = 0;

  // You can also manipulate action and grid.
  // Read more here: https://github.com/haltu/muuri#dragsortpredicate-
  // result.action = 'swap';
  // result.grid = fooGrid;

  return result;
}
```

If we wanted to have a really generic automatic sort _always_ before doing a layout we'd need to have some kind of hook right before this line: https://github.com/haltu/muuri/blob/master/src/Grid/Grid.js#L531, where we could manipulate the order of the items before the layout calculations are carried out and... actually, that _is_ possible already by providing your own layout function and piggybacking on the default layout algorithm: https://github.com/haltu/muuri/blob/master/src/Grid/Grid.js#L1245

So you would have to do something like this:

```javascript
var packer = new Muuri.Packer();
// ...
layout: 
function(items, width, height) {
  // The items are all the _active_ items in the grid. So if you want
  // to sort all the items before layout it might be a good idea to
  // sort both `grid._items` and the `items`. They are two
  // different arrays. The `items` argument is used by the layout
  // only and the `grid._items` is the internal state which is used
  // everywhere.
  return packer.getLayout(items, width, height, [], {
    // Define the layout options to suit you...
    fillGaps: false,
    horizontal: false,
    alignRight: false,
    alignBottom: false,
    rounding: false
  });
}
```

**Comment by papakai** [comment]
Thanks @niklasramo, sorry for my late reply - had been busy. I'll dive into this today.

**Comment by papakai** [comment]
I used the layout approach, working just fine. So many thanks for leading in the right direction including short examples. very useful and very appreciated. Saved me so much time.

Thanks @niklasramo
