### ISSUE TITLE
Should grid.synchronize() method be deprecated?

### ISSUE THREAD

**Issue by niklasramo** [haltu/muuri#332]
For the next release I've been reviewing a lot of Muuri's core functionality and reorganizing things. Part of this process has included dropping the _fat_ from the internal/public API. Personally I've never actually needed to use `grid.synchronize()` method and been wondering if anyone is using it all. If you have needed `grid.synchronize()` method I'd be very interested to hear some real-world use case scenarios.

If it turns out that nobody's is using it for anything I think it should be deprecated. It's one of those API methods that I initially planned for _potential_ future usage, but haven't really been finding usage for it.

**Comment by abishekreddy** [comment]
We use the synchronize() method for accessibility purposes. If the layout is changed after dragging an item, the DOM needs to be updated to ensure that tab order is maintained.

**Comment by niklasramo** [comment]
Yep, let's not deprecate 👍

**Comment by denseflux** [comment]
> We use the synchronize() method for accessibility purposes. If the layout is changed after dragging an item, the DOM needs to be updated to ensure that tab order is maintained.

@abishekreddy do you have an implementation of setting tabindex for accessibility purposes you could share, please? I'm needing to do this too.
