### ISSUE TITLE
Items are offset to curssor when dragged from "onload non-visible area"

### ISSUE THREAD

**Issue by hesa2020** [haltu/muuri#335]
When i have a scrollbar (overflow: auto);
If i scroll the bar to a zone that was not visible when muuri loaded the items in the list will be offseted from the curssor position.

I noticed adding a delay to muuri initialization and scrolling to the bottom makes the bottom part fine but the top becommes offsetd too.

Here is a video demo:
[https://streamable.com/yo5sk](https://streamable.com/yo5sk)

Here is a codepen demo:
[Codepen](https://codepen.io/sylvain-william-martens/pen/ExYEMmp)

**Comment by niklasramo** [comment]
As mentioned here: https://github.com/haltu/muuri#5-add-the-styles

> never ever set overflow: auto; or overflow: scroll; to the container element. Muuri's calculation logic does not account for that and you will see some item jumps when dragging starts. Always use a wrapper element for the container where you set the auto/scroll overflow values.

..but, I noticed you had used `overflow: overlay` in your demo which is something I actually have not taken into consideration in here: https://github.com/haltu/muuri/blob/master/src/utils/isScrollable.js. Although it's not really widely supported overflow value it still needs to be accounted for. I'll fix that one.

**Comment by hesa2020** [comment]
Updated my codepen demo, i removed overflows from parent and the issue is still occuring.

**Comment by niklasramo** [comment]
Did you update to this demo: https://codepen.io/sylvain-william-martens/pen/ExYEMmp? I still see `overflow:overlay` applied to `.board-column-content` elements. You need to create a wrapper around `.board-column-content` elements and give that wrapper overflow scroll/auto/overlay style.

**Comment by hesa2020** [comment]
@niklasramo This does fix the scroll/offset issue 👍 
However now items does not drops anymore into other `.board-item-content` 🤔

**Comment by niklasramo** [comment]
This seems resolved -> closing
