### ISSUE TITLE
How to drop an item at the end of the grid?

### ISSUE THREAD

**Issue by wizardnet972** [haltu/muuri#339]
I have two grids and I want to move items between. but how to move an item at the end of the target grid? I don't want to able to drop an item between items. always in the end grid.

It is something that I can do with muuri?

[Here my code](https://codepen.io/shlomilevi/pen/qBBqRxm)

**Comment by niklasramo** [comment]
Well yes, that's actually _very_ simple.

```javascript
  dragSortPredicate: function (item, e) {
    var result = Muuri.ItemDrag.defaultSortPredicate(item);
    if (result) result.index = -1;
    return result
  }
```

https://codepen.io/niklasramo/pen/vYYZMZx

**Comment by wizardnet972** [comment]
Thank you @niklasramo
