### ISSUE TITLE
Muuri is dropping an item in the wrong location

### ISSUE THREAD

**Issue by wizardnet972** [haltu/muuri#340]
I have three grids. 

When I drag an item from the `grid1` and release it not in the blank space - it return to `grid1`. which is good.

But, when I drag an item and move on another grid (say `grid2`) and release it on the blank space, then the item is return the `grid2`.

How do I fix this?

![muuri](https://user-images.githubusercontent.com/4997825/67155176-ae418080-f312-11e9-8962-59be40ab3339.gif)

**Comment by niklasramo** [comment]
This is the _designed_ behaviour, but I do understand your point too.

What you could do is store the dragged item's origin grid and index when dragging starts. If you want to restore the item to the origin grid and index you just [_send_](https://github.com/haltu/muuri#gridsend-item-grid-position-options-) it there on e.g. `dragEnd`.

If you want to restore the item during drag (e.g. when the item moves out of grid that's not the origin grid) you can use [`dragSortPredicate`](https://github.com/haltu/muuri#dragsortpredicate-) option. That's a bit more difficult task, but doable for sure.

**Comment by wizardnet972** [comment]
exactly what i did :) thank you!
