### ISSUE TITLE
Snake layout

### ISSUE THREAD

**Issue by dudo** [haltu/muuri#342]
Hello! I'm recently in need of laying out objects in a snake or sorts. 

```
1  2  3  4

8  7  6  5

9  0  N  ...
```

After scouring the web for a bit, I decided to just do it myself with brute force. Upon further conversations, and a lot of digging, I found muuri! Amazing library! I'd say that you are uniquely qualified to help me with this problem. Is this something that muuri can do? If not, is it something that is easy enough to add?

Thanks so much for your time!

**Comment by niklasramo** [comment]
Hi! This is _exactly_ what Muuri can do 😄...but there's not built-in snake layout algorithm unfortunately. So you'll have to roll up your sleeves, read a bit on how to build custom layout algorithm with Muuri (https://github.com/haltu/muuri#layout-) and then play a bit with this live demo: https://codepen.io/niklasramo/pen/LLbLLd

It sounds pretty straightforward task, especially if all your items are the same size.
