### ISSUE TITLE
Prevent Dragging back

### ISSUE THREAD

**Issue by David-Carty** [haltu/muuri#343]
I have two containers, currently implemented in sortable.js.  The elements in both containers can be sorted internally.  The elements in the left container can be dragged to the right container so that they still remain in the left container but are cloned to appear in the right container.  Elements cannot be dragged from the right container into the left container.  Is this possible to implement this in Muuri as I would like to move from sortable.js?  Any help on this matter greatly appreciated. Thanks D

**Comment by niklasramo** [comment]
Everything else but the cloning part is supported out of the box, but I guess that's no biggie to get working. Here's an example on how to clone an item: https://codepen.io/niklasramo/pen/zPVBLq, but unlike in that demo I guess you'd want to clone the item when the drag starts, right?

**Comment by David-Carty** [comment]
Thanks for the example.  Currently using sortable.js, which works nicely but lacks some of the features of Muuri.  It would be great to have the cloning, out of the box, as when creating DnD interfaces you often want to retain the elements to allow them to be dragged multiple times.

**Comment by niklasramo** [comment]
Yep, might be nice to have support for cloning in the core, especially if it's a common ux pattern. But let's see, I don't have so much time to spend on Muuri and a lot of stuff in the backlog already. Currently working on the autoscrolling during drag and that's a massive feature which has been in the backlog for a long long time.

**Comment by David-Carty** [comment]
Shoot for the stars.  Just a little polish and then Muuri is in pole position.
