### ISSUE TITLE
Using custom layout, when setWidth/setHeight are false, drag works but not drop

### ISSUE THREAD

**Issue by Bicher123** [haltu/muuri#347]
I am using Muuri's custom layout to create my own grid layout. However, I need the setWidth/setHeight to be set to false. When I do that, I cannot drag and drop between items. dragging works, but the item always goes back to its original position. 

Here is an example built off of your demo on codepen: 
https://codepen.io/bchammaa/pen/MWWEBEp

**Comment by niklasramo** [comment]
@Bicher123 Why do you need `setWidth` and `setHeight` to be `false`? If you inspect the layout with e.g. chrome dev tools you will find out that the container has `0` height, which basically means that it's non-existent to Muuri's overlap detection. When dragSortOverlap routine is carried out Muuri first checks if the dragged item overlaps any of the grids the item can be moved in/into and if Muuri does not find any grids that overlap with the item there will be no sorting.

You don't have to use Muuri's `setWidth` and `setHeight`, it's okay to set them `false` if you need to. But in order for things to work properly you need to make sure that the grid element's width and height cover all of the area where the items exist.

**Comment by Bicher123** [comment]
Oh I understand. Thank you for your quick response. I tried setting it to false was not working wit my layout. In the end I set both setHeight and setWidth to true and made sure that layout.width/layout.height are equal to the grid dimensions I want.
