### ISSUE TITLE
Saving dragged order and restore after page reload [question]

### ISSUE THREAD

**Issue by mesh-newbie** [haltu/muuri#349]
Hi, Muuri looks super cool.
Just wondering if it's possible to "save" the final dragged order of elements so that on-page reload the elements are returned to their last location?
E.g on 1st time page load order is .. 1,2,3,4,5,6
Drag some elements around... so we end with say ... 1,6,2,5,4,3... thus
On reloading the same page.. we start with 1,6,2,5,4,3

**Comment by niklasramo** [comment]
Here's an example: https://codepen.io/niklasramo/pen/YveqNN :)

**Comment by mesh-newbie** [comment]
Sweet... ta :-)
