### ISSUE TITLE
Muuri overlapping in modal

### ISSUE THREAD

**Issue by CryoEagle** [haltu/muuri#355]
Hello, I am using this demo inside my modal [https://codepen.io/niklasramo/pen/BrYaOp](https://codepen.io/niklasramo/pen/BrYaOp) but muuri displays items like that [https://imgur.com/a/5c2j21L](https://imgur.com/a/5c2j21L), when I use that inside page not within modal it displays **normally**

It seems okey after sort or resize, I tryed some magic with **boardGrid.refreshItems().layout();**, with timeout and inside muuri init object but nothing worked, can you help me ? Is problem inside css ?

**Comment by NikitaIT** [comment]
@CryoEagle you can try to change the positioning of the popup, transform: translate may not be positioned correctly in the parents(of any order) with a position other than relative. Gonna do the same. If you solved this problem, it would be nice to know more.

**Comment by sssaff** [comment]
Hi, did you manage to solve this? I have the same exact problem. Muuri inside modal doesn't display normally. If I instead use a div on my page directly everything works fine.

**Comment by CryoEagle** [comment]
@sssaff Hello, I found my project with that code,

![Výstřižekffffffff](https://user-images.githubusercontent.com/43248056/99113672-ee476580-25ef-11eb-9fe2-06694afda540.PNG)


It seems like setTimeout solved problem.

**Comment by sssaff** [comment]
> @sssaff Hello, I found my project with that code,
> 
> ![Výstřižekffffffff](https://user-images.githubusercontent.com/43248056/99113672-ee476580-25ef-11eb-9fe2-06694afda540.PNG)
> 
> It seems like setTimeout solved problem.

Thanks a lot. This works!

**Comment by niklasramo** [comment]
This seems resolved now, closing.
