### ISSUE TITLE
Item placeholder breaks when some of the items in the layout are hidden

### ISSUE THREAD

**Issue by qq164654109** [haltu/muuri#359]
After i filter by color，drag item will cause the grid to jam

console error:
muuri-0.8.0.js:389 Uncaught DOMException: Failed to execute 'animate' on 'Element': Partial keyframes are not supported.
    at ItemAnimate.start (https://haltu.github.io/muuri/scripts/vendor/muuri-0.8.0.js:389:25)
    at ItemDragPlaceholder._startAnimation (https://haltu.github.io/muuri/scripts/vendor/muuri-0.8.0.js:3191:15)
    at Ticker._step (https://haltu.github.io/muuri/scripts/vendor/muuri-0.8.0.js:1263:24)

**Comment by niklasramo** [comment]
Hi @ qq164654109! Thanks for the report 👍However, I can't repro this. Could you give me some more info (OS, browser + version) and exact steps how to reproduce this?

**Comment by qq164654109** [comment]
`win10 Google Chrome 79.0.3945.130`

https://haltu.github.io/muuri/     

>  GRID DEMO

just select any color to filter item(maybe twice)，you will see the bug when you drag item .

You can see it in the following link
https://github.com/qq164654109/my-vue/blob/master/public/images/step1.png
https://github.com/qq164654109/my-vue/blob/master/public/images/step2.png

**Comment by niklasramo** [comment]
Ah, yes! You found  a bug in the `ItemPlaceholder` class  👍 Here https://github.com/haltu/muuri/blob/master/src/Item/ItemDragPlaceholder.js#L66 logic does not account for the fact that some of the items may be hidden. So currently the placeholder works properly only if none of the items are hidden.

I actually fixed this one already in the `dev` branch: https://github.com/haltu/muuri/blob/dev/src/Item/ItemDragPlaceholder.js#L94 ...but apparently forgot to file an issue about it here. I'll try to release the v0.9.0 as soon as possible, a _lot_ of good stuff and improvements coming along with it.

**Comment by qq164654109** [comment]
👍 good job!

**Comment by yumindeckard** [comment]
Hi, Niklas, would you please make a patch release, like `0.8.1` to fix this issue? Thanks.
