### ISSUE TITLE
multiple muuri's result in one mooshed together muuri

### ISSUE THREAD

**Issue by h3rb** [haltu/muuri#36]
It would be nice to toggle something in css to force something to remain a divider when it is 100% width

**Comment by h3rb** [comment]
basically I tried to use two muuri instances and the elements of each muuri ended up being binpacked in the same overall area.

**Comment by h3rb** [comment]
What I was trying to do initially was do this:

[   t i t l e  ]
[a] [b] [c] [d]
[  t it l e 2 ]
[e] [f] [g] [h]

I tried first to simply put them in order.
Then I tried to use two distinct muuri's but title2 got pushed below efgh, I couldn't put anything between them (it pushed them down the page under the static content).

"fillGaps" was on

**Comment by niklasramo** [comment]
Hi! Can you provide a live demo (in codepen for example)?

**Comment by h3rb** [comment]
I don't have time to right now, but it is literally by taking the demo, duplicating it, instantiating the muuri's twice, then turning on fillgaps for both muuris.

also, if you were to put <HR> between the muuris, the muuris end up below the <HR>

**Comment by h3rb** [comment]
the "title' elements were width:100%

**Comment by niklasramo** [comment]
Right. Well, I'm not fully grasping the issue here, so please try to set up the demo when you have time and I'll see what I can do =)

**Comment by h3rb** [comment]
something close to this http://codepen.io/anon/pen/LWRoWe

**Comment by niklasramo** [comment]
Hi! Thanks for the demo. There were some issues in the demo not related to Muuri. Here's a fixed version: http://codepen.io/niklasramo/pen/xqEoeo
