### ISSUE TITLE
Question on CSS transition / animation conflict for a child of an item element

### ISSUE THREAD

**Issue by nozer** [haltu/muuri#360]
In the doc, it is stated that 

> The item elements must not have any CSS transitions or animations applied to them, because they might conflict with Muuri's internal animation engine. 

If any child of an item element (and not the item itself) has CSS transitions / animations applied to them, might it also cause conflict?

**Comment by niklasramo** [comment]
Muuri animates the `transform` property of the item element and visible/hidden styles (https://github.com/haltu/muuri#visiblestyles-) of the first direct child of the item element.  All other elements have no danger of conflict :)

**Comment by nozer** [comment]
Thank you!
