### ISSUE TITLE
Sort Left to Right - When moved move cards left to Right

### ISSUE THREAD

**Issue by zsarnett** [haltu/muuri#363]
I am looking to sort these cards in a left to right order. If a card from the 2nd row is moved to the first row then all cards are shifted to the right and the last card in the first row would move to the second row. Do you or anyone have any idea how I can accomplish this? I believe the issue lies in the cards having different heights but this is a necessary piece for my project.

![image](https://user-images.githubusercontent.com/18730868/73960718-62bedc80-48d9-11ea-8b75-071fdf441b5f.png)

Video showing how other cards are moved with the card I am moving not just shifted to the right.

[![Screenshot from Gyazo](https://gyazo.com/d14580f37c41e6726b620c26dc4dde20/raw)](https://gyazo.com/d14580f37c41e6726b620c26dc4dde20)

**Comment by zsarnett** [comment]
Actually, What I have found is I want the initial sorting to be done by 1 after each other so side by side until width > gridWidth and then go back to the first column and place the next item under the first and so on. but when the items are moved / dragged they should shift down the column not side to side. 

My goal is to store the order they are in and then use that to make them consistent but be able to drag and place in columns. 

* the Items will always be the same width

**Comment by zsarnett** [comment]
I have created a customLayout that is able to sort them how the OP suggests. Would you be able to give me any guidance on how to accomplish both? I would be happy to share any more information or more detailed information on the ask. Thank you!

**Comment by zsarnett** [comment]
https://codepen.io/niklasramo/details/ppeMbK

Using this method and sorting the items into the grids my self I was able to achieve my end goal

**Comment by niklasramo** [comment]
Lovely, you managed to solve your own issue in a day 👌 and using a custom layout algorithm I suppose? That's something I've seen a lot of people struggling with.

I understand what you were trying to do and custom layout algorithm is indeed the only solution AFAIK.

**Comment by zsarnett** [comment]
I actually was able to achieve the solution without a custom layout. Since each column is the width of one card, all I had to do was set up the multiple grids for the amount of columns and then iterate through all cards and add to the grid it belonged to. Which grid was calculated via `cardIndex % columnCount`

A custom Layout using the same method may have been possible. Not sure. But since it was over multiple grids manually sending in the items seemed easier

**Comment by rcnjstudent** [comment]
> 
> 
> https://codepen.io/niklasramo/details/ppeMbK
> 
> Using this method and sorting the items into the grids my self I was able to achieve my end goal

I'm actually trying to do the same thing myself and am struggling with this, it looks like you had a solution to this but your Codepen is now taken down.  Is there a chance you could repost with the basic premise?
