### ISSUE TITLE
Probable glitch in version 0.9.0

### ISSUE THREAD

**Issue by Paol-imi** [haltu/muuri#366]
I am writing the new version of muuri-react which I will publish in conjunction with muuri 0.9.0, to add new APIs and update the changes that have been made in muuri. By testing, I realized that layout animations are not always applied.
<br>

The glitch can be played in the grid demo with version 0.9.0 of muuri:
* Apply the color filter and hide the blue boxes.
* Remove the color filter and show the blue boxes again.
* Change the sort order.

<br>
In my case the blue boxes had no animation in moving to the new position.

**Comment by niklasramo** [comment]
Hi @Paol-imi ! The dev branch (v0.9.0) is unstable and not suitable for testing yet. There's a lot of issues there and unfinished business. If you want to I can ping you when it's closer to "beta" stage.

**Comment by Paol-imi** [comment]
Sure, thanks !
