### ISSUE TITLE
DragEnd triggers click events on all nested elements.

### ISSUE THREAD

**Issue by thomasdv** [haltu/muuri#368]
If there are any click event listeners inside an item, they are triggered on drop.

I have created a simple pen:
https://codepen.io/tomage/pen/MWwBgog

Is there a way to prevent this?

**Comment by niklasramo** [comment]
Just to clarify, Muuri itself is not triggering any click events, it's just the browser's default behavior. You can of course use any of these methods depending on your use case:
* https://developer.mozilla.org/en-US/docs/Web/API/Event/stopImmediatePropagation
* https://developer.mozilla.org/en-US/docs/Web/API/Event/stopPropagation
* https://developer.mozilla.org/en-US/docs/Web/API/Event/preventDefault

**Comment by thomasdv** [comment]
When is the best time to call it? I tried to call these methods on `dragEnd` event, but it only breaks muuri and the click event is fired anyway.

**Comment by niklasramo** [comment]
Well, again it of course depends on what you are trying to do. Are you trying to prevent the default click action or event event propagation? Whichever you need to do (or maybe both?) you can just e.g. `element.addEventListener('click', (e) => e.preventDefault())`.
