### ISSUE TITLE
Tips for Creating Filter Buttons

### ISSUE THREAD

**Issue by who519** [haltu/muuri#37]
Sorry, JS noob and serial js plugin leverager here...I can usually write enough JS to gain access to a plugin, but I am having a ton of trouble creating filter buttons for Muuri. I have the plugin installed just fine, just need some examples to customize my grid based on button interactions.

Any help would be greatly appreciated!

LOVE MURRI BTW...it is a great piece of code.

**Comment by niklasramo** [comment]
Hi! Glad to hear you're enjoying Muuri =) Have you tried to check how the filtering is done in the demo page? You can check out the demo's filter function [here](https://github.com/haltu/muuri/blob/gh-pages/scripts/main.js#L122). I hope that's enough to get you started =)

**Comment by who519** [comment]
That is more than enough! Sorry I didn't think to look there first. Cheers! I will spread the good word about Muuri and I am looking forward to seeing the new version.
