### ISSUE TITLE
add item to a blank area

### ISSUE THREAD

**Issue by blitheinsz** [haltu/muuri#370]
in the grid, i have a item.  this item width: 100px height: 100px;
 hom can i  drag and move this item to a blank area?    
this blank area width:100px ; height: 100px  and belong to the grid.

**Comment by niklasramo** [comment]
unfortunately, that's not possible with the default layout algorithm and drag sort predicate.. but you can roll your own if you're into it 😉 probably going to be a bit of work though and if you do get it up and running let me know.
