### ISSUE TITLE
Just reorder DOM items?

### ISSUE THREAD

**Issue by nanawel** [haltu/muuri#376]
Hi and thanks for your great lib.

I as wondering if it was possible to use Muuri only to **filter and reorder items directly in the DOM**, without ever touching to the CSS. I just need to be able to reorder DOM elements in containers, without any fancy animation of any kind.

It's a bit weird to use this lib for such a small need, but it would still help a lot.

Regards

**Comment by niklasramo** [comment]
Here's how to sort:
```javascript
arrayOfElements.sort(comparer).forEach(element => {
  containerElement.appendChild(element);
});
```

Here's how to filter:
```javascript
arrayOfElements.forEach(el => {
  let shouldBeVisible = true; // You have to do your own logic here.
  el.style.display = shouldBeVisible ? 'block' : 'none';
})
```

Muuri is definitely overkill for your purpose 😉

**Comment by nanawel** [comment]
Haha definetely :smile: 
I'll take a look at the (much lighter) methods you mentioned.

Thanks a lot :+1:
