### ISSUE TITLE
AutoScroll on Chrome / Opera

### ISSUE THREAD

**Issue by comercialseo** [haltu/muuri#377]
Hi guys.
On first time i want to say the great job doing on this librarie. 
My question is, I have a grid whit tousand of items and, when i want to up once element form the bottom of the page to up of the page, in browsers Chrome and Opera dont scroll automatic and i have to do whit the center button of the mause.
Can I do something to resolve that problem?
I was reading all of topics and documentation of plugin and I trie all of topics whitout results.

Thanks so much!

**Comment by niklasramo** [comment]
This feat is coming to the next version: https://github.com/haltu/muuri/issues/9

When is the next version released? I don't know yet :slightly_smiling_face: sooner than later hopefully :crossed_fingers:

**Comment by comercialseo** [comment]
Okay great!
However, if I can lend a hand in the development I would like to be able to participate, I try to see the code and I tell you if I can do something.
Again, thank you so much.

**Comment by niklasramo** [comment]
@comercialseo Nice, always glad to receive a helping hand :) A good place to start would be testing the latest dev version: https://github.com/haltu/muuri/issues/373

Just reading through the docs and checking if everything works as advertised. Also, there could be a lot more tests so if that piques your interest check out the tests folder and add any tests you feel like is missing.

**Comment by niklasramo** [comment]
I'll close this issue as it will be fixed with the next release.
