### ISSUE TITLE
filter button help...again

### ISSUE THREAD

**Issue by who519** [haltu/muuri#38]
I had some luck creating a filter button using the demo js as a guide, but I have run up against another challenge. My first version worked on the first filter but then just appended the grid on every other filter. I added a rather inelegant reset of the "itemsToShow" array at the beginning of my click function to solve that problem, but it doesn't animate as nicely as the initial filter add gets progressively worse. Do you have any advice for a better solution? I apologize in advance for my basic code...still learning. Here is the js:

$(document).ready(function() {
  var filterButton = $(".filter-button");
  var items = grid.get();
  var itemsToShow = [];
  var itemsToHide = [];

      $( filterButton ).click(function(e) {

        e.preventDefault();
        var filterButtonType = $(this).attr('id');
        itemsToShow = [];

        items.forEach(function (item) {
          var $elem = $(item._element);
          var isFilterMatch = filterButtonType ? $elem.attr('data-filter-type') === filterButtonType: true;
          (isFilterMatch ? itemsToShow : itemsToHide).push(item);
          grid.hide(itemsToHide);
          grid.show(itemsToShow);

        });
      });

});

**Comment by niklasramo** [comment]
Still having troubles with this? You should create the itemsToShow and itemsToHide arrays inside the event handler and also get the items inside the event handler.

```
$(document).ready(function() {

  var $filterButton = $(".filter-button");

  $filterButton.on('click', function (e) {

    e.preventDefault();

    var items = grid.get();
    var itemsToShow = [];
    var itemsToHide = [];
    var filterButtonType = $(this).attr('id');

    items.forEach(function (item) {
      var $elem = $(item._element);
      var isFilterMatch = filterButtonType ? $elem.attr('data-filter-type') === filterButtonType: true;
      (isFilterMatch ? itemsToShow : itemsToHide).push(item);
      grid.hide(itemsToHide);
      grid.show(itemsToShow);
    });

  });

});
```

**Comment by who519** [comment]
Thanks so much, like I said still on the low side of the learning curve for jquery. I did actually get it working and realized the animations were messed up because of styles I created to identify the different filter areas. I input my actual content yesterday and it is running beautifully! Thanks again for your help and this impressive plug in!
