### ISSUE TITLE
Vertical fill ordering

### ISSUE THREAD

**Issue by austinwbest** [haltu/muuri#383]
Maybe i missed it.. When there is room for multiple columns it displays them horizontally

1 2
3 4

But vertically is needed...

1 4
2
3

Is there a method for filling vertically before moving to the next column somewhere i am missing?

Basically a horizontal fill (what it does now) vs vertical fill (what i am looking for)

**Comment by niklasramo** [comment]
Does this work for you?
```
var grid = new Muuri(elem, {
  layout: { horizontal: true }
});
```

**Comment by austinwbest** [comment]
Negative, that just puts them all in a horizontal line.. I want them to all be vertical until they hit the height max before starting the next row. As it is now it "fills" the container in a horizontal manner but im looking for it to do that vertically.

**Comment by austinwbest** [comment]
Needed:
```
|-------------------------|
| 1 4 | other stuff on the
| 2   | page here
| 3   |
|-------------------------|
```
Fills the space vertically, however what it does is
```
|-------------------------|
| 1 2 | other stuff on the
| 3 4 | page here
|     |
|-------------------------|
```
Which now leaves dead space in the first column that could be filled. Not to mention it throws the numbering all out of wack for those who would assume the first column is numbered sequentially (as most would)

**Comment by niklasramo** [comment]
https://codepen.io/niklasramo/pen/xPoVPe 🤔

**Comment by austinwbest** [comment]
Use 8 @ 100x100 (for easy math here).. Set a fixed width of say 220 (so it is 2 wide) and a height of 600.. you should end up with 1 column of 5 and 1 column of 3. That is not what it does. It stacks them left to right and leaves dead space below them.

**Comment by niklasramo** [comment]
First of all, you can't really set a fixed width for the horizontal layout algorithm (just like you can't set a fixed height for the vertical layout algorithm). And secondly, I still see no dead space: https://codepen.io/niklasramo/pen/PoPBLYP. Unless my browser shows different stuff than yours, it does exactly what you are after.

**Comment by austinwbest** [comment]
I guess that in its self would be the solution.. Being able to specify a height for the container as then it would fill to that height before going to the next column

**Comment by austinwbest** [comment]
https://imgur.com/a/aaBk9ER

Visual aid.. So i have overwritten and specified the grid container height (it is bordered) to match the height of the overall container. But as you see, the icons are not filling in the gap, they stay in the same place they are with the height not set

**Comment by austinwbest** [comment]
Got it sorted out :) Thanks bud!
