### ISSUE TITLE
on dragging -> modal with move / copy / cancel options 

### ISSUE THREAD

**Issue by juanisimioli** [haltu/muuri#384]
What if after dropping one item from gridA to gridB I want to show a modal with these 3 options:
-Move item 
-Copy item
-Cancel Movement

I´m a bit lost on how to use send, onDragEnd, and how to manage state.
Does somebody worked with some function like this?

Thanks!

**Comment by niklasramo** [comment]
Interesting usecase. Technically the item is part of the grid it is dropped in when `dragEnd` is emitted.

So if you want to "move item" you don't have to do anything, it's done.

If you want to "copy item" you need to create a clone of the dropped item _element_ and add it as a Muuri item to the originating grid into the originating index (you can store those when drag starts). Of course maybe it would make sense to clone the item when dragging starts already.

If you want to "cancel movement"  you need to `grid.send()` the dropped item back to where it came from.

The cloning (copy item) is the only part which will probably get a a bit complex as there is no built-in helpers for that in Muuri, at least not yet.

**Comment by juanisimioli** [comment]
Thanks for your reply!
Do you have an estimate of when version 0.9.0 would be available?

**Comment by niklasramo** [comment]
No estimate, sorry. I'm tracking the progress here: https://github.com/haltu/muuri/issues/373

**Comment by niklasramo** [comment]
Closing as this seems issue seems somewhat resolved and stale. And Muuri v0.9.0 is already out too ;)
