### ISSUE TITLE
Animate grid when item width changes

### ISSUE THREAD

**Issue by iamjaredsimpson** [haltu/muuri#386]
I am trying to add a button to each grid element that toggles the width to be twice as large. I have this working with the grid updating with grid.layout() and toggling a class that has the new width.

The problem is the grid animation isn't as smooth as when you delete an element. When you delete, visually it looks like the next element slides over as the item is being removed. If I have a css transition on the grow class, I have to set a timeout to wait until the animation is finished before I call the layout function. Otherwise the resulting layout is calculated while the element is in mid animation. If I have no transition and the width change is instant, there is momentary overlap of the large element and all of the others that surround it. 

Do you have any suggestions on how to make the grid animate/react to the size of element as it's growing or shrinking so that it "pushes" the surrounding elements to their new position?

**Comment by niklasramo** [comment]
Is this demo helpful (double-click the items to resize): https://codepen.io/niklasramo/pen/eYmLQXO?

The gist is that always update the dimensions of the item element instantly, but animate the inner element (or some other descendant of the item element).

**Comment by iamjaredsimpson** [comment]
Ah I see. The outer element tells grid items how to move and then the inner element is what actually does the animation of the resize. I remember now that the docs say to add styles to the inner element. That's my bad. I might need to tweak my approach, but this should be enough to point me in the right direction. Thanks!

**Comment by niklasramo** [comment]
Closing as this seems to be solved.
