### ISSUE TITLE
Version on CDNJS is still 0.5.4 - are you planning to release 0.9.0 to CDNJS?

### ISSUE THREAD

**Issue by drauch** [haltu/muuri#392]
Version on CDNJS is still 0.5.4 - are you planning to release 0.9.0 to CDNJS?

**Comment by niklasramo** [comment]
Nope, but AFAIK it does not have to be me who updates it? I've never tried to add Muuri to any CDN as far as I recall :thinking:

**Comment by drauch** [comment]
> but AFAIK it does not have to be me who updates it? I've never tried to add Muuri to any CDN as far as I recall

Oh, thought it had been you and you had some reason to hold back. In that case, I posted an update request at cdnjs.

Best regards,
D.R.
