### ISSUE TITLE
Items flicker when dragged over

### ISSUE THREAD

**Issue by Darkscanner** [haltu/muuri#393]
https://i.imgur.com/1Im5fjr.gif
As shown in this gif, list items seem to rapidly flicker between positions if I hover one item over another. The effect seems to get worse for taller items. I haven't observed this problem on other muuri lists so I'm having trouble comprehending what's different exactly.

Alternatively, a fix to this animation bug that occurs when I send items between lists, since the first effect is much less pronounced with animations turned on. https://i.imgur.com/Nx6S3c2.gif

**Comment by niklasramo** [comment]
Could you provide a reduced test case in e.g. codepen so folks can debug the issue?

In any case, this issue shoul be solved from v0.8.0 upwards. It was fixed in this PR: https://github.com/haltu/muuri/pull/262

You can finetune the dragSortHeuristics in options.

**Comment by Darkscanner** [comment]
Woops, I didn't even realize I was using an older version. Replaced my muuri file with the one you linked and it fixed the issue without having to change any of my code. Sorry for wasting your time, thanks.

**Comment by niklasramo** [comment]
Awesome, and I recommend using the latest version (v0.9.0). There are bugs in all the previous versions.

**Comment by Darkscanner** [comment]
Yeah, I'd like to go back and upgrade down the line, the current version just breaks a lot of the code I've written. I'm already pretty burnt out on this project, so right now I'm just stumbling towards the finish line lol. Muuri saved me a ton of time as apposed to building everything from scratch, so I can't thank you enough.

**Comment by niklasramo** [comment]
Super glad to hear that Muuri helped you out :muscle: 
 Good luck with finishing your project :)
