### ISSUE TITLE
uglify (minimize) error - default value of parameter in function

### ISSUE THREAD

**Issue by hackoff** [haltu/muuri#397]
from Muuri v 0.9 i am getting error from my uglify grunt module, because of using ES6 technique. Default value of parameter is not allowed in ES5.

dist/muuri.js
row 6311

function createPackerProcessor(isWorker = false) { 

should be
function createPackerProcessor(isWorker) {

**Comment by niklasramo** [comment]
@hackoff good catch! Let's make a patch release to fix this one.

**Comment by niklasramo** [comment]
Fixed: https://github.com/haltu/muuri/releases/tag/0.9.1
