### ISSUE TITLE
Drag in a div with inner scrollbar got problem

### ISSUE THREAD

**Issue by simiczhang** [haltu/muuri#399]
Add overflow-y: auto to Muuri container
Set dragEnabled as true
Set dragContainer as document.body or any container above Murri container (which is set to position:fixed)
Scroll the Muuri items a little bit
Start drag

You would see the item in drag is shown behind the cursor. See blew screenshot (it seems scroll offset is not considered) 

<img width="1170" alt="Screen Shot 2020-07-03 at 1 52 24 PM" src="https://user-images.githubusercontent.com/2820936/86436497-f1267580-bd34-11ea-8e18-73dd532c767c.png">

**Comment by simiczhang** [comment]
Work around this issue by set overflow-y:auto on the parent of Muuri container which is used as a wrapper

**Comment by niklasramo** [comment]
As stated in the docs, you should not make the grid element scrollable: https://github.com/haltu/muuri#getting-started-4. A parent/ancestor of the grid element can be made scrollable.

**Comment by simiczhang** [comment]
Thanks mate.
