### ISSUE TITLE
Random items

### ISSUE THREAD

**Issue by Mategm** [haltu/muuri#40]
Hello!
How can i make a gellery with random order of items on every loading?

Thank you!

**Comment by niklasramo** [comment]
Just [shuffle the array](http://stackoverflow.com/questions/6274339/how-can-i-shuffle-an-array/6274381#6274381) of elements you provide as the initial *items* in the options.

**Comment by mixn** [comment]
@niklasramo Thanks for this thread!

What would be the nicest way to shuffle upon, let’s say, filtering? So not just on initial load, but every filter. 

Basically a `grid.sort(grid.getItems().shuffle());` is what I’m looking for. 

Thank you in advance!
