### ISSUE TITLE
No animation after adding item

### ISSUE THREAD

**Issue by peterming3** [haltu/muuri#401]
When I use `grid.add(item)`, the item just appears in the grid without any animation. 
![load_without_animation](https://user-images.githubusercontent.com/33970143/87003044-7fa95580-c180-11ea-90cf-ceb7b099a942.gif)
I find that first put item display to 'None' and then use filter function can generate desired animation
```    
    item.style.display = 'none';
    grid.add(item)
    grid.filter(function (item) {
        return true
    })
```
![load_with_animation](https://user-images.githubusercontent.com/33970143/87003074-8b951780-c180-11ea-94ab-a078be9f8ded.gif)

Also, I tried the following code
```    
    item.style.display = 'none';
    grid.add(item)
    grid.show([item])
```
and get 

> muuri.min.js:21 Uncaught TypeError: Cannot set property '_skipNextAnimation' of undefined

I am confused on how the animation works. Could someone help to explain it?
Thanks!

**Comment by niklasramo** [comment]
@peterming3 Here's how 🙂 (might be wise to put an example of this in the docs).

```javascript
const newItems = grid.add([elemA, elemB, elemC], { active: false });
grid.show(newItems);
```

**Comment by peterming3** [comment]
@niklasramo That works! Thanks!
Another question. How can I change the animation for grid.show()

**Comment by niklasramo** [comment]
You can tweak the `showDuration`, `showEasing` and `visibleStyles` options as you wish. Unfortunately more advanced animation configuration is not available out of the box, which is something that will be addressed in the future hopefully.
