### ISSUE TITLE
[question] is there a way to keep spaces in a layout ?

### ISSUE THREAD

**Issue by daslicht** [haltu/muuri#419]
Hi,
is there a way to keep spaces in a layout so that the gaps are not filled automatically ?

**Comment by niklasramo** [comment]
If you mean the [`layout.fillGaps`](https://github.com/haltu/muuri#grid-option-layout) option then that is by default `false`, which means that the gaps should not be filled automatically by default. You can always write your own layout function to position the items as you wish if the default functionality does not suit your needs :)

**Comment by daslicht** [comment]
> 
> 
> If you mean the [`layout.fillGaps`](https://github.com/haltu/muuri#grid-option-layout) option then that is by default `false`, which means that the gaps should not be filled automatically by default. You can always write your own layout function to position the items as you wish if the default functionality does not suit your needs :)

I mean something like this:
![](https://i.imgur.com/6l6vkKD.png)

**Comment by niklasramo** [comment]
Yep, that requires a custom layout. The default layout algo can't do that.

**Comment by daslicht** [comment]
So in taht case I woudl beed to modify muuri ? or is theer already a way to creat such custom layouts ?

**Comment by niklasramo** [comment]
Yes, you can create a custom layout in Muuri -> https://github.com/haltu/muuri#grid-option-layout :)
