### ISSUE TITLE
Different layoutDuration for resize and swap/hide/other animations

### ISSUE THREAD

**Issue by bernhardberger** [haltu/muuri#421]
Is it possible (if so - how?) to have a different layoutDuration (namely 0ms / instant) when resizing while still keeping a nice and smooth animation for sorting and reordering of say 150ms?

**Comment by niklasramo** [comment]
Yes. Set [layoutOnResize](https://github.com/haltu/muuri#grid-option-layoutonresize) to `false`, and do your own logic for the resize. Calling [`grid.layout(true)`](https://github.com/haltu/muuri#grid-method-layout) will layout the items instantly without animations.
