### ISSUE TITLE
[QUESTION] MutationObserver

### ISSUE THREAD

**Issue by bernhardberger** [haltu/muuri#424]
What would be the best practice to implement a MutationObserver when using muuri grid?

Use cases:
1) lazy loading some of my elements without knowing how big they're gonna get
2) I need to adjust some margins when a user enables a setting

The problem is: I can't fire a `layout()` event on either of those actions because there are a ton of animations inbetween of varying length and it's basically impossible to time a layout event when they finish. I kind of need a debounced `layout()` call on-the-fly..

**Comment by bernhardberger** [comment]
```
 onMutate() {
      console.log('mutation');
      this.grid.refreshItems().layout(); // nothing happens
    },
```

I get a log output when the mutation occurs, but nothing happens.

If I map that method to a button and click that button manually the items get layed out correctly..

**Comment by niklasramo** [comment]
@bernhardberger Could you provide a reduced test case in e.g. codepen? There should be nothing stopping you from calling layout in a mutation observer callback AFAIK 🤔

**Comment by syfgkjasdkn** [comment]
Just to serve as a reference point, I am using ResizeObserver observer and it works. I use it roughly like this:

```js
function observeResize(grid, elements) {
  const resizeObserver = new ResizeObserver(() => {
      grid.refreshItems();
      grid.layout();
  });

  elements.forEach((el) => resizeObserver.observe(el));
}

const grid = new Muuri(...);
observerResize(grid, grid.element.querySelectorAll(".item"))
```
