### ISSUE TITLE
Muuri with tooltip on items

### ISSUE THREAD

**Issue by sssaff** [haltu/muuri#429]
Hi all
I want to have a html tooltip for each item in my grid. I have created separate divs for each grid-item and show/hide on mouse cursor. This works fine BUT the div is behind the grid-item (z-index) and I can't seem to get it on top. It looks like this: [https://imgur.com/a/FeQD1hg](https://imgur.com/a/FeQD1hg)

This happend when I have my tooltip-div inside and grid item like this:
`<div class="item">`
  `<div class="item-content">`
     Here I can the code for my grid cell
  `</div>`
  `<div class="itemtooltip">`
     Tooltip code
  `</div>`
`</div>`

My class "itemtooltip" has position absolute and is relative to class="item". This is when I get the behaviour as the image. Doesn't matter how high I set the z-index on class "itemtooltip".

I have tried to place the "itemtooltip" outside class="item" and set the transform of the tooltip div based on transform of the grid-item like this:
`$(".itemtooltip").css({ transform: "matrix(1,0,0,1,"+(tx+50)+", "+(ty+20)+")" });` where tx and ty is the transform x and y of the cell. But this has the problem when I'm dragging items between different grids. Then I need to keep track of what grid the item belongs to e.t.c. and just messes up everything and I must have the itemtooltip outside all grids.

Please give any hints on how I can get custom tooltips with html for grid cells :-)

Thanks in advance!
Staffan

**Comment by sssaff** [comment]
Hi all again

I solved it by using jQuery UI tooltip with custom HTML. So problem solved but it would still be of interest if my original problem  is solveable somehow :-)

//Staffan

**Comment by niklasramo** [comment]
In theory at least your original code sounds right and the tooltip should be placed over the item-content element inside the item element. However, in order for the tooltip (within a an item) to be above the other items (which in your picture are over the tooltip) you need to also make sure that the item element that is currently showing the tooltip has the largest z-index among the sibling item elements.
