### ISSUE TITLE
how to get the right ordered listData, after drag and sort;

### ISSUE THREAD

**Issue by webstermobile** [haltu/muuri#430]
after drag and sort , I console the listData , and its element order is not changed, how to get the right order listData;

**Comment by niklasramo** [comment]
[gird.getItems()](https://github.com/haltu/muuri#grid-method-getitems) get you the items in current order and [grid.synchronize()][https://github.com/haltu/muuri#grid-method-synchronize] orders the DOM elements to match the current order.

**Comment by webstermobile** [comment]
@niklasramo  ok , thanks ! I got it.
