### ISSUE TITLE
how does destroying grid with no elements from the grid array work?

### ISSUE THREAD

**Issue by mehdiqanavatian** [haltu/muuri#431]
Hi, I have this function:
I get the div element from another function, create a Muuri Grid for it and then add it to my collection of existing grids.
So far so good. but what if one of my grids is empty and I want to delete that grid entirely? how can I achieve that the right way?

I've tried dragReleaseEnd event it appears to work sometimes and then gets buggy and starts removing all the grids by itself.

so here's my function:
```
function addGrid(grid) {
    
    cols = document.querySelectorAll('.col');
    grids = document.querySelectorAll('.grid');

    let gIndex = "grid" + newGridID;
    newGridID++;

    grid.classList.add(gIndex)
    dragSortArray.push(gIndex);

    gIndex = "." + gIndex;

    let muuriGrid = new Muuri(gIndex, {
        dragEnabled: true,
        dragContainer: null,
        dragPlaceholder: {
            enabled: true,
            createElement(item) {
                let clone = item.getElement().cloneNode(true)
                clone.style.opacity = 0.5;
                return clone;
            },
        },
        dragSort: function () {
            return allMuuriGrids;
        }
    });
    

    
    allMuuriGrids.push(muuriGrid);


    muuriGrid.on('dragStart', function (item, event) {
        console.log(event);
        console.log(item);
    });
    muuriGrid.on('dragReleaseEnd', function (item) {
        console.log(item);
    });
}
```

Please guide me on how to destroy a grid that has become empty after the drag process.
I can get the initiating GridID in dragStart but that doesn't exist in dragReleaseEnd.

**Comment by niklasramo** [comment]
Well I don't any other way than calling [grid.destroy](https://github.com/haltu/muuri#grid-method-destroy) and you _should_ be able to call it at whatever time. If you encounter bugs with it (and apparently you do), please provide a reduced test case 
 (in e.g. codepen) that demonstrates the bug.

**Comment by mehdiqanavatian** [comment]
I mean how can you identify the origin of the item if it doesn't exist? _gridID does change to target's _gridID on dragReleaseEnd, so how do you call [unknown grid].destroy() at dragReleaseEnd?

**Comment by mehdiqanavatian** [comment]
I've updated the code and this one does work. thanks for the tip. 
Although I still feel like dragReleaseEnd should include the oldGrid in item as well as the newGrid!

```
    muuriGrid.on('dragStart', function (item, event) {
        currentDragGridCheck = item.getGrid()
    });
    muuriGrid.on('dragReleaseEnd', function (item) {

        if (currentDragGridCheck) {
            let pastGridItems = currentDragGridCheck.getItems();
            if (pastGridItems.length === 0) {

                currentDragGridCheck.destroy();
                allMuuriGrids.splice(allMuuriGrids.indexOf(currentDragGridCheck), 1);
                dragSortArray.splice(dragSortArray.indexOf(currentDragGridCheck.getElement().classList[1]), 1);
                currentDragGridCheck.getElement().parentNode.remove();
                currentDragGridCheck = null;
            }
        }
    });
```
