### ISSUE TITLE
Question: Placeholder draggable areas

### ISSUE THREAD

**Issue by justaashir** [haltu/muuri#433]
![image](https://user-images.githubusercontent.com/54057721/101244831-648c4300-372a-11eb-9f25-57e1455bddce.png)

Thanks, for this amazing library. I'm having a great time building stuff with this.
I just want to ask, if we can have draggable areas like in the image, where the content can be dragged but also can be empty?

**Comment by niklasramo** [comment]
Great to hear @justaashir :) What you are trying to accomplish is doable, but not supported out of the box, yet. You would need to create a custom [layout](https://github.com/haltu/muuri#grid-option-layout) function and custom [drag sort predicate](https://github.com/haltu/muuri#grid-option-dragsortpredicate). Unfortunately I don't have a ready-made example for you so you'll need to take a bit of a deep dive yourself to get it up and running ;)
