### ISSUE TITLE
Muuri is not defined

### ISSUE THREAD

**Issue by kkueo123456** [haltu/muuri#439]
main.js
 import VueMuuri from 'vue-muuri'
import 'vue-muuri/dist/vue-muuri.css'
Vue.use(VueMuuri)
but still Muuri is not defined

**Comment by niklasramo** [comment]
This is probably an issue with in the [vue-muuri](https://github.com/jocodev1/vue-muuri) library and not the Muuri itself, so I suggest asking this question in vue-muuri's repo instead. If you find this to be an issue in Muuri library please provide a [reduced test case](https://css-tricks.com/reduced-test-cases/).
