### ISSUE TITLE
Check if item is destroyed before test if item is present in items array

### ISSUE THREAD

**Issue by BurningTreeC** [haltu/muuri#441]
https://github.com/haltu/muuri/blob/546f56e1f620187326e1afeba5356a0f541c81a7/dist/muuri.js#L7107

Hi there, first of all thank you for this great library, I'm using it extensively here: https://burningtreec.github.io/tiddlywiki-muuri

I'm having trouble with the latest dev branch, see the line posted above. I believe the test if an item is present in the items array should be issued before checking if the item is destroyed. I get an "item.isDestroyed is not a function" error.

What do you think? Is it just something I'm doing wrong?

**Comment by niklasramo** [comment]
Hi @BurningTreeC ! First of all I have to warn you that the `dev` branch is in _very_ unstable state. It's going through a major refactoring: JS->TypeScript, breaking API changes, README might not be up to date with all the code changes, etc. But with that out of the way, I'm glad some people are still experimenting with it as there are still probably a lot of unnoticed bugs I have introduced with the JS->TypeScript refactoring.

> I believe the test if an item is present in the items array should be issued before checking if the item is destroyed.

I don't think it matters in this case at all actually and I prefer doing the cheaper (`isDestroyed()`) check first. The item class has `isDestroyed` method so it seems like you have a non-item object in the array for some reason.

If you want I can ping you when the first alpha version of the `1.0.0` version (`dev` branch) is ready for testing, but if you are testing `dev` branch now please keep in mind that there might be breaking changes introduced at any time and there might nasty bugs lingering around (which I of course would love to hear about).

**Comment by BurningTreeC** [comment]
Thanks for answering @niklasramo , yes I'm aware that the dev branch is unstable and can have nasty bugs but I want to test it anyway, I'm about to prepare my TiddlyWiki plugin for a first Muuri 1.0.0 alpha version and I'm keeping an eye on your development :+1: 

>I don't think it matters in this case at all actually and I prefer doing the cheaper (isDestroyed()) check first. The item class has isDestroyed method so it seems like you have a non-item object (maybe an HTMLElement?) in the array for some reason.

Yeah, I was thinking the same - that the isDestroyed() check will be cheaper to do first - it's possible that I have a non-item object in the array, I'll go check that and report back.

Thank you!

**Comment by BurningTreeC** [comment]
>I don't think it matters in this case at all actually and I prefer doing the cheaper (isDestroyed()) check first. The item class has isDestroyed method so it seems like you have a non-item object (maybe an HTMLElement?) in the array for some reason.

You're assumption was right, I had an HTMLElement in the array (for some reason :grin:) - thanks for pointing me in the right direction!

It would be great if you could ping me when the first alpha version of 1.0.0 is ready for testing, I'd give it a shot 100%
