### ISSUE TITLE
Muuri item with dropdown menu

### ISSUE THREAD

**Issue by kori22** [haltu/muuri#450]
Hello, need help for implementing custom html muuri.js on grid. now i am working on task management project, which is similar with asana or jira. for my case, i want make dropdown menu for every item grid for taking action every task item, but dropdown view will be placed back on next item and not working when use z-index, this i attach some screenshoot

<img width="360" alt="Screen Shot 2021-01-29 at 21 36 05" src="https://user-images.githubusercontent.com/6101157/106287955-038c7180-627a-11eb-915f-92538ef903da.png">

please some advice for handle this issue

**Comment by pip182** [comment]
Same issue here, anyone know a way to work around this?

**Comment by niklasramo** [comment]
@kori22 You need to make sure that the `item` element, which currently contains an open dropdown, has the highest z-index among all the sibling elements (or elements you want to dropdown to be over).
