### ISSUE TITLE
iterating through multiple or all grids- ajax update

### ISSUE THREAD

**Issue by hbergman** [haltu/muuri#454]

**Comment by hbergman** [comment]
super script. After trying a few libs, this was the one I finally managed to understand well enough to get the desired trick done. Thanx. I have met an issue, though. Might be really simple, so please excuse, if this is a stupid question. 
I created a site with around 85 grids, all created throught turning all containers with a specific class into muuri-grids (following one of your demos). I am trying to refresh the sitecontent with ajax (vanilla js). Right now, I have all grids within a container-div. I update the innerHTML of this container with the responsetext, recreating all grids. Now I would like to refresh every grid. I cannot figure out though, how to loop through all of the grids. Is there an object, that contains all 85 grids?
To get near the desired solution, I first tried to init all grids again, but as I have expected, muuri alerted me, that it cannot create another instance on the same element. The ajax update worked though, all containers and elements appeared...

Further explaination: the ultimate goal is to have site on which multiple users can simultanously move the items around the grids as they wish and have their site updated regularly with what the others did... much like trello-board. Saving and updating the datasrc (a txtfile for developing purposes) even with manually item-positioning within a grid already works fine. Now I need asynchronously updating without manually reloading the page. Removing and adding updated items would work fine for me too, but still the same problem: how to loop through every muuri instance in order to remove or add the instances items.

**Comment by hbergman** [comment]
Well, it was a stupid question after all. Thanx for letting me find out on my own ;) While being created all grids where stored in a variable called 'columnGrids', through which I could loop through every grid at any time, in any function I further used. 

I noticed though, that it takes up to 7 seconds to loop through every grid and update the itmes.... (remember: 89 grids). When I first load the page, it takes noticable seconds before all grids are inititated and the layout moves into order. 
Same happens, when I update the content through ajax-Request.
Is there a way to speed up that time?

**Comment by niklasramo** [comment]
I believe doing this (before initializing any grid) might help you out tremendously :)

```javascript
Muuri.defaultPacker.destroy();
Muuri.defaultPacker = new Muuri.Packer(0);
```

In the latest version of Muuri the layout happens asynchronously in web workers _by default_, which has it's pros and cons, in your case you are hitting one of the cons. I think it was a bad design choice by me in the end, shoud have left the default algorithm to be synchronous. This will be the case in the next version, where I will revert the default async behaviour.
