### ISSUE TITLE
placeholder translate issue

### ISSUE THREAD

**Issue by kkoo95** [haltu/muuri#461]
Hello, 
How come in your kanban and grid demo , the placeholder aren't shifted a bit down-right from item's position (based on item margin) like it's supposed to ? I clearly see that this shift is applied (translateX Y is added to style) but it still renders right bellow the original item.
I would like to achieve that as well but I scoured all tracks I managed to see...
Thanks for your help

**Comment by niklasramo** [comment]
Can you provide your code which behaves in an unwanted manner in e.g. codepen/codesandbox? It's hard to help out if we can't see the issue :)

**Comment by kkoo95** [comment]
here is a repro: https://codepen.io/kkoo95/pen/RwKvdbY
i understand red placeholder is shifted because of "margin: 5px" but in your demos, placeholders aren't

**Comment by niklasramo** [comment]
Ah, yes, you just need to unset the margin for the placeholder: https://codepen.io/niklasramo/pen/jOydJMb

**Comment by kkoo95** [comment]
thanks it worked 👍
