### ISSUE TITLE
[Vue] Not working toggle dragEnabled option

### ISSUE THREAD

**Issue by presetslrdev** [haltu/muuri#468]
Hi,
[Demo](https://codesandbox.io/s/busy-cloud-9922e?file=/src/components/HelloWorld.vue) on codesandbox.io

I used **muuri** with **Vue.js**.

And I can't control _dragEnabled_.
If I install _isDraggable_ **true** (line 31 on code), everything works, but it does not turn off draggable effect.
If I install _IsDraggable_ **false** (line 31 on code), it does not turn on draggable effect.

I override __settings.dragEnabled_, but this does not affect the work in any way.

Any ideas?

**Comment by niklasramo** [comment]
Changing the dragEnabled setting value after instantiation won't work and is not supposed to work, yet. There is a method for updating the settings on the fly in the dev branch version, but that version is still in very much alpha stage so I don't recommend using it in production.
