### ISSUE TITLE
Remove the # in the README.md titles 

### ISSUE THREAD

**Issue by adonyssantos** [haltu/muuri#472]

**Comment by adonyssantos** [comment]
The # that are in the README titles aren't necessary. 
The table of contents continues to function without them.

**Comment by niklasramo** [comment]
The # are actually used for controlling the urls hash fragment. E.g. if I decide to change the title I don't want the url to to change so that existing urls keep functioning. It's a bit clunky approach, but the best I could come up with the given constraints.

**Comment by adonyssantos** [comment]
For that you can place an `id` inside the `h2` or you can also create a `div` or `span` for this.

```html
<h2><div id="motivation">Motivation</div></h2>
```
