### ISSUE TITLE
Flickering effect when dragging

### ISSUE THREAD

**Issue by arcticmatt** [haltu/muuri#474]
My CSS is similar to the example in the README
```
.item {
  display: block;
  position: absolute;
  width: 100px;
  height: 100px;
  margin: 5px;
  z-index: 1;
  background: #000;
  color: #fff;
}
```

I noticed that when `background-color` is not set, there is sometimes a weird flickering effect when dragging.

https://user-images.githubusercontent.com/4356178/119605885-63b59f00-bda6-11eb-9828-d3bfe7794113.mov

When `background-color` is set, e.g. `background-color: white;`, I don't observe this effect.

https://user-images.githubusercontent.com/4356178/119605935-81830400-bda6-11eb-839b-efc83da3ec15.mov

**Comment by niklasramo** [comment]
@arcticmatt That looks more like a rendering glitch to me. Not directly related to Muuri. But good thing you've found a workaround for it already ;)
