### ISSUE TITLE
Ideas for v1.0.0

### ISSUE THREAD

**Issue by niklasramo** [haltu/muuri#48]
I just released v0.3.0 and it was a big release: API rewrite, performance optimizations, tons of bug fixes a lot of new features (including dragging items between grids). I hope the API won't change too much for the upcoming 1.0.0 version, but let's see.

In any case I'll start working on the 1.0.0 version very soon and was hoping that I would get as much feedback on the 0.3.0 version as possible so when you have the time please give me some feedback. Also, I'm very open to any feature ideas you guys have =)

**Comment by macsupport** [comment]
Ability to use localstorage to save drag position would be nice. Here is a [codepen](https://codepen.io/desandro/pen/GcDbr) with it functioning with packery.js

**Comment by niklasramo** [comment]
That's actually doable already with Muuri. There's no specific localStorage implementation in the core but there's a method for retrieving the items in order (and the elements) with `grid.getItems()` and also method for sorting the grid with `grid.sort()`. You could easily modify the demo you provided to use Muuri instead of Packery.

**Comment by o-t-w** [comment]
Have you thought of implementing this with CSS grid for layout?

**Comment by niklasramo** [comment]
@o-t-w I presume you mean that have I considered using CSS grid as the "layout engine" instead of calculating the layout with JavaScript.

The answer is yes, and no. Muuri's core idea is to provide a way to define the layout with JavaScript, and we're talking about _any_ kind of layout (not just a grid). After the layout is calculated it makes little sense (at least to me) to map that layout to CSS grid properties. It's just faster and easier to set the explicit absolute positions to the elements since we have them already.

That being said, calculating the layout with JavaScript can be a bit taxing on the performance depending on the complexity of the layout algorithm and the amount of items in the layout. So yeah, in that regard I totally see the value of having Muuri's feature set (everything except the layout part) combined with CSS grids. It's a good idea for a Muuri spin-off.

If you have some more specific ideas related to this I'm all ears 😉

**Comment by NikitaIT** [comment]
I plan to combine Muuri with @simonwep/selection-js, it would be nice to add group drag and drop with selection. This will be useful for the file(image) uploader layout.
https://simonwep.github.io/selection/

**Comment by niklasramo** [comment]
@NikitaIT That looks like lovely library that would mix well with Muuri 🙂 Can't wait to see the result if it's going to be publicly visible code.
