### ISSUE TITLE
Memory Leak? defaultPacker retaining layouts

### ISSUE THREAD

**Issue by markphilpot** [haltu/muuri#485]
In my app where we create (and clean up) lots of Grid elements, the static `defaultPacker` seems to retain every layout (including references to the dom item elements). This seems to result in memory being retained over time.

<img width="1296" alt="CleanShot 2021-07-07 at 10 31 03@2x" src="https://user-images.githubusercontent.com/46191/124804267-f3567d80-df0e-11eb-85a0-32f84c818086.png">

On reading the code, I can't tell how `Grid.defaultPacker._layouts` ever gets cleaned up. Do I just to periodically recreate the `defaultPacker` instance?

**Comment by niklasramo** [comment]
Actually yes, a memory leak! Good catch 👍 

The bug is in this line: https://github.com/haltu/muuri/blob/master/src/Packer/Packer.js#L81.

It should say this instead: `if (layout) delete this._layouts[layoutId];`

Will fix asap.

**Comment by niklasramo** [comment]
@markphilpot I created a pull request with a fix here: https://github.com/haltu/muuri/pull/486. Would you mind validating that the fix works in your use case?

**Comment by markphilpot** [comment]
> @markphilpot I created a pull request with a fix here: #486. Would you mind validating that the fix works in your use case?

Yes, the updated `delete` cleans up the layouts correctly.  Looks good 👍

**Comment by niklasramo** [comment]
This should be now fixed in the latest release: https://github.com/haltu/muuri/releases/tag/0.9.5
