### ISSUE TITLE
Handling massive amounts of items

### ISSUE THREAD

**Issue by niklasramo** [haltu/muuri#50]
I'm not sure if there exists yet a dynamic grid library which can handle a massive amount of items (10000+). Kinda like what [SlickGrid](https://github.com/mleibman/SlickGrid) is doing, but with dynamic grids. I have high hopes that I can make Muuri handle tons of items with decent responsiveness.

The rendering part will actually be the easiest part (although not easy to implement by any means). The simplest solution is just to add "display:none" to all items that are outside the viewport, which should be enough to keep the UI responsive. Sure, there are going to be problems with animating and it's going to require a lot of hair-pulling to get it right, but it's doable.

The hard part is getting the layout algorithm work fast in this kind of scenario. I have no clue how I'm gonna pull that off at the moment, but I think we can pull a rabbit or two out of the hat if we really try ;)

This kind of functionality is needed in infinitely scrolling grid layouts with lots of data, like Instagram or Pinterest for example.

Let's see if we can pull this off. Help and ideas are appreciated!

**Comment by Munoz085** [comment]
How about making a pagination? Example: Option with "Show 10/50/100" and in the footer a pagination.

**Comment by niklasramo** [comment]
Sure, pagination solves the problem, but it's not something I'd like to add to the core. Muuri's API already has .add() and .remove() methods which can be used to create pagination with logic of your choice =)

This is more about making Muuri as fast as it can be. Although, I have to admit, the use cases for this level of performance optimization would probably be pretty small.

**Comment by niklasramo** [comment]
I'm thinking this stuff will be better as a plugin, food for thought for a later time -> closing for now.
