### ISSUE TITLE
How to make a layout so that the height of the grid container is variable

### ISSUE THREAD

**Issue by jiniC** [haltu/muuri#508]
Thanks to murri for a lot of help! But I am not able to solve the following problem.
I ask the problem I want to solve with an image.
Are the following situations not supported in murri? 😥

1. I want to move box 6 down to number 7, but it is not possible.
<img width="1175" alt="murri test" src="https://user-images.githubusercontent.com/13125662/147017333-4e3816d3-8b7e-4a2d-a99f-403305c883ef.png">

2. I want to move box 4 only below number 5. But when I try this it only swaps 4 and 5.
<img width="1201" alt="murri test 2" src="https://user-images.githubusercontent.com/13125662/147017345-299480d2-334d-4b23-b10b-77a4ec9d9de6.png">
 
 This is the code under test : https://codepen.io/jiniC/pen/rNGzoBb

**Comment by niklasramo** [comment]
Hi @jiniC ! Yep, what you are trying to do is not possible with the default layout algorithm. You can create your own layout algorithm though to allow any kind of layout. Here's an example: https://codepen.io/niklasramo/pen/LLbLLd.

**Comment by jiniC** [comment]
aha thanks for the reply :D
