### ISSUE TITLE
vue demo

### ISSUE THREAD

**Issue by gogo1008** [haltu/muuri#512]
The following address and code are for reference only, I hope there is a corresponding vue version
1、demo link
https://doc.rg1008.com/docs/rg_pass_api/rg_pass_api-1djvloqj2aqi0
2、util code
https://doc.rg1008.com/docs/rg_pass_api/rg_pass_api-1djvlp0dc155k
3、demo code
https://doc.rg1008.com/docs/rg_pass_api/rg_pass_api-1djvlqrj6n510

**Comment by niklasramo** [comment]
I'm not sure what the actual issue here 🤔
