### ISSUE TITLE
Muuri with other frameworks - MaterializeCSS

### ISSUE THREAD

**Issue by SamWillson** [haltu/muuri#52]
I was trying to achieve the "Muuri kind of" effect in Materialize.

GitHub Repos - https://github.com/samwillson/muuri-materialize
GitHub Pages - https://samwillson.github.io/muuri-materialize/index.html

Visit the GitHub Pages link and you will understand the problem.

Can anyone explain which grid framework to use alongside muuri or how to integrate the other pre-developed frameworks?
Does anyone know how to fix the page?

**Comment by niklasramo** [comment]
The answer is explained in the getting started section: https://github.com/haltu/muuri#5-add-the-styles. In your example the grid container is not positioned (give it `position:relative` for example) and the items are not absolutely positioned (needs to have `position:absolute`).
