### ISSUE TITLE
TypeError in wkhtmltopdf (QtWebKit), which doesn't have Function.prototype.bind

### ISSUE THREAD

**Issue by sbj42** [haltu/muuri#523]
If [wkhtmltopdf](https://wkhtmltopdf.org/) is used to print a site that's using Muuri, a JavaScript TypeError occurs and Muuri does not work in the resulting PDF.  This is because wkhtmltopdf uses version 4 of [Qt WebKit](https://github.com/qtwebkit/qtwebkit), which is old and doesn't have `Function.prototype.bind`.

```
> wkhtmltopdf.exe --debug-javascript https://muuri.dev/ out.pdf
...
Warning: undefined:0 TypeError: 'undefined' is not a function
```

This can be worked around by adding a polyfill for `Function.prototype.bind`.

**Comment by niklasramo** [comment]
This issue is not relevant to Muuri's core as far as I can tell as Muuri is not "officially" supported in browsers that don't have `Function.prototype.bind`.
