### ISSUE TITLE
[Question] is it possible to lock an item in place while other items drag?

### ISSUE THREAD

**Issue by planetlucid** [haltu/muuri#524]
[Question] is it possible to lock an item in place while other items drag around it?

**Comment by ruudvh** [comment]
I think this is a duplicate of [#205](https://github.com/haltu/muuri/issues/205).
See @niklasramo answer here: [#205 (comment)](https://github.com/haltu/muuri/issues/205#issuecomment-417049799).

> Hmmm.. If by locked you mean item that can't be dragged or sorted then this is how you'd do it: https://codepen.io/niklasramo/pen/EEdmJr
> If you want the item to be in fixed position at all times then you can build a custom layout algorithm.
_Originally posted by @niklasramo in https://github.com/haltu/muuri/issues/205#issuecomment-417049799_

**Comment by niklasramo** [comment]
Yep, this seems to be a duplicate of #205.
