### ISSUE TITLE
Docs website

### ISSUE THREAD

**Issue by niklasramo** [haltu/muuri#525]
Muuri desperately needs a proper docs website and more official examples so let's get busy with it. This issue continues the conversation from here: https://github.com/haltu/muuri/issues/470#issuecomment-1234769169

**Comment by niklasramo** [comment]
Docs are now live here: https://docs.muuri.dev/. Thanks to @Tragio for creating the docs site 🙏

**Comment by Tragio** [comment]
@niklasramo happy to contribute 😄 the only thing missing is the Algolia Docs for the search.
