### ISSUE TITLE
Shuffling or rearrangement of 'Dashboard' cards is not accessible with keyboard.

### ISSUE THREAD

**Issue by msftedad** [haltu/muuri#529]
### Issue: ### 
'Dashboard' card is not shuffling with keyboard while using mouse 'Dashboard' card can easily be shuffled.
### Test Environment: ###
Test Environment:
OS: Windows 11 21H2 (OS Build 22000.675)
Browsers: Edge version 101.0.1210.47 (Official build) (64-bit)

### Repro steps: ###
Step 1: Open the URL: [https://nam06.safelinks.protection.outlook.com/?url=https%3A%2f%2fmuuri.dev%2f&data=05%7c01%7cv-svuppla%40microsoft.com%7cc2a2981c807d4a5da1c708da91bf0800%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c637982546939189692%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c3000%7c%7c%7c&sdata=DCelJNOEwuCKt%2fCCv84QnDeBgiQCfgV%2BjqoMfZ8vb38%3D&reserved=0 in New Edge browser.
Step 2: 'MUURI dev' page will be displayed.
Step 3: Navigate to the webpage using the tab key.
Step 4: Observe whether 'Grid memo' card can be shuffled with the keyboard or not.

### Actual result: ###
'Dashboard' card is not shuffling with keyboard while using mouse 'Dashboard' card can easily be shuffled.
### Expected result: ###
Shuffling of 'Dashboard' cards should be accessible with keyboard. This option can be provided in "..." (more options) control for each card.
### Screenshot and video: ###
 Screen shot: <img width="973" alt="Shuffling or rearrangement for Cards" src="https://user-images.githubusercontent.com/93735775/192241377-222790d1-bfe8-4490-9708-73ccfd0224a6.png">
 
Video: 

https://user-images.githubusercontent.com/93735775/192241586-c6dcb8d8-aa4c-411d-847e-83e59acd5e07.mp4

**Comment by niklasramo** [comment]
Yep, Muuri does not provide keyboard handling out of the box at the moment. But you should be able to build that functionality into your app using Muuri's [move](https://github.com/haltu/muuri#grid-method-move) and [send](https://github.com/haltu/muuri#grid-method-send) methods.
