### ISSUE TITLE
Guidance with styling the "drop zone" – e.g. where the item will end up

### ISSUE THREAD

**Issue by hemaldev** [haltu/muuri#530]
Hi! Firstly, huge thanks for this incredible library! We are using it for some internal apps in a non-profit and not being a great front-end developer this has added super-powers to our app! So many thanks 🙏 

![muuri-example-drop-zone-styling](https://user-images.githubusercontent.com/121841/195983787-7dab9cd6-e24e-451d-a3ca-ddcf4194b34e.png)

I have one question – how can the "drop-zone" styling you have in the above from your homepage be implemented, where the blue dotted border appears (and also shows the content of the item)?

I can't see any examples of this implemented in any of your amazing CodePens. If I had to guess I'd say it was tied to a grid event, maybe `dragScroll`.

Any pointers or examples on how to implement this would be greatly appreciated! Thanks again! 🙇

**Comment by niklasramo** [comment]
Check out documentation for [dragPlaceholder option](https://github.com/haltu/muuri#grid-option-dragplaceholder) ;)

**Comment by hemaldev** [comment]
> Check out documentation for [dragPlaceholder option](https://github.com/haltu/muuri#grid-option-dragplaceholder) ;)

Superb, many thanks :pray:
