### ISSUE TITLE
Question: Is it possible to do nesting in muuri

### ISSUE THREAD

**Issue by soelynn** [haltu/muuri#57]
For example, if we look at Kanban example, i want to make the board itself movable too

https://haltu.github.io/muuri/

**Comment by niklasramo** [comment]
Sure =) However, to make draggable nested grids usable you probably have to use the *handle* option in [dragStartPredicate](https://github.com/haltu/muuri#dragstartpredicate-) option.

**Comment by soelynn** [comment]
@niklasramo you're awesome. It works like a charm. Thank you so much.

I was look at hammerjs to do stopProgatation. But this is very neat. you really think of most of the edge case!!!
