### ISSUE TITLE
Connected muuri instances

### ISSUE THREAD

**Issue by niklasramo** [haltu/muuri#6]
This is a big feature, we need to make it possible to connect `Muuri` instances to allow dragging items from a container to another.

**Initial specs:**
- Allow moving and swapping items between two `Muuri` instances.
- The `Muuri` instance that from which the item is moved to another `Muuri` instance should trigger a "send" event.
- The `Muuri` instance that receives an item from another `Muuri` instance should trigger a "receive" event.

**Comment by niklasramo** [comment]
Alrighty, got started on this one. So far I've managed to create new method `muuri.sendItem()` that can be used to send an item from a Muuri instance to another. You *can* do that already by using `muuri.removeItems()` and `muuri.addItems()` methods,  but you'd need to apply some hacks to make it work nicely in all scenarios. And by working nicely I mean the item animating smoothly from it's current whereabouts to the new container into correct position.

So the `muuri.sendItem()` basically allows you to move an item to another Muuri instance smoothly, no matter in which state the item is currently in (visible, hidden, showing, hiding, dragging, releasing, active or inactive).

Additionally you can define:

* A container element for the duration of the send process (needed to make sure that the element stays visible for the duration of the process).
* Should the item be cloned and the clone moved or the actual item mutated and moved?
* Should the sending happen instantly (without animations) or with animations (as defined in options)?

It actually takes quite a bit of code to accomplish that, so that's one hack less for Muuri users to worry about ;)

However, allowing users to drag items between containers is another beast and much more complex problem than I originally thought.

The first issue is the API. How do we define the connections between the Muuri instances in the first place? When dragging starts we need to know to which Muuri instances the item can be dragged to. After exploring how others have done this I thought the method used by [Sortable.js](https://github.com/RubaXa/Sortable) would fit nicely to Muuri also. So basically we would allow users to define drag sort groups in Muuri's options: `dragSortGroup: {name: 'groupA', connections: ['groupB', 'groupC']}`.  Here we are defining that the initiated Muuri instance belongs to `'groupA'` and it's items can be dragged to groups `'groupB'` and `'groupC'`.

The second issue is that we now have to loop through all the items in all connected Muuri instances to find the best match. So we probably will need to make some performance improvements. I have a cool idea for this one which would radically reduce the amount of items that need to be iterated when finding a match, but more on that later.

The third issue is that a lot of refactoring needs to be done.

I'm now starting to understand why [Packery is still missing this feature](https://github.com/metafizzy/packery/issues/27). It's no walk in the park.

**Comment by niklasramo** [comment]
Just thought to post a little update about the progress on this one. The new Muuri instance options are now implemented as well as the calculations for determining which container's items should be matched against the dragged item. So basically everything works nicely to the point where we actually have to move to item to another container during drag without interrupting the drag process. There are a lot of different ways to handle the situation, but let's see what I'll come up to. Almost there...

**Comment by niklasramo** [comment]
Happy to announce that this feature is *almost* ready for prime time :tada: The items can now be dragged from a container to another and it works pretty smoothly. Still have to figure out the names and data for the events that get fired during container switch. And of course gotta test this one thoroughly to make sure the nastiest bugs get squashed before the next release.

**Comment by petergrice** [comment]
Can't wait! Thanks for tackling this feature.

**Comment by niklasramo** [comment]
Alrighty, this is about done now. Will be released with v0.3.0.
