### ISSUE TITLE
[Question] Disable Masonry Layout and do pure left to right layout

### ISSUE THREAD

**Issue by soelynn** [haltu/muuri#61]
Hi @niklasramo,
Currently, we only have options for layout as mentioned in https://github.com/haltu/muuri#layout-

Is pure left to right supported?

Here's the screenshot

<img width="1226" alt="screen shot 2017-06-15 at 5 29 31 pm" src="https://user-images.githubusercontent.com/3153918/27174926-46d3e03e-51f0-11e7-8581-d11b8e321e0c.png">

**Comment by niklasramo** [comment]
Nope, that kind of layout is not baked into Muuri. However, as advertised, you can provide your own layout algorithm. Here's an example how to do it: https://codepen.io/niklasramo/pen/LLbLLd. The example is a bit stupid and not practical at all, but it shows you how to fully customize the layout.

**Comment by soelynn** [comment]
Thank you for showing where to make override. I will close this issue :)

**Comment by pauldstar** [comment]
I know this thread has been closed, but for future users who may have similar needs, I edited the codepen provided by niklasramo to provide a better example of the layout requested by the OP. You can find the custom layout here: https://codepen.io/pauldstar/pen/LzEdmp

**Comment by mtuzinskiy** [comment]
I know this thread has been closed, too,  but did anybody do anything similar with never versions of Muuri?
