### ISSUE TITLE
[BUG] Problem when items are with percent dimnesions.

### ISSUE THREAD

**Issue by kstalega** [haltu/muuri#67]
Hi,

I think that there is a problem with placing grid in layout when items are sized based on percentage values:

```
.grid {
  .item {
    display: block;
    position: absolute;
    z-index: 1;
    margin: 0;
    width: 100%;
    padding: 0;

    &.w50 {
      width: 50%;
    }
    &.w25 {
      width: 50%;
    }
    &.w125 {
      width: 25%;
    }
  }
  }
```

Div with class grid is full-width, and when screen size is full hd grid starts to not fill last column. Temporary workaround is to set width like 49.9999% or 24.999%. Could you check this?

Thank you in advance.

**Comment by niklasramo** [comment]
Indeed there is a problem and it's about to be fixed in the next release which is just about ready ;)

https://github.com/haltu/muuri/issues/59

**Comment by kstalega** [comment]
Thank you very much :)! I'm looking forward for next release. BTW: great plugin, I so appreaciate your work.
