### ISSUE TITLE
More usage examples and demos

### ISSUE THREAD

**Issue by niklasramo** [haltu/muuri#7]
Would be great to have detailed usage examples with working demos.

**Comment by h3rb** [comment]
how to have multiple muuris?

**Comment by niklasramo** [comment]
http://codepen.io/niklasramo/pen/wJKMQz

**Comment by niklasramo** [comment]
I created a codepen collection for all Muuri demos: https://codepen.io/collection/AWopag/. There's not much there yet, but I'll try to add more demos there little by little. Below's a list of demo's I'm planning to add there in the near future. If you have some other demo ideas you're welcome to add your idea here. An if you're up to building a demo yourself just add a link to it here and I'll add it to the collection.

**Must have demos**

- [ ] Images in items
- [ ] Links in items
- [ ] Infinite scrolling grid
- [ ] Horizontal grid layout
- [ ] A simple todo list (with reordering by dragging)
- [ ] Full featured kanban board (with scrollable columns)

**Comment by SLiNv** [comment]
Could somebody who knows how to do nesting using Muuri share some thoughts please 👍 
For example: a subentry in Kanban board.

**Comment by niklasramo** [comment]
@SLiNv There actually is a an example of nesting in the kanban demo on [muuri's website](https://haltu.github.io/muuri/). Try sorting the kanban columns by dragging the columns' titles. The kanban board itself is a muuri instance and each column inside the board contains a muuri instance. The kanban code itself is pretty contained so you should be able to get an understanding on how it's done: https://github.com/haltu/muuri/blob/gh-pages/scripts/demo-kanban.js

**Comment by SLiNv** [comment]
@niklasramo Yes, I notice that the kanban demo is nested, but I'm working to achieve something like this:
<img width="358" alt="capture" src="https://user-images.githubusercontent.com/6207334/33895754-352ea798-df2f-11e7-8992-eb5a1e65069a.PNG">
where an entry can be a indented sub entry of another.

Could you please point out what parameters or functions I should look at? Thanks.

**Comment by niklasramo** [comment]
The codepen collection has plenty of examples nowadays to get started. It's still missing examples on how to do advanced nesting, but let's add demo of that later on.
