### ISSUE TITLE
HELP withdesign idea

### ISSUE THREAD

**Issue by PrestaShark** [haltu/muuri#70]
Hi! Im back to Muuri!
Im looking for a solution how to use Murii with ideal square items in grid where most of the items are 25% width/height and few (featured) are 50% w/h
With px values looks very nice so far.
https://codepen.io/PrestaShark/pen/LLMQYZ
But how to make it responsive to still have the same proportions? Ideas?
Media queries should do the job but maybe Muuri have instant solution?

**Comment by PrestaShark** [comment]
https://codepen.io/PrestaShark/full/LLMQYZ i feel like the boss! Muuri + Bootstrap col responsive classes and grid.refreshItems().layout(); So far so good!

**Comment by niklasramo** [comment]
Nice work @PrestaShark! The percentage dimensions do have some "hiccups" currently due to the way Muuri handles them, but it's about to be fixed: https://github.com/haltu/muuri/issues/59 ;)

**Comment by PrestaShark** [comment]
Yes @niklasramo  i have noticed that "For example if width is set to 33.333333% **the last item in the row is sometimes positioned incorrectly** to the next row's first item." 

Can't wait for 0.4.0 :)

**Comment by niklasramo** [comment]
@PrestaShark v0.4.0 is now released, try setting the [layout.rounding](https://github.com/haltu/muuri#layout-) option to false when using percentages :wink:
