### ISSUE TITLE
grouping of items

### ISSUE THREAD

**Issue by anoosurf** [haltu/muuri#71]
hi
i saw the option for dragSortGroup . is there a way we can group the items by some data field or something ?

**Comment by niklasramo** [comment]
Well you could fetch the data for dragSortGroup and dragSortWith options from the element on init if you wish.

Let's say you got an element like this:

```
<div class="grid" data-drag-sort-group="foo" data-drag-sort-with="foo,bar,baz"></div>
```

Then you could init Muuri instance like this:

```
var elem = document.querySelector('.grid');
var muuri = new Muuri(elem, {
  dragSortGroup: elem.getAttribute('data-drag-sort-group'),
  dragSortWith: elem.getAttribute('data-drag-sort-with').split(',')
})
```

But if you want to change those options dynamically after init then that's not currently possible, unfortunately. I've been thinking about adjusting the option a bit to make that possible though. For example if you want to temporarily prevent dragging from grid a to b then that's not possible currently. There are plenty of ways to make this option dynamic (using CSS selectors or allowing to define a function which returns the sort groups) so maybe we will see that in later versions.

**Comment by anoosurf** [comment]
i meant within the grid itself ( in just 1 muuri instance) can we group the items like the image below how can we do that ?
![image](https://user-images.githubusercontent.com/4696146/28258396-ad2e36e2-6aee-11e7-94bf-5780eaed13cc.png)

**Comment by niklasramo** [comment]
Yep, that is possible. You can sort the items using the sortData option and grid.sort() method. If you want to control the sorting by dragging within the grid you can provide your own [dragSortPredicate](https://github.com/haltu/muuri#dragsortpredicate-). I don't have time to build a working demo right now, but I hope you can get it working looking at those options/methods =)
