### ISSUE TITLE
Initial order of items

### ISSUE THREAD

**Issue by patristein** [haltu/muuri#77]
Hi,

I have a problem setting a initial order to dashboard items using the Muuri lib.
I tried setting sort order by function sort() with different parms (data-id values, numbers...).
Do I also need a sortData val during init?
I'm afraid I have some basically knowledge gap...

Please could you give me a hint how to achieve this?

**Comment by niklasramo** [comment]
The initial order of items is always the same order as is the order of the item elements in the DOM when Muuri is initiated. So basically you need to just reorder the DOM elements before initiating Muuri. No greater magic to it.

However, if you want use Muuri to do this for you that is possible too, check out this demo: https://codepen.io/niklasramo/pen/EvXoOG

Hope this helps :slightly_smiling_face:

**Comment by patristein** [comment]
Thanks for your quick reply! :)
At first I will try get it working with Flex and CSS.
