### ISSUE TITLE
How to set the space between items?

### ISSUE THREAD

**Issue by MuozRoberto** [haltu/muuri#79]
I tried setting some padding to items, but with no result.

**Comment by niklasramo** [comment]
Can you please provide a demo of your issue? You can for example fork [this example](https://codepen.io/niklasramo/pen/jyJLGM) to showcase the issue.

**Comment by MunozRobert** [comment]
Hello (I'm the same guy, just changed my account).

Well, seems like it worked now: [https://codepen.io/MunozRobert/pen/mMxyjp](url)

I was trying to do that, and with your example I managed to do it. Thanks. I totally support Muuri, is pretty awesome.

**Comment by niklasramo** [comment]
Awesome, glad you got it working :slightly_smiling_face:
