### ISSUE TITLE
Drag placeholder

### ISSUE THREAD

**Issue by niklasramo** [haltu/muuri#8]
Currently there is no built-in drag placeholder. Would probably be a good usability enhancement.

**Comment by soelynn** [comment]
i am gonna give this a shot.

**Comment by soelynn** [comment]
@niklasramo may i know the release date for `v0.4`?

**Comment by niklasramo** [comment]
v0.4 is planned to be released in the end of this month, but it's almost done already. Just missing some review and unit tests. I'm planning to release it as soon as I get it finalized, probably by the end of the week if no bigger issues come up.

We can release this feature in v0.4.1 if there are no breaking API changes. If you need any help with this let me know. If you manage to pull this off before the v0.4 release we can add this to the release.

There is no contributing guidelines written down yet, but just fork the dev branch, do your thing and create a pull request. Also if you can create unit tests for the new functionality that would be awesome!

**Comment by niklasramo** [comment]
@realsoelynn how's things going with this? Can I help you out?

**Comment by realsoelynn** [comment]
@niklasramo I haven't been able to find time to work on this. I am trying this saturday. BTW i am in Singapore TimeZone :)

**Comment by niklasramo** [comment]
Yep, no worries =)

**Comment by niklasramo** [comment]
This feature is being implemented here: https://github.com/haltu/muuri/pull/194

**Comment by niklasramo** [comment]
Okay, this just went into `dev` -> will be out with the next release.
