### ISSUE TITLE
I'd like to ask you a little demo example with the filtering and seach functions (Request)

### ISSUE THREAD

**Issue by MunozRobert** [haltu/muuri#81]
Hello.
In your demo webpage [https://haltu.github.io/muuri/](https://haltu.github.io/muuri/) you display a nice Muuri demo with a complete set of functions. I'm actually a little new on jquery and I'm trying to figure out how to apply these functions to the basic [demo](https://codepen.io/niklasramo/pen/jyJLGM) you provided to us. Some help would be greatly appreciated.

Thank you.

**Comment by niklasramo** [comment]
Hi! I totally understand if using Muuri feels a bit overwhelming at first, but once you get your hands dirty and read the docs it will get easier =)

I'll add more and more Muuri examples [here ](https://codepen.io/collection/AWopag/)whenever I have time. Also check out [this issue](https://github.com/haltu/muuri/issues/7) which lists the planned demos. I'll try to add a similar demo as in the website at some point.
