### ISSUE TITLE
How I can fire layout on bs.hidden.collapse event (Question)

### ISSUE THREAD

**Issue by deybyd182** [haltu/muuri#82]
I want fires layout method on Bootstrap's bs.hidden.collapse event, but when panel collapse out, the bottom panel overlaps and when panel collapse in, the panel is positioned in the collapse out position...

![dfgdfg](https://user-images.githubusercontent.com/31019120/29877230-a78d6080-8d64-11e7-89f3-9bab8bb21777.png)

`  $('.BIT_Dashboard').on('shown.bs.collapse', function (event) {
                $grid.layout(function () {
                    $grid.refreshItems();
                });
            });
            $('.BIT_Dashboard').on('hidden.bs.collapse',  function (event) {
                $grid.layout(function () {
                    $grid.refreshItems();
                });
            });`

what I can do? or what I'm doing wrong?

**Comment by niklasramo** [comment]
I think in this situation you need to call the grid.refreshItems() method *before* the grid.layout().
