### ISSUE TITLE
Locking certain item in spot

### ISSUE THREAD

**Issue by kacpuur** [haltu/muuri#84]
Hi,

Is it possible to lock one or more items in specific spot when other items will remain draggable and float around that item without moving it?

Thanks for help

**Comment by niklasramo** [comment]
If you mean something like this: https://packery.metafizzy.co/options.html#stamp, then no. It's not yet possible out of the box. However, it is always possible to create your own layout algorithm and build that kind of functionality into it. Muuri allows you to fully customize the layout: https://codepen.io/niklasramo/pen/LLbLLd

I've been thinking about adding an option to the default layout algorithm that allows the user to define "holes" in the layout. If there's a great need for such functionality then I'll be sure to add it to Muuri.
