### ISSUE TITLE
kanban demo /hammer

### ISSUE THREAD

**Issue by diomed** [haltu/muuri#85]
how come kanban demo is so hammer dependent?
as soon as I remove hammer, only 1 tile is shown in each,
and whole list is behind? basically disappears.
is  there a way around this?

**Comment by niklasramo** [comment]
The kanban demo requires dragging the items so it Hammer.js is requierd, no way around that: https://github.com/haltu/muuri#2-get-the-dependencies

**Comment by diomed** [comment]
what if I dont want dragging? just the normal looks of it.

**Comment by niklasramo** [comment]
By default Muuri should *not* have dragging enabled and Hammer is not needed. If that's not the case then there's a bug. You have to explicitly set [dragEnabled](https://github.com/haltu/muuri#dragenabled-) to `true` to enable dragging, which requires Hammer as dependency.
