### ISSUE TITLE
Stand Alone Demo

### ISSUE THREAD

**Issue by jbreslow** [haltu/muuri#87]
How about including a "stand alone" demo that doesn't require the Search bar and footer? Just the basics!

I can't get the boxes to close without including demo-grid.js, but that file is looking for other objects that are not on the page.

**Comment by niklasramo** [comment]
Here are some basic examples: https://codepen.io/collection/AWopag/

It's not much, but you can always contribute more examples to the list if you want to. Just send me the link to your codepen demo and I'll add it to the collection.
