### ISSUE TITLE
Resize item method

### ISSUE THREAD

**Issue by baccello** [haltu/muuri#88]
Hi everybody,
Do you think realize in future a resize item method like Gridstack?

Thanks.

**Comment by niklasramo** [comment]
I don't think so.. the emphasis is now on fine-tuning the performance and adding only the planned features for v1.0.0. For v2 I'm actually planning to strip a lot of functionality from the core and creating separate drag, sort and filter plugins. At that point it would be reasonable to build a separate resize plugin for Muuri.

There's also some discussion about this here: https://github.com/haltu/muuri/issues/49#issuecomment-300261160
