### ISSUE TITLE
How to get column (x) and row (y) position of an item?

### ISSUE THREAD

**Issue by cgomezmendez** [haltu/muuri#89]
I'm trying to get position but item.getPosition() doesn't return the position relative to column and row.

**Comment by niklasramo** [comment]
Well... there actually is no concept of columns or rows in Muuri's default layout algorithm. That's why [getPosition()](https://github.com/haltu/muuri#itemgetposition) always returns item's offset from the container. You have to do the math yourself to get what you want  :neutral_face:

**Comment by cgomezmendez** [comment]
Already did it, thanks.
