### ISSUE TITLE
Scrolling while dragging

### ISSUE THREAD

**Issue by niklasramo** [haltu/muuri#9]
At least With Chrome this already happens automatically if the dragged element is within a scrollable element. However, it would be nice if Muuri allowed scrolling element(s) specified by the user when dragging occurs.

**Comment by niklasramo** [comment]
Started working on this, but realized there's much more work involved than I initially thought. Especially since Muuri supports dragging multiple items simultaneously it's going to get really interesting to figure out how to make this intuitive... imagine dragging two items simultaneously to opposite directions :slightly_smiling_face: Going to save this one for a later sprint, because there's so much new stuff ready in the dev branch I want to release.

**Comment by RamcharanG** [comment]
When are you planning to implement this ??

**Comment by niklasramo** [comment]
https://codesandbox.io/s/muuri-autoscroll-dev-17lib 🎉 Almost there... I'll be releasing 0.9.0 after I get this one finished 🙂

**Comment by douwevdijk** [comment]
Would be super awesome if you can get it done! The one thing that is missing!

**Comment by niklasramo** [comment]
The latest version of autoscroll demo updated here: https://codesandbox.io/s/muuri-autoscroll-dev-17lib... it's done (afaik). Still need to write some tests for it and then onto releasing 💪

**Comment by nevaan9** [comment]
@niklasramo any idea when v0.9.0 (I assume this feature is included in that) will be released? :)

**Comment by niklasramo** [comment]
@nevaan9 Yes, this feat will be in the next release, but unfortunately I do not have any updates on _when_ the release will happen. It's a big release all in all and still requires quite a lot of testing and writing more unit tests. I think I'll ask the community's help with testing it and possibly writing unit tests when I've first gotten all the existing issues squashed and all the features finishes I want to include in it.

I wish I had more time to dedicate to this project, but in order to do that I'd need get some financial support.

**Comment by nevaan9** [comment]
@niklasramo I understand mate. Thanks for all you do, the project is freaking awesome!
