### ISSUE TITLE
No droppable?

### ISSUE THREAD

**Issue by ALTELMA** [haltu/muuri#90]
Now I will use your plugin to do kanban board, but I need to use dragover event to move item over other element for trigger new event.

If it already exist, please let me know or suggest me for solution.
Thanks a lot.

**Comment by niklasramo** [comment]
Do you mean an event that is triggered when an item is dragged *visually* over another grid? If that's the case then yep, there is no such event.

However, there is an event similar to jQuery UI sortable's [over](http://api.jqueryui.com/sortable/#event-over). Check out [receive](https://github.com/haltu/muuri#receive) and [beforeReceive](https://github.com/haltu/muuri#beforereceive). Those two events are called when you drag an item from a container to another (before releasing the item).

**Comment by ALTELMA** [comment]
I mean draged item to drop other element in page not relate with element in grid.
Example like dropable from jQuery UI,
but I have less choice. I will do this without jQuery UI.

`$( "#droppable" ).droppable();`

Now I try to do with "dragMove" event and check dragded item position and target position closely.
Should not best solution.

Thank you for response.

**Comment by niklasramo** [comment]
Yep, using the `dragMove` event is the best (and only) solution to your problem as far as I know. Just remember that `dragMove` event is called *very* often during drag so avoid querying and/or manipulating the DOM inside it, if possible.

**Comment by ALTELMA** [comment]
Other question 
How can I stop event 'dragReleaseEnd' If I remove item from 'dragEnd' event?

When I do like this will got error _reslease is not defined.

**Comment by niklasramo** [comment]
Could you please provide some example code on codepen for example? Your issue might be caused by a multitude of reasons. Can't really tell until I see the code.
