### ISSUE TITLE
Recursion support?

### ISSUE THREAD

**Issue by tuomassalo** [haltu/muuri#95]
Is Muuri supposed to work with recursive elements, eg. arranging items in a tree? Any code samples, clues?

**Comment by niklasramo** [comment]
If you mean that can you create nested Muuri instances, then yes. An example of this is on the homepage. The kanban demo's lists can be ordered as well as the items within the lists.

**Comment by tuomassalo** [comment]
To clarify, I was thinking of something where the depth of each element can change when dragging. Something like eg.: https://mbraak.github.io/jqTree/examples/03_drag_and_drop/

Do you think Muuri hasany limitations that would make it the wrong choice for such an application?

**Comment by niklasramo** [comment]
Well, in theory I see no obstacles using Muuri to build that kind of tree structure. Should work :)
