### ISSUE TITLE
How to create a row of elements ?

### ISSUE THREAD

**Issue by zenati** [haltu/muuri#98]
Hello,

## Current result:
<img width="1190" alt="screen shot 2017-10-27 at 11 03 03" src="https://user-images.githubusercontent.com/5849907/32096408-ac2f3c4c-bb06-11e7-9950-3ae1158f79a7.png">

## Needed result:
Similar to 'row' in Bootstrap. So each row of 4 images will have a specific height:

<img width="671" alt="screen shot 2017-10-27 at 11 11 17" src="https://user-images.githubusercontent.com/5849907/32096731-9aed7344-bb07-11e7-8e6a-cf9608c04b93.png">

```
      var $grid = new Muuri('.grid', {
        dragEnabled: true,
        dragStartPredicate: { distance: 30 },
      });
```

Any idea ? Thank you.

**Comment by zenati** [comment]
@niklasramo Hellon any idea ? Thanks 👍

**Comment by niklasramo** [comment]
Good question! Unfortunately, Muuri's default algorithm does not allow you to define rows like this, so you need to create a custom layout algorithm to make this happen. Here's an example how to go about doing it: https://codepen.io/niklasramo/pen/LLbLLd

**Comment by niklasramo** [comment]
Thinking about this further it would be nice if there were more layout algorithms freely available that can be used with Muuri. Adding more and more layout algorithms to Muuri's core is not the right way to do this.

So if you guys want to share your layout algorithms send me links and I'll add them to the repo.

**Comment by peregraum** [comment]
@zenati Could you please share your layout algorithm? We are in the same situation as you and we are definitely stuck!
